pbrt: api.cpp File Reference
api.cpp File Reference
#include "api.h"
#include "paramset.h"
#include "color.h"
#include "scene.h"
#include "film.h"
#include "dynload.h"
#include "volume.h"
#include <map>
Classes
struct RenderOptions
struct GraphicsState
Defines
#define STATE_UNINITIALIZED 0
#define STATE_OPTIONS_BLOCK 1
#define STATE_WORLD_BLOCK 2
#define VERIFY_INITIALIZED(func)
#define VERIFY_OPTIONS(func)
#define VERIFY_WORLD(func)
Functions
COREDLL void pbrtInit ()
COREDLL void pbrtCleanup ()
COREDLL void pbrtIdentity ()
COREDLL void pbrtTranslate (float dx, float dy, float dz)
COREDLL void pbrtTransform (float tr[16])
COREDLL void pbrtConcatTransform (float tr[16])
COREDLL void pbrtRotate (float angle, float dx, float dy, float dz)
COREDLL void pbrtScale (float sx, float sy, float sz)
COREDLL void pbrtLookAt (float ex, float ey, float ez, float lx, float ly, float lz, float ux, float uy, float uz)
COREDLL void pbrtCoordinateSystem (const string &name)
COREDLL void pbrtCoordSysTransform (const string &name)
COREDLL void pbrtPixelFilter (const string &name, const ParamSet &params)
COREDLL void pbrtFilm (const string &type, const ParamSet &params)
COREDLL void pbrtSampler (const string &name, const ParamSet &params)
COREDLL void pbrtAccelerator (const string &name, const ParamSet &params)
COREDLL void pbrtSurfaceIntegrator (const string &name, const ParamSet &params)
COREDLL void pbrtVolumeIntegrator (const string &name, const ParamSet &params)
COREDLL void pbrtCamera (const string &name, const ParamSet &params)
COREDLL void pbrtSearchPath (const string &path)
COREDLL void pbrtWorldBegin ()
COREDLL void pbrtAttributeBegin ()
COREDLL void pbrtAttributeEnd ()
COREDLL void pbrtTransformBegin ()
COREDLL void pbrtTransformEnd ()
COREDLL void pbrtTexture (const string &name, const string &type, const string &texname, const ParamSet &params)
COREDLL void pbrtMaterial (const string &name, const ParamSet &params)
COREDLL void pbrtLightSource (const string &name, const ParamSet &params)
COREDLL void pbrtAreaLightSource (const string &name, const ParamSet &params)
COREDLL void pbrtShape (const string &name, const ParamSet &params)
COREDLL void pbrtReverseOrientation ()
COREDLL void pbrtVolume (const string &name, const ParamSet &params)
COREDLL void pbrtObjectBegin (const string &name)
COREDLL void pbrtObjectEnd ()
COREDLL void pbrtObjectInstance (const string &name)
COREDLL void pbrtWorldEnd ()
Variables
static int currentApiState = STATE_UNINITIALIZED
static Transform curTransform
static map< string, Transform > namedCoordinateSystems
static RenderOptions * renderOptions = NULL
static GraphicsState graphicsState
static vector< GraphicsState > pushedGraphicsStates
static vector< Transform > pushedTransforms
Define Documentation
#define STATE_OPTIONS_BLOCK 1
Definition at line 110 of file api.cpp.
Referenced by pbrtInit(), and pbrtWorldEnd().
#define STATE_UNINITIALIZED 0
Definition at line 109 of file api.cpp.
Referenced by pbrtCleanup(), and pbrtInit().
#define STATE_WORLD_BLOCK 2
Definition at line 111 of file api.cpp.
Referenced by pbrtCleanup(), and pbrtWorldBegin().
#define VERIFY_INITIALIZED (func)
Value:
if (currentApiState == STATE_UNINITIALIZED) { \
        Error("pbrtInit() must be before calling \"%s()\". " \
                "Ignoring.", func); \
        return; \
} else
Definition at line 120 of file api.cpp.
Referenced by pbrtConcatTransform(), pbrtCoordinateSystem(), pbrtCoordSysTransform(), pbrtIdentity(), pbrtLookAt(), pbrtRotate(), pbrtScale(), pbrtTransform(), and pbrtTranslate().
#define VERIFY_OPTIONS (func)
Value:
VERIFY_INITIALIZED(func); \
if (currentApiState == STATE_WORLD_BLOCK) { \
        Error("Options cannot be set inside world block; " \
                "\"%s\" not allowed.  Ignoring.", func); \
        return; \
} else
Definition at line 126 of file api.cpp.
Referenced by pbrtAccelerator(), pbrtCamera(), pbrtFilm(), pbrtPixelFilter(), pbrtSampler(), pbrtSearchPath(), pbrtSurfaceIntegrator(), pbrtVolumeIntegrator(), and pbrtWorldBegin().
#define VERIFY_WORLD (func)
Value:
VERIFY_INITIALIZED(func); \
if (currentApiState == STATE_OPTIONS_BLOCK) { \
        Error("Scene description must be inside world block; " \
                "\"%s\" not allowed. Ignoring.", func); \
        return; \
} else
Definition at line 133 of file api.cpp.
Referenced by pbrtAreaLightSource(), pbrtAttributeBegin(), pbrtAttributeEnd(), pbrtLightSource(), pbrtMaterial(), pbrtObjectBegin(), pbrtObjectEnd(), pbrtObjectInstance(), pbrtReverseOrientation(), pbrtShape(), pbrtTexture(), pbrtTransformBegin(), pbrtTransformEnd(), pbrtVolume(), and pbrtWorldEnd().
Function Documentation
COREDLL void pbrtAccelerator (const string & name, const ParamSet & params)
Definition at line 239 of file api.cpp.
References RenderOptions::AcceleratorName, RenderOptions::AcceleratorParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtAreaLightSource (const string & name, const ParamSet & params)
Definition at line 348 of file api.cpp.
References GraphicsState::areaLight, GraphicsState::areaLightParams, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtAttributeBegin ()
Definition at line 274 of file api.cpp.
References pushedGraphicsStates, pushedTransforms, and VERIFY_WORLD.
Referenced by pbrtObjectBegin(), and yyparse().
COREDLL void pbrtAttributeEnd ()
Definition at line 279 of file api.cpp.
References Error(), pushedGraphicsStates, pushedTransforms, and VERIFY_WORLD.
Referenced by pbrtObjectEnd(), and yyparse().
COREDLL void pbrtCamera (const string & name, const ParamSet & params)
Definition at line 254 of file api.cpp.
References RenderOptions::CameraName, RenderOptions::CameraParams, Transform::GetInverse(), namedCoordinateSystems, VERIFY_OPTIONS, and RenderOptions::WorldToCamera.
Referenced by yyparse().
COREDLL void pbrtCleanup ()
Definition at line 163 of file api.cpp.
References currentApiState, Error(), STATE_UNINITIALIZED, STATE_WORLD_BLOCK, and StatsCleanup().
Referenced by main().
COREDLL void pbrtConcatTransform (float tr[16])
Definition at line 191 of file api.cpp.
References VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtCoordinateSystem (const string & name)
Definition at line 213 of file api.cpp.
References namedCoordinateSystems, and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtCoordSysTransform (const string & name)
Definition at line 217 of file api.cpp.
References namedCoordinateSystems, and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtFilm (const string & type, const ParamSet & params)
Definition at line 229 of file api.cpp.
References RenderOptions::FilmName, RenderOptions::FilmParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtIdentity ()
Definition at line 174 of file api.cpp.
References VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtInit ()
Definition at line 141 of file api.cpp.
References currentApiState, Error(), STATE_OPTIONS_BLOCK, and STATE_UNINITIALIZED.
Referenced by main().
COREDLL void pbrtLightSource (const string & name, const ParamSet & params)
Definition at line 338 of file api.cpp.
References Error(), RenderOptions::lights, MakeLight(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtLookAt (float ex, float ey, float ez, float lx, float ly, float lz, float ux, float uy, float uz)
Definition at line 207 of file api.cpp.
References LookAt(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtMaterial (const string & name, const ParamSet & params)
Definition at line 333 of file api.cpp.
References GraphicsState::material, GraphicsState::materialParams, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtObjectBegin (const string & name)
Definition at line 409 of file api.cpp.
References RenderOptions::currentInstance, Error(), RenderOptions::instances, pbrtAttributeBegin(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtObjectEnd ()
Definition at line 420 of file api.cpp.
References RenderOptions::currentInstance, Error(), pbrtAttributeEnd(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtObjectInstance (const string & name)
Definition at line 428 of file api.cpp.
References RenderOptions::AcceleratorName, RenderOptions::AcceleratorParams, RenderOptions::currentInstance, Error(), RenderOptions::instances, MakeAccelerator(), RenderOptions::primitives, Severe(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtPixelFilter (const string & name, const ParamSet & params)
Definition at line 223 of file api.cpp.
References RenderOptions::FilterName, RenderOptions::FilterParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtReverseOrientation ()
Definition at line 397 of file api.cpp.
References GraphicsState::reverseOrientation, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtRotate (float angle, float dx, float dy, float dz)
Definition at line 199 of file api.cpp.
References Rotate(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtSampler (const string & name, const ParamSet & params)
Definition at line 234 of file api.cpp.
References RenderOptions::SamplerName, RenderOptions::SamplerParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtScale (float sx, float sy, float sz)
Definition at line 203 of file api.cpp.
References Scale(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtSearchPath (const string & path)
Definition at line 263 of file api.cpp.
References RenderOptions::gotSearchPath, UpdatePluginPath(), and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtShape (const string & name, const ParamSet & params)
Definition at line 354 of file api.cpp.
References GraphicsState::areaLight, GraphicsState::areaLightParams, RenderOptions::currentInstance, GraphicsState::floatTextures, RenderOptions::lights, MakeAreaLight(), MakeMaterial(), MakeShape(), GraphicsState::material, GraphicsState::materialParams, RenderOptions::primitives, ParamSet::ReportUnused(), GraphicsState::reverseOrientation, Severe(), GraphicsState::spectrumTextures, VERIFY_WORLD, and Warning().
Referenced by yyparse().
COREDLL void pbrtSurfaceIntegrator (const string & name, const ParamSet & params)
Definition at line 244 of file api.cpp.
References RenderOptions::SurfIntegratorName, RenderOptions::SurfIntegratorParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtTexture (const string & name, const string & type, const string & texname, const ParamSet & params)
Definition at line 305 of file api.cpp.
References Error(), GraphicsState::floatTextures, MakeFloatTexture(), MakeSpectrumTexture(), GraphicsState::spectrumTextures, VERIFY_WORLD, and Warning().
Referenced by yyparse().
COREDLL void pbrtTransform (float tr[16])
Definition at line 183 of file api.cpp.
References VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtTransformBegin ()
Definition at line 291 of file api.cpp.
References pushedTransforms, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtTransformEnd ()
Definition at line 295 of file api.cpp.
References Error(), pushedTransforms, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtTranslate (float dx, float dy, float dz)
Definition at line 178 of file api.cpp.
References Translate(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtVolume (const string & name, const ParamSet & params)
Definition at line 402 of file api.cpp.
References MakeVolumeRegion(), VERIFY_WORLD, and RenderOptions::volumeRegions.
Referenced by yyparse().
COREDLL void pbrtVolumeIntegrator (const string & name, const ParamSet & params)
Definition at line 249 of file api.cpp.
References VERIFY_OPTIONS, RenderOptions::VolIntegratorName, and RenderOptions::VolIntegratorParams.
Referenced by yyparse().
COREDLL void pbrtWorldBegin ()
Definition at line 268 of file api.cpp.
References currentApiState, namedCoordinateSystems, STATE_WORLD_BLOCK, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtWorldEnd ()
Definition at line 458 of file api.cpp.
References currentApiState, RenderOptions::gotSearchPath, RenderOptions::MakeScene(), namedCoordinateSystems, pushedGraphicsStates, pushedTransforms, Scene::Render(), Severe(), STATE_OPTIONS_BLOCK, StatsPrint(), VERIFY_WORLD, and Warning().
Referenced by yyparse().
Variable Documentation
int currentApiState = STATE_UNINITIALIZED [static]
Definition at line 112 of file api.cpp.
Referenced by pbrtCleanup(), pbrtInit(), pbrtWorldBegin(), and pbrtWorldEnd().
Transform curTransform [static]
Definition at line 113 of file api.cpp.
GraphicsState graphicsState [static]
Definition at line 116 of file api.cpp.
map<string, Transform> namedCoordinateSystems [static]
Definition at line 114 of file api.cpp.
Referenced by pbrtCamera(), pbrtCoordinateSystem(), pbrtCoordSysTransform(), pbrtWorldBegin(), and pbrtWorldEnd().
vector<GraphicsState> pushedGraphicsStates [static]
Definition at line 117 of file api.cpp.
Referenced by pbrtAttributeBegin(), pbrtAttributeEnd(), and pbrtWorldEnd().
vector<Transform> pushedTransforms [static]
Definition at line 118 of file api.cpp.
Referenced by pbrtAttributeBegin(), pbrtAttributeEnd(), pbrtTransformBegin(), pbrtTransformEnd(), and pbrtWorldEnd().
RenderOptions* renderOptions = NULL [static]
Definition at line 115 of file api.cpp.