pbrt: api.h File Reference
api.h File Reference
#include "pbrt.h"
Functions
COREDLL void pbrtIdentity ()
COREDLL void pbrtTranslate (float dx, float dy, float dz)
COREDLL void pbrtRotate (float angle, float ax, float ay, float az)
COREDLL void pbrtScale (float sx, float sy, float sz)
COREDLL void pbrtLookAt (float ex, float ey, float ez, float lx, float ly, float lz, float ux, float uy, float uz)
COREDLL void pbrtConcatTransform (float transform[16])
COREDLL void pbrtTransform (float transform[16])
COREDLL void pbrtCoordinateSystem (const string &)
COREDLL void pbrtCoordSysTransform (const string &)
COREDLL void pbrtPixelFilter (const string &name, const ParamSet &params)
COREDLL void pbrtFilm (const string &type, const ParamSet &params)
COREDLL void pbrtSampler (const string &name, const ParamSet &params)
COREDLL void pbrtAccelerator (const string &name, const ParamSet &params)
COREDLL void pbrtSurfaceIntegrator (const string &name, const ParamSet &params)
COREDLL void pbrtVolumeIntegrator (const string &name, const ParamSet &params)
COREDLL void pbrtCamera (const string &, const ParamSet &cameraParams)
COREDLL void pbrtSearchPath (const string &path)
COREDLL void pbrtWorldBegin ()
COREDLL void pbrtAttributeBegin ()
COREDLL void pbrtAttributeEnd ()
COREDLL void pbrtTransformBegin ()
COREDLL void pbrtTransformEnd ()
COREDLL void pbrtTexture (const string &name, const string &type, const string &texname, const ParamSet &params)
COREDLL void pbrtMaterial (const string &name, const ParamSet &params)
COREDLL void pbrtLightSource (const string &name, const ParamSet &params)
COREDLL void pbrtAreaLightSource (const string &name, const ParamSet &params)
COREDLL void pbrtShape (const string &name, const ParamSet &params)
COREDLL void pbrtReverseOrientation ()
COREDLL void pbrtVolume (const string &name, const ParamSet &params)
COREDLL void pbrtObjectBegin (const string &name)
COREDLL void pbrtObjectEnd ()
COREDLL void pbrtObjectInstance (const string &name)
COREDLL void pbrtWorldEnd ()
Function Documentation
COREDLL void pbrtAccelerator (const string & name, const ParamSet & params)
Definition at line 239 of file api.cpp.
References RenderOptions::AcceleratorName, RenderOptions::AcceleratorParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtAreaLightSource (const string & name, const ParamSet & params)
Definition at line 348 of file api.cpp.
References GraphicsState::areaLight, GraphicsState::areaLightParams, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtAttributeBegin ()
Definition at line 274 of file api.cpp.
References pushedGraphicsStates, pushedTransforms, and VERIFY_WORLD.
Referenced by pbrtObjectBegin(), and yyparse().
COREDLL void pbrtAttributeEnd ()
Definition at line 279 of file api.cpp.
References Error(), pushedGraphicsStates, pushedTransforms, and VERIFY_WORLD.
Referenced by pbrtObjectEnd(), and yyparse().
COREDLL void pbrtCamera (const string & , const ParamSet & cameraParams)
Definition at line 254 of file api.cpp.
References RenderOptions::CameraName, RenderOptions::CameraParams, Transform::GetInverse(), namedCoordinateSystems, VERIFY_OPTIONS, and RenderOptions::WorldToCamera.
Referenced by yyparse().
COREDLL void pbrtConcatTransform (float transform[16])
Definition at line 191 of file api.cpp.
References VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtCoordinateSystem (const string &)
Definition at line 213 of file api.cpp.
References namedCoordinateSystems, and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtCoordSysTransform (const string &)
Definition at line 217 of file api.cpp.
References namedCoordinateSystems, and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtFilm (const string & type, const ParamSet & params)
Definition at line 229 of file api.cpp.
References RenderOptions::FilmName, RenderOptions::FilmParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtIdentity ()
Definition at line 174 of file api.cpp.
References VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtLightSource (const string & name, const ParamSet & params)
Definition at line 338 of file api.cpp.
References Error(), RenderOptions::lights, MakeLight(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtLookAt (float ex, float ey, float ez, float lx, float ly, float lz, float ux, float uy, float uz)
Definition at line 207 of file api.cpp.
References LookAt(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtMaterial (const string & name, const ParamSet & params)
Definition at line 333 of file api.cpp.
References GraphicsState::material, GraphicsState::materialParams, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtObjectBegin (const string & name)
Definition at line 409 of file api.cpp.
References RenderOptions::currentInstance, Error(), RenderOptions::instances, pbrtAttributeBegin(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtObjectEnd ()
Definition at line 420 of file api.cpp.
References RenderOptions::currentInstance, Error(), pbrtAttributeEnd(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtObjectInstance (const string & name)
Definition at line 428 of file api.cpp.
References RenderOptions::AcceleratorName, RenderOptions::AcceleratorParams, RenderOptions::currentInstance, Error(), RenderOptions::instances, MakeAccelerator(), RenderOptions::primitives, Severe(), and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtPixelFilter (const string & name, const ParamSet & params)
Definition at line 223 of file api.cpp.
References RenderOptions::FilterName, RenderOptions::FilterParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtReverseOrientation ()
Definition at line 397 of file api.cpp.
References GraphicsState::reverseOrientation, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtRotate (float angle, float ax, float ay, float az)
Definition at line 199 of file api.cpp.
References Rotate(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtSampler (const string & name, const ParamSet & params)
Definition at line 234 of file api.cpp.
References RenderOptions::SamplerName, RenderOptions::SamplerParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtScale (float sx, float sy, float sz)
Definition at line 203 of file api.cpp.
References Scale(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtSearchPath (const string & path)
Definition at line 263 of file api.cpp.
References RenderOptions::gotSearchPath, UpdatePluginPath(), and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtShape (const string & name, const ParamSet & params)
Definition at line 354 of file api.cpp.
References GraphicsState::areaLight, GraphicsState::areaLightParams, RenderOptions::currentInstance, GraphicsState::floatTextures, RenderOptions::lights, MakeAreaLight(), MakeMaterial(), MakeShape(), GraphicsState::material, GraphicsState::materialParams, RenderOptions::primitives, ParamSet::ReportUnused(), GraphicsState::reverseOrientation, Severe(), GraphicsState::spectrumTextures, VERIFY_WORLD, and Warning().
Referenced by yyparse().
COREDLL void pbrtSurfaceIntegrator (const string & name, const ParamSet & params)
Definition at line 244 of file api.cpp.
References RenderOptions::SurfIntegratorName, RenderOptions::SurfIntegratorParams, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtTexture (const string & name, const string & type, const string & texname, const ParamSet & params)
Definition at line 305 of file api.cpp.
References Error(), GraphicsState::floatTextures, MakeFloatTexture(), MakeSpectrumTexture(), GraphicsState::spectrumTextures, VERIFY_WORLD, and Warning().
Referenced by yyparse().
COREDLL void pbrtTransform (float transform[16])
Definition at line 183 of file api.cpp.
References VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtTransformBegin ()
Definition at line 291 of file api.cpp.
References pushedTransforms, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtTransformEnd ()
Definition at line 295 of file api.cpp.
References Error(), pushedTransforms, and VERIFY_WORLD.
Referenced by yyparse().
COREDLL void pbrtTranslate (float dx, float dy, float dz)
Definition at line 178 of file api.cpp.
References Translate(), and VERIFY_INITIALIZED.
Referenced by yyparse().
COREDLL void pbrtVolume (const string & name, const ParamSet & params)
Definition at line 402 of file api.cpp.
References MakeVolumeRegion(), VERIFY_WORLD, and RenderOptions::volumeRegions.
Referenced by yyparse().
COREDLL void pbrtVolumeIntegrator (const string & name, const ParamSet & params)
Definition at line 249 of file api.cpp.
References VERIFY_OPTIONS, RenderOptions::VolIntegratorName, and RenderOptions::VolIntegratorParams.
Referenced by yyparse().
COREDLL void pbrtWorldBegin ()
Definition at line 268 of file api.cpp.
References currentApiState, namedCoordinateSystems, STATE_WORLD_BLOCK, and VERIFY_OPTIONS.
Referenced by yyparse().
COREDLL void pbrtWorldEnd ()
Definition at line 458 of file api.cpp.
References currentApiState, RenderOptions::gotSearchPath, RenderOptions::MakeScene(), namedCoordinateSystems, pushedGraphicsStates, pushedTransforms, Scene::Render(), Severe(), STATE_OPTIONS_BLOCK, StatsPrint(), VERIFY_WORLD, and Warning().
Referenced by yyparse().