pbrt: area.cpp File Reference
area.cpp File Reference
#include "light.h"
#include "primitive.h"
Functions
DLLEXPORT Light * CreateAreaLight (const Transform &light2world, const ParamSet &paramSet, const Reference< Shape > &shape)
Function Documentation
DLLEXPORT Light* CreateAreaLight (const Transform & light2world, const ParamSet & paramSet, const Reference< Shape > & shape)
Definition at line 106 of file area.cpp.
References AreaLight::AreaLight(), ParamSet::FindOneInt(), ParamSet::FindOneSpectrum(), AreaLight::L(), and Light::nSamples.