pbrt: bilerp.cpp File Reference
bilerp.cpp File Reference
#include "pbrt.h"
#include "texture.h"
#include "paramset.h"
Classes
class BilerpTexture< T >
Functions
DLLEXPORT Texture< float > * CreateFloatTexture (const Transform &tex2world, const TextureParams &tp)
DLLEXPORT Texture< Spectrum > * CreateSpectrumTexture (const Transform &tex2world, const TextureParams &tp)
Function Documentation
DLLEXPORT Texture<float>* CreateFloatTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 59 of file bilerp.cpp.
References Error(), TextureParams::FindFloat(), TextureParams::FindString(), TextureParams::FindVector(), and Transform::GetInverse().
DLLEXPORT Texture<Spectrum>* CreateSpectrumTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 86 of file bilerp.cpp.
References Error(), TextureParams::FindFloat(), TextureParams::FindSpectrum(), TextureParams::FindString(), TextureParams::FindVector(), and Transform::GetInverse().