pbrt: checkerboard.cpp File Reference
checkerboard.cpp File Reference
#include "pbrt.h"
#include "texture.h"
#include "paramset.h"
#include "sampling.h"
#include "shape.h"
Classes
class Checkerboard2D< T >
class Checkerboard3D< T >
Defines
#define BUMPINT(x)
#define SQRT_SAMPLES 4
#define N_SAMPLES (SQRT_SAMPLES * SQRT_SAMPLES)
#define N_SAMPLES 4
Enumerations
enum { NONE, SUPERSAMPLE, CLOSEDFORM }
Functions
DLLEXPORT Texture< float > * CreateFloatTexture (const Transform &tex2world, const TextureParams &tp)
DLLEXPORT Texture< Spectrum > * CreateSpectrumTexture (const Transform &tex2world, const TextureParams &tp)
Variables
enum { ... } aaMethod
Define Documentation
#define BUMPINT (x)
Value:
(Floor2Int((x)/2) + \
                                 2.f * max((x/2)-Floor2Int(x/2) - .5f, 0.f))
Referenced by Checkerboard2D< T >::Evaluate().
#define N_SAMPLES 4
#define N_SAMPLES (SQRT_SAMPLES * SQRT_SAMPLES)
Referenced by Checkerboard3D< T >::Evaluate(), and Checkerboard2D< T >::Evaluate().
#define SQRT_SAMPLES 4
Referenced by Checkerboard2D< T >::Evaluate().
Enumeration Type Documentation
anonymous enum
Enumerator:
NONE
SUPERSAMPLE
CLOSEDFORM
Definition at line 31 of file checkerboard.cpp.
Function Documentation
DLLEXPORT Texture<float>* CreateFloatTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 176 of file checkerboard.cpp.
References Error(), TextureParams::FindFloat(), TextureParams::FindInt(), TextureParams::FindString(), TextureParams::FindVector(), TextureParams::GetFloatTexture(), and Transform::GetInverse().
DLLEXPORT Texture<Spectrum>* CreateSpectrumTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 217 of file checkerboard.cpp.
References Error(), TextureParams::FindFloat(), TextureParams::FindInt(), TextureParams::FindString(), TextureParams::FindVector(), Transform::GetInverse(), and TextureParams::GetSpectrumTexture().
Variable Documentation
enum { ... } aaMethod
Referenced by Checkerboard2D< T >::Checkerboard2D(), and Checkerboard2D< T >::Evaluate().