pbrt: Material Class Reference
Material Class Reference
#include <material.h>
Public Member Functions
virtual BSDF * GetBSDF (const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading) const =0
virtual ~Material ()
Static Public Member Functions
static void Bump (Reference< Texture< float > > d, const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading, DifferentialGeometry *dgBump)
Detailed Description
Definition at line 33 of file material.h.
Constructor & Destructor Documentation
Material::~Material () [virtual]
Definition at line 27 of file material.cpp.
Member Function Documentation
void Material::Bump (Reference< Texture< float > > d, const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading, DifferentialGeometry * dgBump) [static]
Definition at line 29 of file material.cpp.
References Cross(), DifferentialGeometry::dndu, DifferentialGeometry::dndv, Dot(), DifferentialGeometry::dpdu, DifferentialGeometry::dpdv, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, DifferentialGeometry::nn, Normalize(), DifferentialGeometry::p, Shape::reverseOrientation, DifferentialGeometry::shape, Shape::transformSwapsHandedness, DifferentialGeometry::u, and DifferentialGeometry::v.
Referenced by UberMaterial::GetBSDF(), Translucent::GetBSDF(), Substrate::GetBSDF(), Skin::GetBSDF(), ShinyMetal::GetBSDF(), Primer::GetBSDF(), Plastic::GetBSDF(), Mirror::GetBSDF(), Matte::GetBSDF(), Glass::GetBSDF(), Felt::GetBSDF(), Clay::GetBSDF(), BrushedMetal::GetBSDF(), and BluePaint::GetBSDF().
virtual BSDF* Material::GetBSDF (const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading) const [pure virtual]
Implemented in BluePaint, BrushedMetal, Clay, Felt, Glass, Matte, Mirror, Plastic, Primer, ShinyMetal, Skin, Substrate, Translucent, and UberMaterial.
The documentation for this class was generated from the following files:
material.h
material.cpp