pbrt: IGIIntegrator Class Reference
IGIIntegrator Class Reference
Public Member Functions
IGIIntegrator (int nl, int ns, float md, float rrt, float is)
Spectrum Li (const Scene *scene, const RayDifferential &ray, const Sample *sample, float *alpha) const
void RequestSamples (Sample *sample, const Scene *scene)
void Preprocess (const Scene *)
Private Attributes
u_int nLightPaths
u_int nLightSets
vector< VirtualLight > * virtualLights
int specularDepth
int maxSpecularDepth
float minDist2
float rrThreshold
float indirectScale
int vlSetOffset
int * lightSampleOffset
int lightNumOffset
int * bsdfSampleOffset
int * bsdfComponentOffset
Detailed Description
Definition at line 41 of file igi.cpp.
Constructor & Destructor Documentation
IGIIntegrator::IGIIntegrator (int nl, int ns, float md, float rrt, float is)
Definition at line 64 of file igi.cpp.
References indirectScale, maxSpecularDepth, minDist2, nLightPaths, nLightSets, RoundUpPow2(), rrThreshold, specularDepth, and virtualLights.
Member Function Documentation
Spectrum IGIIntegrator::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [virtual]
Implements Integrator.
Definition at line 170 of file igi.cpp.
References AbsDot(), Spectrum::Black(), BSDF_REFLECTION, BSDF_SPECULAR, BSDF_TRANSMISSION, bsdfComponentOffset, bsdfSampleOffset, Ray::d, Intersection::dg, BSDF::dgShading, DistanceSquared(), DifferentialGeometry::dndu, DifferentialGeometry::dndv, Dot(), DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, BSDF::eta, BSDF::f(), Intersection::GetBSDF(), RayDifferential::hasDifferentials, indirectScale, Scene::Intersect(), Scene::IntersectP(), VirtualLight::Le, Intersection::Le(), Scene::Li(), Scene::lights, lightSampleOffset, maxSpecularDepth, minDist2, VirtualLight::n, nLightSets, DifferentialGeometry::nn, Normalize(), Ray::o, Sample::oneD, VirtualLight::p, DifferentialGeometry::p, RandomFloat(), RAY_EPSILON, rrThreshold, RayDifferential::rx, RayDifferential::ry, BSDF::Sample_f(), SmoothStep(), specularDepth, Scene::Transmittance(), UniformSampleAllLights(), virtualLights, vlSetOffset, and Spectrum::y().
void IGIIntegrator::Preprocess (const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 93 of file igi.cpp.
References AbsDot(), Spectrum::Black(), BSDF_ALL, ComputeStep1dCDF(), Ray::d, Intersection::dg, BSDF::dgShading, Floor2Int(), BSDF::FreeAll(), Intersection::GetBSDF(), Scene::Intersect(), LDShuffleScrambled1D(), LDShuffleScrambled2D(), Scene::lights, M_PI, nLightPaths, nLightSets, DifferentialGeometry::nn, DifferentialGeometry::p, RandomFloat(), BSDF::rho(), BSDF::Sample_f(), Light::Sample_L(), SampleStep1d(), Scene::Transmittance(), virtualLights, and Spectrum::y().
void IGIIntegrator::RequestSamples (Sample * sample, const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 75 of file igi.cpp.
References Sample::Add1D(), Sample::Add2D(), bsdfComponentOffset, bsdfSampleOffset, lightNumOffset, Scene::lights, lightSampleOffset, Light::nSamples, Sampler::RoundSize(), Scene::sampler, and vlSetOffset.
Member Data Documentation
int * IGIIntegrator::bsdfComponentOffset [private]
Definition at line 60 of file igi.cpp.
Referenced by Li(), and RequestSamples().
int* IGIIntegrator::bsdfSampleOffset [private]
Definition at line 60 of file igi.cpp.
Referenced by Li(), and RequestSamples().
float IGIIntegrator::indirectScale [private]
Definition at line 56 of file igi.cpp.
Referenced by IGIIntegrator(), and Li().
int IGIIntegrator::lightNumOffset [private]
Definition at line 59 of file igi.cpp.
Referenced by RequestSamples().
int* IGIIntegrator::lightSampleOffset [private]
Definition at line 59 of file igi.cpp.
Referenced by Li(), and RequestSamples().
int IGIIntegrator::maxSpecularDepth [private]
Definition at line 55 of file igi.cpp.
Referenced by IGIIntegrator(), and Li().
float IGIIntegrator::minDist2 [private]
Definition at line 56 of file igi.cpp.
Referenced by IGIIntegrator(), and Li().
u_int IGIIntegrator::nLightPaths [private]
Definition at line 52 of file igi.cpp.
Referenced by IGIIntegrator(), and Preprocess().
u_int IGIIntegrator::nLightSets [private]
Definition at line 52 of file igi.cpp.
Referenced by IGIIntegrator(), Li(), and Preprocess().
float IGIIntegrator::rrThreshold [private]
Definition at line 56 of file igi.cpp.
Referenced by IGIIntegrator(), and Li().
int IGIIntegrator::specularDepth [mutable, private]
Definition at line 54 of file igi.cpp.
Referenced by IGIIntegrator(), and Li().
vector<VirtualLight>* IGIIntegrator::virtualLights [private]
Definition at line 53 of file igi.cpp.
Referenced by IGIIntegrator(), Li(), and Preprocess().
int IGIIntegrator::vlSetOffset [private]
Definition at line 57 of file igi.cpp.
Referenced by Li(), and RequestSamples().
The documentation for this class was generated from the following file:
igi.cpp