pbrt: BRDFToBTDF Class Reference
BRDFToBTDF Class Reference
#include <reflection.h>
Public Member Functions
BRDFToBTDF (BxDF *b)
Spectrum rho (const Vector &w, int nSamples, float *samples) const
Spectrum rho (int nSamples, float *samples) const
Spectrum f (const Vector &wo, const Vector &wi) const
Spectrum Sample_f (const Vector &wo, Vector *wi, float u1, float u2, float *pdf) const
float Pdf (const Vector &wo, const Vector &wi) const
Static Public Member Functions
static Vector otherHemisphere (const Vector &w)
Private Attributes
BxDF * brdf
Detailed Description
Definition at line 143 of file reflection.h.
Constructor & Destructor Documentation
BRDFToBTDF::BRDFToBTDF (BxDF * b) [inline]
Definition at line 146 of file reflection.h.
Member Function Documentation
Spectrum BRDFToBTDF::f (const Vector & wo, const Vector & wi) const [virtual]
Implements BxDF.
Definition at line 63 of file reflection.cpp.
References brdf, BxDF::f(), and otherHemisphere().
Referenced by Sample_f().
static Vector BRDFToBTDF::otherHemisphere (const Vector & w) [inline, static]
Definition at line 151 of file reflection.h.
References Vector::x, Vector::y, and Vector::z.
Referenced by f(), and Sample_f().
float BRDFToBTDF::Pdf (const Vector & wo, const Vector & wi) const [virtual]
Reimplemented from BxDF.
Definition at line 231 of file reflection.cpp.
References brdf, and BxDF::Pdf().
Spectrum BRDFToBTDF::rho (int nSamples, float * samples) const [inline, virtual]
Reimplemented from BxDF.
Definition at line 158 of file reflection.h.
Spectrum BRDFToBTDF::rho (const Vector & w, int nSamples, float * samples) const [inline, virtual]
Reimplemented from BxDF.
Definition at line 154 of file reflection.h.
Spectrum BRDFToBTDF::Sample_f (const Vector & wo, Vector * wi, float u1, float u2, float * pdf) const [virtual]
Reimplemented from BxDF.
Definition at line 67 of file reflection.cpp.
References brdf, f(), otherHemisphere(), and BxDF::Sample_f().
Member Data Documentation
BxDF* BRDFToBTDF::brdf [private]
Definition at line 166 of file reflection.h.
Referenced by f(), Pdf(), and Sample_f().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp