pbrt: Matte Class Reference
Matte Class Reference
Public Member Functions
Matte (Reference< Texture< Spectrum > > kd, Reference< Texture< float > > sig, Reference< Texture< float > > bump)
BSDF * GetBSDF (const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading) const
Private Attributes
Reference< Texture< Spectrum > > Kd
Reference< Texture< float > > sigma
Reference< Texture< float > > bumpMap
Detailed Description
Definition at line 28 of file matte.cpp.
Constructor & Destructor Documentation
Matte::Matte (Reference< Texture< Spectrum > > kd, Reference< Texture< float > > sig, Reference< Texture< float > > bump) [inline]
Definition at line 31 of file matte.cpp.
References bumpMap, Kd, and sigma.
Member Function Documentation
BSDF * Matte::GetBSDF (const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading) const [virtual]
Implements Material.
Definition at line 46 of file matte.cpp.
References BSDF::Add(), BSDF_ALLOC, Material::Bump(), bumpMap, Clamp(), Kd, DifferentialGeometry::nn, and sigma.
Member Data Documentation
Reference<Texture<float> > Matte::bumpMap [private]
Definition at line 43 of file matte.cpp.
Referenced by GetBSDF(), and Matte().
Reference<Texture<Spectrum> > Matte::Kd [private]
Definition at line 42 of file matte.cpp.
Referenced by GetBSDF(), and Matte().
Reference<Texture<float> > Matte::sigma [private]
Definition at line 43 of file matte.cpp.
Referenced by GetBSDF(), and Matte().
The documentation for this class was generated from the following file:
matte.cpp