pbrt: Timer Class Reference
Timer Class Reference
#include <timer.h>
Public Member Functions
Timer ()
~Timer ()
void Start ()
void Stop ()
void Reset ()
double Time ()
Private Member Functions
double GetTime ()
Private Attributes
double time0
double elapsed
bool running
struct timeval timeofday
Detailed Description
Definition at line 38 of file timer.h.
Constructor & Destructor Documentation
Timer::Timer ()
Definition at line 27 of file timer.cpp.
References elapsed, running, Severe(), and time0.
Timer::~Timer ()
Definition at line 99 of file timer.cpp.
Member Function Documentation
void Timer::Start ()
Definition at line 106 of file timer.cpp.
References Assert, GetTime(), running, and time0.
Referenced by ProgressReporter::ProgressReporter(), and Time().
void Timer::Stop ()
Definition at line 113 of file timer.cpp.
References Assert, elapsed, GetTime(), running, and time0.
Referenced by Time().
void Timer::Reset ()
Definition at line 121 of file timer.cpp.
References elapsed, and running.
double Timer::Time ()
Definition at line 127 of file timer.cpp.
References elapsed, running, Start(), and Stop().
Referenced by ProgressReporter::Done(), and ProgressReporter::Update().
double Timer::GetTime () [private]
Definition at line 74 of file timer.cpp.
References timeofday.
Referenced by Start(), and Stop().
Member Data Documentation
double Timer::time0 [private]
Definition at line 51 of file timer.h.
Referenced by Start(), Stop(), and Timer().
double Timer::elapsed [private]
Definition at line 51 of file timer.h.
Referenced by Reset(), Stop(), Time(), and Timer().
bool Timer::running [private]
Definition at line 52 of file timer.h.
Referenced by Reset(), Start(), Stop(), Time(), and Timer().
struct timeval Timer::timeofday [read, private]
Definition at line 74 of file timer.h.
Referenced by GetTime().
The documentation for this class was generated from the following files:
timer.h
timer.cpp