pbrt: SpecularTransmission Class Reference
SpecularTransmission Class Reference
#include <reflection.h>
Public Member Functions
SpecularTransmission (const Spectrum &t, float ei, float et)
Spectrum f (const Vector &, const Vector &) const
Spectrum Sample_f (const Vector &wo, Vector *wi, float u1, float u2, float *pdf) const
float Pdf (const Vector &wo, const Vector &wi) const
Private Attributes
Spectrum T
float etai
float etat
FresnelDielectric fresnel
Detailed Description
Definition at line 221 of file reflection.h.
Constructor & Destructor Documentation
SpecularTransmission::SpecularTransmission (const Spectrum & t, float ei, float et) [inline]
Definition at line 224 of file reflection.h.
Member Function Documentation
Spectrum SpecularTransmission::f (const Vector & , const Vector &) const [inline, virtual]
Implements BxDF.
Definition at line 231 of file reflection.h.
Referenced by Sample_f().
float SpecularTransmission::Pdf (const Vector & wo, const Vector & wi) const [inline, virtual]
Reimplemented from BxDF.
Definition at line 235 of file reflection.h.
Spectrum SpecularTransmission::Sample_f (const Vector & wo, Vector * wi, float u1, float u2, float * pdf) const [virtual]
Reimplemented from BxDF.
Definition at line 104 of file reflection.cpp.
References CosTheta(), etai, etat, FresnelDielectric::Evaluate(), f(), fresnel, SinTheta2(), T, Vector::x, and Vector::y.
Member Data Documentation
float SpecularTransmission::etai [private]
Definition at line 241 of file reflection.h.
Referenced by Sample_f().
float SpecularTransmission::etat [private]
Definition at line 241 of file reflection.h.
Referenced by Sample_f().
FresnelDielectric SpecularTransmission::fresnel [private]
Definition at line 242 of file reflection.h.
Referenced by Sample_f().
Spectrum SpecularTransmission::T [private]
Definition at line 240 of file reflection.h.
Referenced by Sample_f().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp