pbrt: KdTree< NodeData, LookupProc > Class Template Reference
KdTree< NodeData, LookupProc > Class Template Reference
#include <kdtree.h>
Public Member Functions
KdTree (const vector< NodeData > &data)
~KdTree ()
void recursiveBuild (u_int nodeNum, int start, int end, vector< const NodeData * > &buildNodes)
void Lookup (const Point &p, const LookupProc &process, float &maxDistSquared) const
Private Member Functions
void privateLookup (u_int nodeNum, const Point &p, const LookupProc &process, float &maxDistSquared) const
Private Attributes
KdNode * nodes
NodeData * nodeData
u_int nNodes
u_int nextFreeNode
Detailed Description
template<class NodeData, class LookupProc>
class KdTree< NodeData, LookupProc >
Definition at line 48 of file kdtree.h.
Constructor & Destructor Documentation
template<class NodeData, class LookupProc > KdTree< NodeData, LookupProc >::KdTree (const vector< NodeData > & data) [inline]
Definition at line 81 of file kdtree.h.
References AllocAligned().
template<class NodeData, class LookupProc> KdTree< NodeData, LookupProc >::~KdTree () [inline]
Definition at line 52 of file kdtree.h.
Member Function Documentation
template<class NodeData , class LookupProc> void KdTree< NodeData, LookupProc >::Lookup (const Point & p, const LookupProc & process, float & maxDistSquared) const [inline]
Definition at line 127 of file kdtree.h.
References KdTree< NodeData, LookupProc >::privateLookup().
Referenced by ExPhotonIntegrator::estimateE(), ExPhotonIntegrator::Li(), PhotonIntegrator::LPhoton(), and ExPhotonIntegrator::LPhoton().
template<class NodeData , class LookupProc> void KdTree< NodeData, LookupProc >::privateLookup (u_int nodeNum, const Point & p, const LookupProc & process, float & maxDistSquared) const [inline, private]
Definition at line 133 of file kdtree.h.
References DistanceSquared(), KdNode::hasLeftChild, KdTree< NodeData, LookupProc >::nNodes, KdTree< NodeData, LookupProc >::nodeData, KdTree< NodeData, LookupProc >::nodes, KdNode::rightChild, KdNode::splitAxis, and KdNode::splitPos.
Referenced by KdTree< NodeData, LookupProc >::Lookup().
template<class NodeData, class LookupProc > void KdTree< NodeData, LookupProc >::recursiveBuild (u_int nodeNum, int start, int end, vector< const NodeData * > & buildNodes) [inline]
Definition at line 93 of file kdtree.h.
References KdNode::hasLeftChild, KdNode::init(), KdNode::initLeaf(), BBox::MaximumExtent(), KdTree< NodeData, LookupProc >::nextFreeNode, KdTree< NodeData, LookupProc >::nodeData, KdTree< NodeData, LookupProc >::nodes, KdNode::rightChild, and Union().
Member Data Documentation
template<class NodeData, class LookupProc> u_int KdTree< NodeData, LookupProc >::nextFreeNode [private]
Definition at line 67 of file kdtree.h.
Referenced by KdTree< NodeData, LookupProc >::recursiveBuild().
template<class NodeData, class LookupProc> u_int KdTree< NodeData, LookupProc >::nNodes [private]
Definition at line 67 of file kdtree.h.
Referenced by KdTree< NodeData, LookupProc >::privateLookup().
template<class NodeData, class LookupProc> NodeData* KdTree< NodeData, LookupProc >::nodeData [private]
Definition at line 66 of file kdtree.h.
Referenced by KdTree< NodeData, LookupProc >::privateLookup(), KdTree< NodeData, LookupProc >::recursiveBuild(), and KdTree< Photon, PhotonProcess >::~KdTree().
template<class NodeData, class LookupProc> KdNode* KdTree< NodeData, LookupProc >::nodes [private]
Definition at line 65 of file kdtree.h.
Referenced by KdTree< NodeData, LookupProc >::privateLookup(), KdTree< NodeData, LookupProc >::recursiveBuild(), and KdTree< Photon, PhotonProcess >::~KdTree().
The documentation for this class was generated from the following file:
kdtree.h