pbrt: DebugIntegrator Class Reference
DebugIntegrator Class Reference
Public Member Functions
Spectrum Li (const Scene *scene, const RayDifferential &ray, const Sample *sample, float *alpha) const
DebugIntegrator (DebugVariable v[3])
Private Attributes
DebugVariable debug_variable [3]
Detailed Description
Definition at line 46 of file debug.cpp.
Constructor & Destructor Documentation
DebugIntegrator::DebugIntegrator (DebugVariable v[3]) [inline]
Definition at line 51 of file debug.cpp.
References debug_variable.
Member Function Documentation
Spectrum DebugIntegrator::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [virtual]
Implements Integrator.
Definition at line 61 of file debug.cpp.
References DEBUG_GEOM_NORMAL_X, DEBUG_GEOM_NORMAL_Y, DEBUG_GEOM_NORMAL_Z, DEBUG_HIT_SOMETHING, DEBUG_ONE, DEBUG_SHAD_NORMAL_X, DEBUG_SHAD_NORMAL_Y, DEBUG_SHAD_NORMAL_Z, DEBUG_U, DEBUG_V, debug_variable, DEBUG_ZERO, Intersection::dg, BSDF::dgShading, Intersection::GetBSDF(), Scene::Intersect(), DifferentialGeometry::nn, Severe(), DifferentialGeometry::u, DifferentialGeometry::v, Normal::x, Normal::y, and Normal::z.
Member Data Documentation
DebugVariable DebugIntegrator::debug_variable[3] [private]
Definition at line 58 of file debug.cpp.
Referenced by DebugIntegrator(), and Li().
The documentation for this class was generated from the following file:
debug.cpp