pbrt: Mirror Class Reference
Mirror Class Reference
Public Member Functions
Mirror (Reference< Texture< Spectrum > > r, Reference< Texture< float > > bump)
BSDF * GetBSDF (const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading) const
Private Attributes
Reference< Texture< Spectrum > > Kr
Reference< Texture< float > > bumpMap
Detailed Description
Definition at line 28 of file mirror.cpp.
Constructor & Destructor Documentation
Mirror::Mirror (Reference< Texture< Spectrum > > r, Reference< Texture< float > > bump) [inline]
Definition at line 31 of file mirror.cpp.
References bumpMap, and Kr.
Referenced by CreateMaterial().
Member Function Documentation
BSDF * Mirror::GetBSDF (const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading) const [virtual]
Implements Material.
Definition at line 42 of file mirror.cpp.
References BSDF::Add(), Spectrum::Black(), BSDF_ALLOC, Material::Bump(), bumpMap, Kr, and DifferentialGeometry::nn.
Member Data Documentation
Reference<Texture<Spectrum> > Mirror::Kr [private]
Definition at line 38 of file mirror.cpp.
Referenced by CreateMaterial(), GetBSDF(), and Mirror().
Reference<Texture<float> > Mirror::bumpMap [private]
Definition at line 39 of file mirror.cpp.
Referenced by CreateMaterial(), GetBSDF(), and Mirror().
The documentation for this class was generated from the following file:
mirror.cpp