pbrt: SphericalMapping2D Class Reference
SphericalMapping2D Class Reference
#include <texture.h>
Public Member Functions
SphericalMapping2D (const Transform &toSph)
void Map (const DifferentialGeometry &dg, float *s, float *t, float *dsdx, float *dtdx, float *dsdy, float *dtdy) const
Private Member Functions
void sphere (const Point &P, float *s, float *t) const
Private Attributes
Transform WorldToTexture
Detailed Description
Definition at line 51 of file texture.h.
Constructor & Destructor Documentation
SphericalMapping2D::SphericalMapping2D (const Transform & toSph) [inline]
Definition at line 54 of file texture.h.
Member Function Documentation
void SphericalMapping2D::Map (const DifferentialGeometry & dg, float * s, float * t, float * dsdx, float * dtdx, float * dsdy, float * dtdy) const [virtual]
Implements TextureMapping2D.
Definition at line 79 of file texture.cpp.
References DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::p, and sphere().
void SphericalMapping2D::sphere (const Point & P, float * s, float * t) const [private]
Definition at line 97 of file texture.cpp.
References INV_PI, INV_TWOPI, Normalize(), SphericalPhi(), SphericalTheta(), and WorldToTexture.
Referenced by Map().
Member Data Documentation
Transform SphericalMapping2D::WorldToTexture [private]
Definition at line 62 of file texture.h.
Referenced by sphere().
The documentation for this class was generated from the following files:
texture.h
texture.cpp