pbrt: PerspectiveCamera Class Reference
PerspectiveCamera Class Reference
Public Member Functions
PerspectiveCamera (const Transform &world2cam, const float Screen[4], float hither, float yon, float sopen, float sclose, float lensr, float focald, float fov, Film *film)
float GenerateRay (const Sample &sample, Ray *) const
Detailed Description
Definition at line 29 of file perspective.cpp.
Constructor & Destructor Documentation
PerspectiveCamera::PerspectiveCamera (const Transform & world2cam, const float Screen[4], float hither, float yon, float sopen, float sclose, float lensr, float focald, float fov, Film * film)
Definition at line 41 of file perspective.cpp.
Member Function Documentation
float PerspectiveCamera::GenerateRay (const Sample & sample, Ray * ray) const [virtual]
Implements Camera.
Definition at line 51 of file perspective.cpp.
References Camera::CameraToWorld, Camera::ClipHither, Camera::ClipYon, ConcentricSampleDisk(), Ray::d, ProjectiveCamera::FocalDistance, Sample::imageX, Sample::imageY, ProjectiveCamera::LensRadius, Sample::lensU, Sample::lensV, Lerp(), Ray::maxt, Ray::mint, Normalize(), Ray::o, ProjectiveCamera::RasterToCamera, Camera::ShutterClose, Camera::ShutterOpen, Sample::time, Ray::time, Point::x, Point::y, Vector::z, and Point::z.
The documentation for this class was generated from the following file:
perspective.cpp