pbrt: MicrofacetDistribution Class Reference
MicrofacetDistribution Class Reference
#include <reflection.h>
Public Member Functions
virtual ~MicrofacetDistribution ()
virtual float D (const Vector &wh) const =0
virtual void Sample_f (const Vector &wo, Vector *wi, float u1, float u2, float *pdf) const =0
virtual float Pdf (const Vector &wo, const Vector &wi) const =0
Detailed Description
Definition at line 277 of file reflection.h.
Constructor & Destructor Documentation
virtual MicrofacetDistribution::~MicrofacetDistribution () [inline, virtual]
Definition at line 280 of file reflection.h.
Member Function Documentation
virtual float MicrofacetDistribution::D (const Vector & wh) const [pure virtual]
Implemented in Blinn, and Anisotropic.
Referenced by FresnelBlend::f(), and Microfacet::f().
virtual float MicrofacetDistribution::Pdf (const Vector & wo, const Vector & wi) const [pure virtual]
Implemented in Blinn, and Anisotropic.
Referenced by FresnelBlend::Pdf(), and Microfacet::Pdf().
virtual void MicrofacetDistribution::Sample_f (const Vector & wo, Vector * wi, float u1, float u2, float * pdf) const [pure virtual]
Implemented in Blinn, and Anisotropic.
Referenced by FresnelBlend::Sample_f(), and Microfacet::Sample_f().
The documentation for this class was generated from the following file:
reflection.h