pbrt: Anisotropic Class Reference
Anisotropic Class Reference
#include <reflection.h>
Public Member Functions
Anisotropic (float x, float y)
float D (const Vector &wh) const
void Sample_f (const Vector &wo, Vector *wi, float u1, float u2, float *pdf) const
float Pdf (const Vector &wo, const Vector &wi) const
void sampleFirstQuadrant (float u1, float u2, float *phi, float *costheta) const
Private Attributes
float ex
float ey
Detailed Description
Definition at line 326 of file reflection.h.
Constructor & Destructor Documentation
Anisotropic::Anisotropic (float x, float y) [inline]
Definition at line 329 of file reflection.h.
Member Function Documentation
float Anisotropic::D (const Vector & wh) const [inline, virtual]
Implements MicrofacetDistribution.
Definition at line 333 of file reflection.h.
References CosTheta(), INV_TWOPI, Vector::x, and Vector::y.
float Anisotropic::Pdf (const Vector & wo, const Vector & wi) const [virtual]
Implements MicrofacetDistribution.
Definition at line 319 of file reflection.cpp.
References CosTheta(), Dot(), ex, ey, INV_TWOPI, Normalize(), Vector::x, and Vector::y.
void Anisotropic::Sample_f (const Vector & wo, Vector * wi, float u1, float u2, float * pdf) const [virtual]
Implements MicrofacetDistribution.
Definition at line 273 of file reflection.cpp.
References CosTheta(), Dot(), ex, ey, INV_TWOPI, M_PI, SameHemisphere(), sampleFirstQuadrant(), SphericalDirection(), Vector::x, and Vector::y.
void Anisotropic::sampleFirstQuadrant (float u1, float u2, float * phi, float * costheta) const
Definition at line 308 of file reflection.cpp.
References ex, ey, and M_PI.
Referenced by Sample_f().
Member Data Documentation
float Anisotropic::ex [private]
Definition at line 344 of file reflection.h.
Referenced by Pdf(), Sample_f(), and sampleFirstQuadrant().
float Anisotropic::ey [private]
Definition at line 344 of file reflection.h.
Referenced by Pdf(), Sample_f(), and sampleFirstQuadrant().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp