pbrt: HighContrastOp Class Reference
HighContrastOp Class Reference
Public Member Functions
void Map (const float *y, int xRes, int yRes, float maxDisplayY, float *scale) const
Static Private Member Functions
static float C (float y)
static float T (float y, float CYmin, float CYmax, float maxDisplayY)
Detailed Description
Definition at line 28 of file highcontrast.cpp.
Member Function Documentation
static float HighContrastOp::C (float y) [inline, static, private]
Definition at line 35 of file highcontrast.cpp.
Referenced by Map(), and T().
void HighContrastOp::Map (const float * y, int xRes, int yRes, float maxDisplayY, float * scale) const [virtual]
Implements ToneMap.
Definition at line 51 of file highcontrast.cpp.
References C(), ProgressReporter::Done(), Lerp(), MIPMap< T >::Lookup(), T(), TEXTURE_CLAMP, and ProgressReporter::Update().
static float HighContrastOp::T (float y, float CYmin, float CYmax, float maxDisplayY) [inline, static, private]
Definition at line 45 of file highcontrast.cpp.
References C().
Referenced by Map().
The documentation for this class was generated from the following file:
highcontrast.cpp