pbrt: Heightfield Class Reference
Heightfield Class Reference
Public Member Functions
Heightfield (const Transform &o2w, bool ro, int nu, int nv, const float *zs)
~Heightfield ()
bool CanIntersect () const
void Refine (vector< Reference< Shape > > &refined) const
BBox ObjectBound () const
Private Attributes
float * z
int nx
int ny
Detailed Description
Definition at line 29 of file heightfield.cpp.
Constructor & Destructor Documentation
Heightfield::Heightfield (const Transform & o2w, bool ro, int nu, int nv, const float * zs)
Definition at line 43 of file heightfield.cpp.
References memcpy(), nx, ny, and z.
Referenced by CreateShape().
Heightfield::~Heightfield ()
Definition at line 51 of file heightfield.cpp.
References z.
Member Function Documentation
bool Heightfield::CanIntersect () const [virtual]
Reimplemented from Shape.
Definition at line 62 of file heightfield.cpp.
void Heightfield::Refine (vector< Reference< Shape > > & refined) const [virtual]
Reimplemented from Shape.
Definition at line 65 of file heightfield.cpp.
References ParamSet::AddFloat(), ParamSet::AddInt(), ParamSet::AddPoint(), MakeShape(), nx, ny, Shape::ObjectToWorld, Shape::reverseOrientation, VERT, Point::x, Point::y, z, and Point::z.
BBox Heightfield::ObjectBound () const [virtual]
Implements Shape.
Definition at line 54 of file heightfield.cpp.
References nx, ny, and z.
Member Data Documentation
float* Heightfield::z [private]
Definition at line 39 of file heightfield.cpp.
Referenced by Heightfield(), ObjectBound(), Refine(), and ~Heightfield().
int Heightfield::nx [private]
Definition at line 40 of file heightfield.cpp.
Referenced by Heightfield(), ObjectBound(), and Refine().
int Heightfield::ny [private]
Definition at line 40 of file heightfield.cpp.
Referenced by Heightfield(), ObjectBound(), and Refine().
The documentation for this class was generated from the following file:
heightfield.cpp