pbrt: ExPhotonIntegrator Class Reference
ExPhotonIntegrator Class Reference
Public Member Functions
ExPhotonIntegrator (int ncaus, int nindir, int nLookup, int mdepth, float maxdist, bool finalGather, int gatherSamples, float rrt, float ga)
~ExPhotonIntegrator ()
Spectrum Li (const Scene *scene, const RayDifferential &ray, const Sample *sample, float *alpha) const
void RequestSamples (Sample *sample, const Scene *scene)
void Preprocess (const Scene *)
Private Member Functions
Spectrum estimateE (KdTree< Photon, PhotonProcess > *map, int count, const Point &p, const Normal &n) const
Static Private Member Functions
static bool unsuccessful (int needed, int found, int shot)
static Spectrum LPhoton (KdTree< Photon, PhotonProcess > *map, int nPaths, int nLookup, BSDF *bsdf, const Intersection &isect, const Vector &w, float maxDistSquared)
Private Attributes
int gatherSampleOffset [2]
int gatherComponentOffset [2]
u_int nCausticPhotons
u_int nIndirectPhotons
u_int nLookup
int specularDepth
int maxSpecularDepth
float maxDistSquared
float rrTreshold
bool finalGather
float cosGatherAngle
int gatherSamples
int * lightSampleOffset
int lightNumOffset
int * bsdfSampleOffset
int * bsdfComponentOffset
int nCausticPaths
int nIndirectPaths
KdTree< Photon, PhotonProcess > * causticMap
KdTree< Photon, PhotonProcess > * indirectMap
KdTree< RadiancePhoton,
RadiancePhotonProcess > * radianceMap
Detailed Description
Definition at line 107 of file exphotonmap.cpp.
Constructor & Destructor Documentation
ExPhotonIntegrator::ExPhotonIntegrator (int ncaus, int nindir, int nLookup, int mdepth, float maxdist, bool finalGather, int gatherSamples, float rrt, float ga)
Definition at line 250 of file exphotonmap.cpp.
References causticMap, cosGatherAngle, finalGather, gatherSamples, indirectMap, maxDistSquared, maxSpecularDepth, nCausticPhotons, nIndirectPhotons, nLookup, radianceMap, Radians(), rrTreshold, and specularDepth.
Referenced by CreateSurfaceIntegrator().
ExPhotonIntegrator::~ExPhotonIntegrator ()
Definition at line 266 of file exphotonmap.cpp.
References causticMap, indirectMap, and radianceMap.
Member Function Documentation
Spectrum ExPhotonIntegrator::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [virtual]
Implements Integrator.
Definition at line 494 of file exphotonmap.cpp.
References AbsDot(), Spectrum::Black(), BSDF_ALL, BSDF_DIFFUSE, BSDF_GLOSSY, BSDF_REFLECTION, BSDF_SPECULAR, BSDF_TRANSMISSION, bsdfComponentOffset, bsdfSampleOffset, causticMap, CoordinateSystem(), cosGatherAngle, Ray::d, Intersection::dg, BSDF::dgShading, DifferentialGeometry::dndu, DifferentialGeometry::dndv, Dot(), DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, BSDF::eta, BSDF::f(), finalGather, Floor2Int(), PhotonProcess::foundPhotons, gatherComponentOffset, gatherSampleOffset, gatherSamples, Intersection::GetBSDF(), RayDifferential::hasDifferentials, indirectMap, INFINITY, Scene::Intersect(), Intersection::Le(), Scene::Li(), Scene::lights, lightSampleOffset, RadiancePhoton::Lo, KdTree< NodeData, LookupProc >::Lookup(), LPhoton(), maxDistSquared, maxSpecularDepth, nCausticPaths, nIndirectPaths, nLookup, DifferentialGeometry::nn, BSDF::NumComponents(), Ray::o, Sample::oneD, DifferentialGeometry::p, BSDF::Pdf(), RadiancePhotonProcess::photon, ClosePhoton::photon, PhotonProcess::photons, PowerHeuristic(), radianceMap, RayDifferential::rx, RayDifferential::ry, BSDF::Sample_f(), specularDepth, Scene::Transmittance(), Sample::twoD, UniformConePdf(), UniformSampleAllLights(), UniformSampleCone(), and Photon::wi.
void ExPhotonIntegrator::RequestSamples (Sample * sample, const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 271 of file exphotonmap.cpp.
References Sample::Add1D(), Sample::Add2D(), bsdfComponentOffset, bsdfSampleOffset, finalGather, gatherComponentOffset, gatherSampleOffset, gatherSamples, lightNumOffset, Scene::lights, lightSampleOffset, Light::nSamples, Sampler::RoundSize(), and Scene::sampler.
void ExPhotonIntegrator::Preprocess (const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 298 of file exphotonmap.cpp.
References AbsDot(), Spectrum::Black(), BSDF_ALL, BSDF_ALL_REFLECTION, BSDF_ALL_TRANSMISSION, BSDF_REFLECTION, BSDF_SPECULAR, BSDF_TRANSMISSION, causticMap, ComputeStep1dCDF(), Ray::d, Intersection::dg, BSDF::dgShading, ProgressReporter::Done(), Dot(), Error(), estimateE(), finalGather, Floor2Int(), BSDF::FreeAll(), Intersection::GetBSDF(), indirectMap, Scene::Intersect(), INV_PI, Scene::lights, RadiancePhoton::Lo, RadiancePhoton::n, nCausticPaths, nCausticPhotons, nIndirectPaths, nIndirectPhotons, DifferentialGeometry::nn, BSDF::NumComponents(), RadiancePhoton::p, DifferentialGeometry::p, radianceMap, RadicalInverse(), RandomFloat(), BSDF::rho(), BSDF::Sample_f(), Light::Sample_L(), SampleStep1d(), Scene::Transmittance(), unsuccessful(), ProgressReporter::Update(), and Spectrum::y().
static bool ExPhotonIntegrator::unsuccessful (int needed, int found, int shot) [inline, static, private]
Definition at line 119 of file exphotonmap.cpp.
Referenced by Preprocess().
Spectrum ExPhotonIntegrator::LPhoton (KdTree< Photon, PhotonProcess > * map, int nPaths, int nLookup, BSDF * bsdf, const Intersection & isect, const Vector & w, float maxDistSquared) [static, private]
Definition at line 190 of file exphotonmap.cpp.
References StatsRatio::Add(), Photon::alpha, BSDF_ALL_REFLECTION, BSDF_ALL_TRANSMISSION, BSDF_DIFFUSE, BSDF_GLOSSY, BSDF_REFLECTION, BSDF_TRANSMISSION, Intersection::dg, BSDF::dgShading, Dot(), BSDF::f(), PhotonProcess::foundPhotons, INV_PI, kernel(), KdTree< NodeData, LookupProc >::Lookup(), DifferentialGeometry::nn, BSDF::NumComponents(), DifferentialGeometry::p, ClosePhoton::photon, PhotonProcess::photons, BSDF::rho(), and Photon::wi.
Referenced by Li().
Spectrum ExPhotonIntegrator::estimateE (KdTree< Photon, PhotonProcess > * map, int count, const Point & p, const Normal & n) const [private]
Definition at line 150 of file exphotonmap.cpp.
References Photon::alpha, Dot(), PhotonProcess::foundPhotons, KdTree< NodeData, LookupProc >::Lookup(), M_PI, maxDistSquared, nLookup, ClosePhoton::photon, and PhotonProcess::photons.
Referenced by Preprocess().
Member Data Documentation
int ExPhotonIntegrator::gatherSampleOffset[2] [private]
Definition at line 131 of file exphotonmap.cpp.
Referenced by Li(), and RequestSamples().
int ExPhotonIntegrator::gatherComponentOffset[2] [private]
Definition at line 131 of file exphotonmap.cpp.
Referenced by Li(), and RequestSamples().
u_int ExPhotonIntegrator::nCausticPhotons [private]
Definition at line 132 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), and Preprocess().
u_int ExPhotonIntegrator::nIndirectPhotons [private]
Definition at line 132 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), and Preprocess().
u_int ExPhotonIntegrator::nLookup [private]
Definition at line 133 of file exphotonmap.cpp.
Referenced by estimateE(), ExPhotonIntegrator(), and Li().
int ExPhotonIntegrator::specularDepth [mutable, private]
Definition at line 134 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), and Li().
int ExPhotonIntegrator::maxSpecularDepth [private]
Definition at line 135 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), and Li().
float ExPhotonIntegrator::maxDistSquared [private]
Definition at line 136 of file exphotonmap.cpp.
Referenced by estimateE(), ExPhotonIntegrator(), and Li().
float ExPhotonIntegrator::rrTreshold [private]
Definition at line 136 of file exphotonmap.cpp.
Referenced by CreateSurfaceIntegrator(), and ExPhotonIntegrator().
bool ExPhotonIntegrator::finalGather [private]
Definition at line 137 of file exphotonmap.cpp.
Referenced by CreateSurfaceIntegrator(), ExPhotonIntegrator(), Li(), Preprocess(), and RequestSamples().
float ExPhotonIntegrator::cosGatherAngle [private]
Definition at line 138 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), and Li().
int ExPhotonIntegrator::gatherSamples [private]
Definition at line 139 of file exphotonmap.cpp.
Referenced by CreateSurfaceIntegrator(), ExPhotonIntegrator(), Li(), and RequestSamples().
int* ExPhotonIntegrator::lightSampleOffset [private]
Definition at line 141 of file exphotonmap.cpp.
Referenced by Li(), and RequestSamples().
int ExPhotonIntegrator::lightNumOffset [private]
Definition at line 141 of file exphotonmap.cpp.
Referenced by RequestSamples().
int* ExPhotonIntegrator::bsdfSampleOffset [private]
Definition at line 142 of file exphotonmap.cpp.
Referenced by Li(), and RequestSamples().
int * ExPhotonIntegrator::bsdfComponentOffset [private]
Definition at line 142 of file exphotonmap.cpp.
Referenced by Li(), and RequestSamples().
int ExPhotonIntegrator::nCausticPaths [private]
Definition at line 143 of file exphotonmap.cpp.
Referenced by Li(), and Preprocess().
int ExPhotonIntegrator::nIndirectPaths [private]
Definition at line 143 of file exphotonmap.cpp.
Referenced by Li(), and Preprocess().
KdTree<Photon, PhotonProcess>* ExPhotonIntegrator::causticMap [mutable, private]
Definition at line 144 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), Li(), Preprocess(), and ~ExPhotonIntegrator().
KdTree<Photon, PhotonProcess>* ExPhotonIntegrator::indirectMap [mutable, private]
Definition at line 145 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), Li(), Preprocess(), and ~ExPhotonIntegrator().
KdTree<RadiancePhoton, RadiancePhotonProcess>* ExPhotonIntegrator::radianceMap [mutable, private]
Definition at line 146 of file exphotonmap.cpp.
Referenced by ExPhotonIntegrator(), Li(), Preprocess(), and ~ExPhotonIntegrator().
The documentation for this class was generated from the following file:
exphotonmap.cpp