pbrt: Clay Class Reference
Clay Class Reference
Public Member Functions
Clay (Reference< Texture< float > > bump)
BSDF * GetBSDF (const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading) const
Private Attributes
Reference< Texture< float > > bumpMap
Detailed Description
Definition at line 28 of file clay.cpp.
Constructor & Destructor Documentation
Clay::Clay (Reference< Texture< float > > bump) [inline]
Definition at line 30 of file clay.cpp.
Referenced by CreateMaterial().
Member Function Documentation
BSDF * Clay::GetBSDF (const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading) const [virtual]
Implements Material.
Definition at line 37 of file clay.cpp.
References BSDF::Add(), BSDF_ALLOC, BSDF_DIFFUSE, BSDF_REFLECTION, Material::Bump(), bumpMap, BSDF::f(), and DifferentialGeometry::nn.
Member Data Documentation
Reference<Texture<float> > Clay::bumpMap [private]
Definition at line 33 of file clay.cpp.
Referenced by CreateMaterial(), and GetBSDF().
The documentation for this class was generated from the following file:
clay.cpp