pbrt: OrenNayar Class Reference
OrenNayar Class Reference
#include <reflection.h>
Public Member Functions
Spectrum f (const Vector &wo, const Vector &wi) const
OrenNayar (const Spectrum &reflectance, float sig)
Private Attributes
Spectrum R
float A
float B
Detailed Description
Definition at line 260 of file reflection.h.
Constructor & Destructor Documentation
OrenNayar::OrenNayar (const Spectrum & reflectance, float sig) [inline]
Definition at line 264 of file reflection.h.
References Radians().
Member Function Documentation
Spectrum OrenNayar::f (const Vector & wo, const Vector & wi) const [virtual]
Implements BxDF.
Definition at line 132 of file reflection.cpp.
References A, B, CosPhi(), CosTheta(), INV_PI, R, SinPhi(), and SinTheta().
Member Data Documentation
float OrenNayar::A [private]
Definition at line 275 of file reflection.h.
Referenced by f().
float OrenNayar::B [private]
Definition at line 275 of file reflection.h.
Referenced by f().
Spectrum OrenNayar::R [private]
Definition at line 274 of file reflection.h.
Referenced by f().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp