pbrt: Checkerboard3D< T > Class Template Reference
Checkerboard3D< T > Class Template Reference
Public Member Functions
Checkerboard3D (TextureMapping3D *m, Reference< Texture< T > > c1, Reference< Texture< T > > c2)
T Evaluate (const DifferentialGeometry &dg) const
Private Attributes
Reference< Texture< T > > tex1
Reference< Texture< T > > tex2
TextureMapping3D * mapping
Detailed Description
template<class T>
class Checkerboard3D< T >
Definition at line 130 of file checkerboard.cpp.
Constructor & Destructor Documentation
template<class T> Checkerboard3D< T >::Checkerboard3D (TextureMapping3D * m, Reference< Texture< T > > c1, Reference< Texture< T > > c2) [inline]
Definition at line 133 of file checkerboard.cpp.
References Checkerboard3D< T >::mapping, Checkerboard3D< T >::tex1, and Checkerboard3D< T >::tex2.
Member Function Documentation
template<class T> T Checkerboard3D< T >::Evaluate (const DifferentialGeometry & dg) const [inline, virtual]
Implements Texture< T >.
Definition at line 140 of file checkerboard.cpp.
References DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, Floor2Int(), TextureMapping3D::Map(), Checkerboard3D< T >::mapping, N_SAMPLES, DifferentialGeometry::p, StratifiedSample2D(), Checkerboard3D< T >::tex1, Checkerboard3D< T >::tex2, DifferentialGeometry::u, DifferentialGeometry::v, Point::x, Point::y, and Point::z.
Member Data Documentation
template<class T> TextureMapping3D* Checkerboard3D< T >::mapping [private]
Definition at line 174 of file checkerboard.cpp.
Referenced by Checkerboard3D< T >::Checkerboard3D(), and Checkerboard3D< T >::Evaluate().
template<class T> Reference<Texture<T> > Checkerboard3D< T >::tex1 [private]
Definition at line 173 of file checkerboard.cpp.
Referenced by Checkerboard3D< T >::Checkerboard3D(), and Checkerboard3D< T >::Evaluate().
template<class T> Reference<Texture<T> > Checkerboard3D< T >::tex2 [private]
Definition at line 173 of file checkerboard.cpp.
Referenced by Checkerboard3D< T >::Checkerboard3D(), and Checkerboard3D< T >::Evaluate().
The documentation for this class was generated from the following file:
checkerboard.cpp