pbrt: Cone Class Reference
Cone Class Reference
Public Member Functions
Cone (const Transform &o2w, bool ro, float height, float rad, float tm)
BBox ObjectBound () const
bool Intersect (const Ray &ray, float *tHit, DifferentialGeometry *dg) const
bool IntersectP (const Ray &ray) const
float Area () const
Protected Attributes
float radius
float height
float phiMax
Detailed Description
Definition at line 27 of file cone.cpp.
Constructor & Destructor Documentation
Cone::Cone (const Transform & o2w, bool ro, float height, float rad, float tm)
Definition at line 42 of file cone.cpp.
References Clamp(), height, phiMax, Radians(), and radius.
Member Function Documentation
float Cone::Area () const [virtual]
Reimplemented from Shape.
Definition at line 182 of file cone.cpp.
References height, phiMax, and radius.
bool Cone::Intersect (const Ray & ray, float * tHit, DifferentialGeometry * dg) const [virtual]
Reimplemented from Shape.
Definition at line 54 of file cone.cpp.
References Cross(), Ray::d, Dot(), height, M_PI, Ray::maxt, Ray::mint, N, Normalize(), Ray::o, Shape::ObjectToWorld, phiMax, Quadratic(), radius, Shape::WorldToObject, Point::x, Vector::x, Point::y, Vector::y, Point::z, and Vector::z.
bool Cone::IntersectP (const Ray & ray) const [virtual]
Reimplemented from Shape.
Definition at line 137 of file cone.cpp.
References Ray::d, height, M_PI, Ray::maxt, Ray::mint, Ray::o, phiMax, Quadratic(), radius, Shape::WorldToObject, Point::x, Vector::x, Point::y, Vector::y, Point::z, and Vector::z.
BBox Cone::ObjectBound () const [virtual]
Implements Shape.
Definition at line 49 of file cone.cpp.
References height, and radius.
Member Data Documentation
float Cone::height [protected]
Definition at line 39 of file cone.cpp.
Referenced by Area(), Cone(), Intersect(), IntersectP(), and ObjectBound().
float Cone::phiMax [protected]
Definition at line 39 of file cone.cpp.
Referenced by Area(), Cone(), Intersect(), and IntersectP().
float Cone::radius [protected]
Definition at line 39 of file cone.cpp.
Referenced by Area(), Cone(), Intersect(), IntersectP(), and ObjectBound().
The documentation for this class was generated from the following file:
cone.cpp