pbrt: Microfacet Class Reference
Microfacet Class Reference
#include <reflection.h>
Public Member Functions
Microfacet (const Spectrum &reflectance, Fresnel *f, MicrofacetDistribution *d)
Spectrum f (const Vector &wo, const Vector &wi) const
float G (const Vector &wo, const Vector &wi, const Vector &wh) const
Spectrum Sample_f (const Vector &wo, Vector *wi, float u1, float u2, float *pdf) const
float Pdf (const Vector &wo, const Vector &wi) const
Private Attributes
Spectrum R
MicrofacetDistribution * distribution
Fresnel * fresnel
Detailed Description
Definition at line 287 of file reflection.h.
Constructor & Destructor Documentation
Microfacet::Microfacet (const Spectrum & reflectance, Fresnel * f, MicrofacetDistribution * d)
Definition at line 157 of file reflection.cpp.
Member Function Documentation
Spectrum Microfacet::f (const Vector & wo, const Vector & wi) const [virtual]
Implements BxDF.
Definition at line 163 of file reflection.cpp.
References CosTheta(), MicrofacetDistribution::D(), distribution, Dot(), Fresnel::Evaluate(), fresnel, G(), Normalize(), R, Vector::x, Vector::y, and Vector::z.
Referenced by Sample_f().
float Microfacet::G (const Vector & wo, const Vector & wi, const Vector & wh) const [inline]
Definition at line 293 of file reflection.h.
References AbsDot(), and CosTheta().
Referenced by f().
float Microfacet::Pdf (const Vector & wo, const Vector & wi) const [virtual]
Reimplemented from BxDF.
Definition at line 241 of file reflection.cpp.
References distribution, MicrofacetDistribution::Pdf(), and SameHemisphere().
Spectrum Microfacet::Sample_f (const Vector & wo, Vector * wi, float u1, float u2, float * pdf) const [virtual]
Reimplemented from BxDF.
Definition at line 235 of file reflection.cpp.
References distribution, f(), SameHemisphere(), and MicrofacetDistribution::Sample_f().
Member Data Documentation
MicrofacetDistribution* Microfacet::distribution [private]
Definition at line 308 of file reflection.h.
Referenced by f(), Pdf(), and Sample_f().
Fresnel* Microfacet::fresnel [private]
Definition at line 309 of file reflection.h.
Referenced by f().
Spectrum Microfacet::R [private]
Definition at line 307 of file reflection.h.
Referenced by f().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp