pbrt: Triangle Class Reference
Triangle Class Reference
Public Member Functions
Triangle (const Transform &o2w, bool ro, TriangleMesh *m, int n)
BBox ObjectBound () const
BBox WorldBound () const
bool Intersect (const Ray &ray, float *tHit, DifferentialGeometry *dg) const
bool IntersectP (const Ray &ray) const
void GetUVs (float uv[3][2]) const
float Area () const
virtual void GetShadingGeometry (const Transform &obj2world, const DifferentialGeometry &dg, DifferentialGeometry *dgShading) const
Point Sample (float u1, float u2, Normal *Ns) const
Private Attributes
Reference< TriangleMesh > mesh
int * v
Detailed Description
Definition at line 51 of file trianglemesh.cpp.
Constructor & Destructor Documentation
Triangle::Triangle (const Transform & o2w, bool ro, TriangleMesh * m, int n) [inline]
Definition at line 54 of file trianglemesh.cpp.
References mesh, and v.
Member Function Documentation
float Triangle::Area () const [virtual]
Reimplemented from Shape.
Definition at line 329 of file trianglemesh.cpp.
References Cross(), Vector::Length(), mesh, and v.
virtual void Triangle::GetShadingGeometry (const Transform & obj2world, const DifferentialGeometry & dg, DifferentialGeometry * dgShading) const [inline, virtual]
Reimplemented from Shape.
Definition at line 71 of file trianglemesh.cpp.
References Cross(), DifferentialGeometry::dpdu, DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, GetUVs(), mesh, DifferentialGeometry::nn, Normalize(), Shape::ObjectToWorld, DifferentialGeometry::p, DifferentialGeometry::shape, SolveLinearSystem2x2(), DifferentialGeometry::u, v, and DifferentialGeometry::v.
void Triangle::GetUVs (float uv[3][2]) const
Definition at line 315 of file trianglemesh.cpp.
References mesh, and v.
Referenced by GetShadingGeometry(), and Intersect().
bool Triangle::Intersect (const Ray & ray, float * tHit, DifferentialGeometry * dg) const [virtual]
Reimplemented from Shape.
Definition at line 213 of file trianglemesh.cpp.
References StatsPercentage::Add(), CoordinateSystem(), Cross(), Ray::d, Dot(), GetUVs(), Ray::maxt, mesh, Normalize(), Ray::o, and v.
bool Triangle::IntersectP (const Ray & ray) const [virtual]
Reimplemented from Shape.
Definition at line 279 of file trianglemesh.cpp.
References StatsPercentage::Add(), Cross(), Ray::d, Dot(), Ray::maxt, mesh, Ray::o, and v.
BBox Triangle::ObjectBound () const [virtual]
Implements Shape.
Definition at line 198 of file trianglemesh.cpp.
References mesh, Union(), v, and Shape::WorldToObject.
Point Triangle::Sample (float u1, float u2, Normal * Ns) const [virtual]
Reimplemented from Shape.
Definition at line 336 of file trianglemesh.cpp.
References Cross(), mesh, Normalize(), Shape::reverseOrientation, UniformSampleTriangle(), and v.
BBox Triangle::WorldBound () const [virtual]
Reimplemented from Shape.
Definition at line 206 of file trianglemesh.cpp.
References mesh, Union(), and v.
Member Data Documentation
Reference<TriangleMesh> Triangle::mesh [private]
Definition at line 137 of file trianglemesh.cpp.
Referenced by Area(), GetShadingGeometry(), GetUVs(), Intersect(), IntersectP(), ObjectBound(), Sample(), Triangle(), and WorldBound().
int* Triangle::v [private]
Definition at line 138 of file trianglemesh.cpp.
Referenced by Area(), GetShadingGeometry(), GetUVs(), Intersect(), IntersectP(), ObjectBound(), Sample(), Triangle(), and WorldBound().
The documentation for this class was generated from the following file:
trianglemesh.cpp