pbrt: FresnelBlend Class Reference
FresnelBlend Class Reference
#include <reflection.h>
Public Member Functions
FresnelBlend (const Spectrum &Rd, const Spectrum &Rs, MicrofacetDistribution *dist)
Spectrum f (const Vector &wo, const Vector &wi) const
Spectrum SchlickFresnel (float costheta) const
Spectrum Sample_f (const Vector &wi, Vector *sampled_f, float u1, float u2, float *pdf) const
float Pdf (const Vector &wi, const Vector &wo) const
Private Attributes
Spectrum Rd
Spectrum Rs
MicrofacetDistribution * distribution
Detailed Description
Definition at line 359 of file reflection.h.
Constructor & Destructor Documentation
FresnelBlend::FresnelBlend (const Spectrum & Rd, const Spectrum & Rs, MicrofacetDistribution * dist)
Definition at line 199 of file reflection.cpp.
References distribution.
Member Function Documentation
Spectrum FresnelBlend::f (const Vector & wo, const Vector & wi) const [virtual]
Implements BxDF.
Definition at line 206 of file reflection.cpp.
References AbsDot(), CosTheta(), MicrofacetDistribution::D(), distribution, Dot(), M_PI, Normalize(), Rd, Rs, and SchlickFresnel().
Referenced by Sample_f().
float FresnelBlend::Pdf (const Vector & wi, const Vector & wo) const [virtual]
Reimplemented from BxDF.
Definition at line 349 of file reflection.cpp.
References distribution, INV_PI, MicrofacetDistribution::Pdf(), SameHemisphere(), and Vector::z.
Referenced by Sample_f().
Spectrum FresnelBlend::Sample_f (const Vector & wi, Vector * sampled_f, float u1, float u2, float * pdf) const [virtual]
Reimplemented from BxDF.
Definition at line 333 of file reflection.cpp.
References CosineSampleHemisphere(), distribution, f(), Pdf(), SameHemisphere(), MicrofacetDistribution::Sample_f(), and Vector::z.
Spectrum FresnelBlend::SchlickFresnel (float costheta) const [inline]
Definition at line 366 of file reflection.h.
Referenced by f().
Member Data Documentation
MicrofacetDistribution* FresnelBlend::distribution [private]
Definition at line 375 of file reflection.h.
Referenced by f(), FresnelBlend(), Pdf(), and Sample_f().
Spectrum FresnelBlend::Rd [private]
Definition at line 374 of file reflection.h.
Referenced by f().
Spectrum FresnelBlend::Rs [private]
Definition at line 374 of file reflection.h.
Referenced by f().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp