pbrt: StatsRatio Class Reference
StatsRatio Class Reference
#include <pbrt.h>
Public Member Functions
StatsRatio (const string &category, const string &name)
void Add (int a, int b)
StatsRatio (const string &category, const string &name)
void Add (int a, int b)
Private Attributes
StatsCounterType na
StatsCounterType nb
Detailed Description
Definition at line 301 of file pbrt.h.
Constructor & Destructor Documentation
StatsRatio::StatsRatio (const string & category, const string & name)
Definition at line 220 of file util.cpp.
References addTracker(), na, and nb.
StatsRatio::StatsRatio (const string & category, const string & name)
Member Function Documentation
void StatsRatio::Add (int a, int b) [inline]
Definition at line 305 of file pbrt.h.
Referenced by MIPMap< T >::EWA(), GridAccel::GridAccel(), KdAccelNode::initLeaf(), IrradianceCache::InterpolateIrradiance(), Voxel::Intersect(), GridAccel::Intersect(), Voxel::IntersectP(), GridAccel::IntersectP(), PhotonIntegrator::LPhoton(), and ExPhotonIntegrator::LPhoton().
void StatsRatio::Add (int a, int b) [inline]
Definition at line 306 of file pbrtlex.l.
Member Data Documentation
StatsCounterType StatsRatio::na [private]
Definition at line 308 of file pbrt.h.
Referenced by StatsRatio().
StatsCounterType StatsRatio::nb [private]
Definition at line 308 of file pbrt.h.
Referenced by StatsRatio().
The documentation for this class was generated from the following files:
pbrt.h
util.cpp