pbrt: BrushedMetal Class Reference
BrushedMetal Class Reference
Public Member Functions
BrushedMetal (Reference< Texture< float > > bump)
BSDF * GetBSDF (const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading) const
Public Attributes
Reference< Texture< float > > bumpMap
Detailed Description
Definition at line 28 of file brushedmetal.cpp.
Constructor & Destructor Documentation
BrushedMetal::BrushedMetal (Reference< Texture< float > > bump) [inline]
Definition at line 30 of file brushedmetal.cpp.
Referenced by CreateMaterial().
Member Function Documentation
BSDF * BrushedMetal::GetBSDF (const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading) const [virtual]
Implements Material.
Definition at line 35 of file brushedmetal.cpp.
References BSDF::Add(), BSDF_ALLOC, BSDF_GLOSSY, BSDF_REFLECTION, Material::Bump(), bumpMap, BSDF::f(), and DifferentialGeometry::nn.
Member Data Documentation
Reference<Texture<float> > BrushedMetal::bumpMap
Definition at line 32 of file brushedmetal.cpp.
Referenced by CreateMaterial(), and GetBSDF().
The documentation for this class was generated from the following file:
brushedmetal.cpp