pbrt: Plugin Class Reference
Plugin Class Reference
Public Member Functions
Plugin (const string &fname)
~Plugin ()
void * GetSymbol (const string &symname)
Private Attributes
void * hinstLib
string pluginName
Detailed Description
Definition at line 95 of file dynload.cpp.
Constructor & Destructor Documentation
Plugin::Plugin (const string & fname)
Definition at line 462 of file dynload.cpp.
References Error(), hinstLib, and pluginName.
Plugin::~Plugin ()
Definition at line 491 of file dynload.cpp.
References hinstLib.
Member Function Documentation
void * Plugin::GetSymbol (const string & symname)
Definition at line 500 of file dynload.cpp.
References hinstLib, pluginName, and Severe().
Referenced by AcceleratorPlugin::AcceleratorPlugin(), AreaLightPlugin::AreaLightPlugin(), CameraPlugin::CameraPlugin(), FilmPlugin::FilmPlugin(), FilterPlugin::FilterPlugin(), LightPlugin::LightPlugin(), MaterialPlugin::MaterialPlugin(), SamplerPlugin::SamplerPlugin(), ShapePlugin::ShapePlugin(), SurfaceIntegratorPlugin::SurfaceIntegratorPlugin(), TexturePlugin::TexturePlugin(), ToneMapPlugin::ToneMapPlugin(), VolumeIntegratorPlugin::VolumeIntegratorPlugin(), and VolumeRegionPlugin::VolumeRegionPlugin().
Member Data Documentation
void* Plugin::hinstLib [private]
Definition at line 108 of file dynload.cpp.
Referenced by GetSymbol(), Plugin(), and ~Plugin().
string Plugin::pluginName [private]
Definition at line 110 of file dynload.cpp.
Referenced by GetSymbol(), and Plugin().
The documentation for this class was generated from the following file:
dynload.cpp