pbrt: OrthoCamera Class Reference
OrthoCamera Class Reference
Public Member Functions
OrthoCamera (const Transform &world2cam, const float Screen[4], float hither, float yon, float sopen, float sclose, float lensr, float focald, Film *film)
float GenerateRay (const Sample &sample, Ray *) const
Detailed Description
Definition at line 29 of file orthographic.cpp.
Constructor & Destructor Documentation
OrthoCamera::OrthoCamera (const Transform & world2cam, const float Screen[4], float hither, float yon, float sopen, float sclose, float lensr, float focald, Film * film)
Definition at line 40 of file orthographic.cpp.
Referenced by CreateCamera().
Member Function Documentation
float OrthoCamera::GenerateRay (const Sample & sample, Ray * ray) const [virtual]
Implements Camera.
Definition at line 48 of file orthographic.cpp.
References Camera::CameraToWorld, Camera::ClipHither, Camera::ClipYon, ConcentricSampleDisk(), Ray::d, ProjectiveCamera::FocalDistance, Sample::imageX, Sample::imageY, ProjectiveCamera::LensRadius, Sample::lensU, Sample::lensV, Lerp(), Ray::maxt, Ray::mint, Normalize(), Ray::o, ProjectiveCamera::RasterToCamera, Camera::ShutterClose, Camera::ShutterOpen, Sample::time, Ray::time, Point::x, Point::y, and Vector::z.
The documentation for this class was generated from the following file:
orthographic.cpp