pbrt: DistantLight Class Reference
DistantLight Class Reference
Public Member Functions
DistantLight (const Transform &light2world, const Spectrum &radiance, const Vector &dir)
bool IsDeltaLight () const
Spectrum Sample_L (const Point &p, Vector *wi, VisibilityTester *) const
Spectrum Power (const Scene *scene) const
Spectrum Sample_L (const Point &P, float u1, float u2, Vector *wo, float *pdf, VisibilityTester *visibility) const
Spectrum Sample_L (const Scene *scene, float u1, float u2, float u3, float u4, Ray *ray, float *pdf) const
float Pdf (const Point &, const Vector &) const
Private Attributes
Vector lightDir
Spectrum L
Detailed Description
Definition at line 30 of file distant.cpp.
Constructor & Destructor Documentation
DistantLight::DistantLight (const Transform & light2world, const Spectrum & radiance, const Vector & dir)
Definition at line 54 of file distant.cpp.
References L, lightDir, Light::LightToWorld, and Normalize().
Member Function Documentation
bool DistantLight::IsDeltaLight () const [inline, virtual]
Implements Light.
Definition at line 34 of file distant.cpp.
float DistantLight::Pdf (const Point & , const Vector &) const [virtual]
Implements Light.
Definition at line 71 of file distant.cpp.
Spectrum DistantLight::Power (const Scene * scene) const [inline, virtual]
Implements Light.
Definition at line 36 of file distant.cpp.
References BBox::BoundingSphere(), L, M_PI, and Scene::WorldBound().
Spectrum DistantLight::Sample_L (const Scene * scene, float u1, float u2, float u3, float u4, Ray * ray, float * pdf) const [virtual]
Implements Light.
Definition at line 74 of file distant.cpp.
References BBox::BoundingSphere(), ConcentricSampleDisk(), CoordinateSystem(), Ray::d, L, lightDir, M_PI, Ray::o, and Scene::WorldBound().
Spectrum DistantLight::Sample_L (const Point & P, float u1, float u2, Vector * wo, float * pdf, VisibilityTester * visibility) const [virtual]
Implements Light.
Definition at line 66 of file distant.cpp.
References Sample_L().
Spectrum DistantLight::Sample_L (const Point & p, Vector * wi, VisibilityTester * visibility) const [virtual]
Implements Light.
Definition at line 60 of file distant.cpp.
References L, lightDir, and VisibilityTester::SetRay().
Referenced by Sample_L().
Member Data Documentation
Spectrum DistantLight::L [private]
Definition at line 51 of file distant.cpp.
Referenced by DistantLight(), Power(), and Sample_L().
Vector DistantLight::lightDir [private]
Definition at line 50 of file distant.cpp.
Referenced by DistantLight(), and Sample_L().
The documentation for this class was generated from the following file:
distant.cpp