pbrt: MemoryArena Class Reference
MemoryArena Class Reference
#include <pbrt.h>
Public Member Functions
MemoryArena (u_int bs=32768)
~MemoryArena ()
void * Alloc (u_int sz)
void FreeAll ()
MemoryArena (u_int bs=32768)
~MemoryArena ()
void * Alloc (u_int sz)
void FreeAll ()
Private Attributes
u_int curBlockPos
u_int blockSize
char * currentBlock
vector< char * > usedBlocks
vector< char * > availableBlocks
Detailed Description
Definition at line 396 of file pbrt.h.
Constructor & Destructor Documentation
MemoryArena::MemoryArena (u_int bs = 32768) [inline]
Definition at line 399 of file pbrt.h.
References AllocAligned().
MemoryArena::~MemoryArena () [inline]
Definition at line 404 of file pbrt.h.
References FreeAligned().
MemoryArena::MemoryArena (u_int bs = 32768) [inline]
Definition at line 400 of file pbrtlex.l.
MemoryArena::~MemoryArena () [inline]
Definition at line 405 of file pbrtlex.l.
Member Function Documentation
void* MemoryArena::Alloc (u_int sz) [inline]
Definition at line 411 of file pbrt.h.
References AllocAligned().
Referenced by KdAccelNode::initLeaf().
void MemoryArena::FreeAll () [inline]
Definition at line 429 of file pbrt.h.
void* MemoryArena::Alloc (u_int sz) [inline]
Definition at line 412 of file pbrtlex.l.
void MemoryArena::FreeAll () [inline]
Definition at line 430 of file pbrtlex.l.
Member Data Documentation
u_int MemoryArena::curBlockPos [private]
Definition at line 438 of file pbrt.h.
u_int MemoryArena::blockSize [private]
Definition at line 438 of file pbrt.h.
char * MemoryArena::currentBlock [private]
Definition at line 439 of file pbrt.h.
vector< char * > MemoryArena::usedBlocks [private]
Definition at line 440 of file pbrt.h.
vector< char * > MemoryArena::availableBlocks [private]
Definition at line 440 of file pbrt.h.
The documentation for this class was generated from the following file:
pbrt.h