pbrt: Primer Class Reference
Primer Class Reference
Public Member Functions
Primer (Reference< Texture< float > > bump)
BSDF * GetBSDF (const DifferentialGeometry &dgGeom, const DifferentialGeometry &dgShading) const
Public Attributes
Reference< Texture< float > > bumpMap
Detailed Description
Definition at line 28 of file primer.cpp.
Constructor & Destructor Documentation
Primer::Primer (Reference< Texture< float > > bump) [inline]
Definition at line 30 of file primer.cpp.
Referenced by CreateMaterial().
Member Function Documentation
BSDF * Primer::GetBSDF (const DifferentialGeometry & dgGeom, const DifferentialGeometry & dgShading) const [virtual]
Implements Material.
Definition at line 36 of file primer.cpp.
References BSDF::Add(), BSDF_ALLOC, BSDF_DIFFUSE, BSDF_REFLECTION, Material::Bump(), bumpMap, BSDF::f(), and DifferentialGeometry::nn.
Member Data Documentation
Reference<Texture<float> > Primer::bumpMap
Definition at line 32 of file primer.cpp.
Referenced by CreateMaterial(), and GetBSDF().
The documentation for this class was generated from the following file:
primer.cpp