pbrt: StatsPercentage Class Reference
StatsPercentage Class Reference
#include <pbrt.h>
Public Member Functions
void Add (int a, int b)
StatsPercentage (const string &category, const string &name)
void Add (int a, int b)
StatsPercentage (const string &category, const string &name)
Private Attributes
StatsCounterType na
StatsCounterType nb
Detailed Description
Definition at line 310 of file pbrt.h.
Constructor & Destructor Documentation
StatsPercentage::StatsPercentage (const string & category, const string & name)
Definition at line 224 of file util.cpp.
References addTracker(), na, and nb.
StatsPercentage::StatsPercentage (const string & category, const string & name)
Member Function Documentation
void StatsPercentage::Add (int a, int b) [inline]
Definition at line 313 of file pbrt.h.
Referenced by GridAccel::GridAccel(), IrradianceCache::InterpolateIrradiance(), Triangle::Intersect(), Triangle::IntersectP(), and PhotonProcess::operator()().
void StatsPercentage::Add (int a, int b) [inline]
Definition at line 314 of file pbrtlex.l.
Member Data Documentation
StatsCounterType StatsPercentage::na [private]
Definition at line 317 of file pbrt.h.
Referenced by StatsPercentage().
StatsCounterType StatsPercentage::nb [private]
Definition at line 317 of file pbrt.h.
Referenced by StatsPercentage().
The documentation for this class was generated from the following files:
pbrt.h
util.cpp