pbrt: DensityRegion Class Reference
DensityRegion Class Reference
#include <volume.h>
Public Member Functions
DensityRegion (const Spectrum &sig_a, const Spectrum &sig_s, float g, const Spectrum &Le, const Transform &VolumeToWorld)
virtual float Density (const Point &Pobj) const =0
Spectrum sigma_a (const Point &p, const Vector &) const
Spectrum sigma_s (const Point &p, const Vector &) const
Spectrum sigma_t (const Point &p, const Vector &) const
Spectrum Lve (const Point &p, const Vector &) const
float p (const Point &p, const Vector &w, const Vector &wp) const
Spectrum Tau (const Ray &r, float stepSize, float offset) const
Protected Attributes
Transform WorldToVolume
Spectrum sig_a
Spectrum sig_s
Spectrum le
float g
Detailed Description
Definition at line 62 of file volume.h.
Constructor & Destructor Documentation
DensityRegion::DensityRegion (const Spectrum & sig_a, const Spectrum & sig_s, float g, const Spectrum & Le, const Transform & VolumeToWorld)
Definition at line 61 of file volume.cpp.
References Transform::GetInverse(), and WorldToVolume.
Member Function Documentation
virtual float DensityRegion::Density (const Point & Pobj) const [pure virtual]
Implemented in ExponentialDensity, and VolumeGrid.
Spectrum DensityRegion::sigma_a (const Point & p, const Vector &) const [inline, virtual]
Implements VolumeRegion.
Definition at line 68 of file volume.h.
Referenced by CreateVolumeRegion().
Spectrum DensityRegion::sigma_s (const Point & p, const Vector &) const [inline, virtual]
Implements VolumeRegion.
Definition at line 71 of file volume.h.
Referenced by CreateVolumeRegion().
Spectrum DensityRegion::sigma_t (const Point & p, const Vector &) const [inline, virtual]
Reimplemented from VolumeRegion.
Definition at line 74 of file volume.h.
Referenced by Tau().
Spectrum DensityRegion::Lve (const Point & p, const Vector &) const [inline, virtual]
Implements VolumeRegion.
Definition at line 77 of file volume.h.
float DensityRegion::p (const Point & p, const Vector & w, const Vector & wp) const [inline, virtual]
Implements VolumeRegion.
Definition at line 80 of file volume.h.
References PhaseHG().
Spectrum DensityRegion::Tau (const Ray & r, float stepSize, float offset) const [virtual]
Implements VolumeRegion.
Definition at line 137 of file volume.cpp.
References Ray::d, VolumeRegion::IntersectP(), Vector::Length(), Ray::maxt, Ray::mint, Ray::o, and sigma_t().
Member Data Documentation
Transform DensityRegion::WorldToVolume [protected]
Definition at line 87 of file volume.h.
Referenced by DensityRegion(), VolumeGrid::IntersectP(), ExponentialDensity::IntersectP(), VolumeGrid::WorldBound(), and ExponentialDensity::WorldBound().
Spectrum DensityRegion::sig_a [protected]
Definition at line 88 of file volume.h.
Spectrum DensityRegion::sig_s [protected]
Definition at line 88 of file volume.h.
Spectrum DensityRegion::le [protected]
Definition at line 88 of file volume.h.
float DensityRegion::g [protected]
Definition at line 89 of file volume.h.
Referenced by CreateVolumeRegion().
The documentation for this class was generated from the following files:
volume.h
volume.cpp