pbrt: ProjectionLight Class Reference
ProjectionLight Class Reference
Public Member Functions
ProjectionLight (const Transform &light2world, const Spectrum &intensity, const string &texname, float fov)
~ProjectionLight ()
Spectrum Sample_L (const Point &p, Vector *wi, VisibilityTester *vis) const
bool IsDeltaLight () const
Spectrum Projection (const Vector &w) const
Spectrum Power (const Scene *) const
Spectrum Sample_L (const Point &P, float u1, float u2, Vector *wo, float *pdf, VisibilityTester *visibility) const
Spectrum Sample_L (const Scene *scene, float u1, float u2, float u3, float u4, Ray *ray, float *pdf) const
float Pdf (const Point &, const Vector &) const
Private Attributes
MIPMap< Spectrum > * projectionMap
Point lightPos
Spectrum Intensity
Transform lightProjection
float hither
float yon
float screenX0
float screenX1
float screenY0
float screenY1
float cosTotalWidth
Detailed Description
Definition at line 30 of file projection.cpp.
Constructor & Destructor Documentation
ProjectionLight::ProjectionLight (const Transform & light2world, const Spectrum & intensity, const string & texname, float fov)
Definition at line 60 of file projection.cpp.
References cosTotalWidth, hither, Intensity, lightPos, lightProjection, Light::LightToWorld, Perspective(), projectionMap, Radians(), RAY_EPSILON, ReadImage(), screenX0, screenX1, screenY0, screenY1, and yon.
Referenced by CreateLight().
ProjectionLight::~ProjectionLight ()
Definition at line 93 of file projection.cpp.
References projectionMap.
Member Function Documentation
Spectrum ProjectionLight::Sample_L (const Point & p, Vector * wi, VisibilityTester * vis) const [virtual]
Implements Light.
Definition at line 94 of file projection.cpp.
References DistanceSquared(), Intensity, lightPos, Normalize(), Projection(), and VisibilityTester::SetSegment().
bool ProjectionLight::IsDeltaLight () const [inline, virtual]
Implements Light.
Definition at line 37 of file projection.cpp.
Spectrum ProjectionLight::Projection (const Vector & w) const
Definition at line 101 of file projection.cpp.
References hither, lightProjection, MIPMap< T >::Lookup(), projectionMap, screenX0, screenX1, screenY0, screenY1, Light::WorldToLight, Point::x, Vector::x, Point::y, Vector::y, and Vector::z.
Referenced by Sample_L().
Spectrum ProjectionLight::Power (const Scene *) const [inline, virtual]
Implements Light.
Definition at line 39 of file projection.cpp.
References cosTotalWidth, Intensity, MIPMap< T >::Lookup(), M_PI, and projectionMap.
Spectrum ProjectionLight::Sample_L (const Point & P, float u1, float u2, Vector * wo, float * pdf, VisibilityTester * visibility) const [virtual]
Implements Light.
Definition at line 114 of file projection.cpp.
References DistanceSquared(), Intensity, lightPos, Normalize(), Projection(), and VisibilityTester::SetSegment().
Spectrum ProjectionLight::Sample_L (const Scene * scene, float u1, float u2, float u3, float u4, Ray * ray, float * pdf) const [virtual]
Implements Light.
Definition at line 122 of file projection.cpp.
References cosTotalWidth, Ray::d, Intensity, lightPos, Light::LightToWorld, Ray::o, Projection(), UniformConePdf(), and UniformSampleCone().
float ProjectionLight::Pdf (const Point & , const Vector &) const [virtual]
Implements Light.
Definition at line 130 of file projection.cpp.
Member Data Documentation
MIPMap<Spectrum>* ProjectionLight::projectionMap [private]
Definition at line 50 of file projection.cpp.
Referenced by Power(), Projection(), ProjectionLight(), and ~ProjectionLight().
Point ProjectionLight::lightPos [private]
Definition at line 51 of file projection.cpp.
Referenced by ProjectionLight(), and Sample_L().
Spectrum ProjectionLight::Intensity [private]
Definition at line 52 of file projection.cpp.
Referenced by Power(), ProjectionLight(), and Sample_L().
Transform ProjectionLight::lightProjection [private]
Definition at line 53 of file projection.cpp.
Referenced by Projection(), and ProjectionLight().
float ProjectionLight::hither [private]
Definition at line 54 of file projection.cpp.
Referenced by Projection(), and ProjectionLight().
float ProjectionLight::yon [private]
Definition at line 54 of file projection.cpp.
Referenced by ProjectionLight().
float ProjectionLight::screenX0 [private]
Definition at line 55 of file projection.cpp.
Referenced by Projection(), and ProjectionLight().
float ProjectionLight::screenX1 [private]
Definition at line 55 of file projection.cpp.
Referenced by Projection(), and ProjectionLight().
float ProjectionLight::screenY0 [private]
Definition at line 55 of file projection.cpp.
Referenced by Projection(), and ProjectionLight().
float ProjectionLight::screenY1 [private]
Definition at line 55 of file projection.cpp.
Referenced by Projection(), and ProjectionLight().
float ProjectionLight::cosTotalWidth [private]
Definition at line 56 of file projection.cpp.
Referenced by Power(), ProjectionLight(), and Sample_L().
The documentation for this class was generated from the following file:
projection.cpp