pbrt: Integrator Class Reference
Integrator Class Reference
#include <transport.h>
Public Member Functions
virtual ~Integrator ()
virtual Spectrum Li (const Scene *scene, const RayDifferential &ray, const Sample *sample, float *alpha) const =0
virtual void Preprocess (const Scene *scene)
virtual void RequestSamples (Sample *sample, const Scene *scene)
Detailed Description
Definition at line 35 of file transport.h.
Constructor & Destructor Documentation
Integrator::~Integrator () [virtual]
Definition at line 28 of file transport.cpp.
Member Function Documentation
virtual Spectrum Integrator::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [pure virtual]
Implemented in BidirIntegrator, DebugIntegrator, DirectLighting, EmissionIntegrator, ExPhotonIntegrator, IGIIntegrator, IrradianceCache, PathIntegrator, PhotonIntegrator, SingleScattering, and WhittedIntegrator.
Referenced by Scene::Li().
virtual void Integrator::Preprocess (const Scene * scene) [inline, virtual]
Reimplemented in ExPhotonIntegrator, IGIIntegrator, IrradianceCache, and PhotonIntegrator.
Definition at line 43 of file transport.h.
Referenced by Scene::Render().
virtual void Integrator::RequestSamples (Sample * sample, const Scene * scene) [inline, virtual]
Reimplemented in BidirIntegrator, DirectLighting, EmissionIntegrator, ExPhotonIntegrator, IGIIntegrator, IrradianceCache, PathIntegrator, PhotonIntegrator, and SingleScattering.
Definition at line 45 of file transport.h.
Referenced by Sample::Sample().
The documentation for this class was generated from the following files:
transport.h
transport.cpp