pbrt: ExponentialDensity Class Reference
ExponentialDensity Class Reference
Public Member Functions
ExponentialDensity (const Spectrum &sa, const Spectrum &ss, float gg, const Spectrum &emit, const BBox &e, const Transform &v2w, float aa, float bb, const Vector &up)
BBox WorldBound () const
bool IntersectP (const Ray &r, float *t0, float *t1) const
float Density (const Point &Pobj) const
Private Attributes
BBox extent
float a
float b
Vector upDir
Detailed Description
Definition at line 27 of file exponential.cpp.
Constructor & Destructor Documentation
ExponentialDensity::ExponentialDensity (const Spectrum & sa, const Spectrum & ss, float gg, const Spectrum & emit, const BBox & e, const Transform & v2w, float aa, float bb, const Vector & up) [inline]
Definition at line 30 of file exponential.cpp.
References Normalize(), and upDir.
Member Function Documentation
float ExponentialDensity::Density (const Point & Pobj) const [inline, virtual]
Implements DensityRegion.
Definition at line 43 of file exponential.cpp.
References a, b, Dot(), extent, BBox::Inside(), BBox::pMin, and upDir.
bool ExponentialDensity::IntersectP (const Ray & r, float * t0, float * t1) const [inline, virtual]
Implements VolumeRegion.
Definition at line 39 of file exponential.cpp.
References extent, BBox::IntersectP(), and DensityRegion::WorldToVolume.
BBox ExponentialDensity::WorldBound () const [inline, virtual]
Implements VolumeRegion.
Definition at line 38 of file exponential.cpp.
References extent, Transform::GetInverse(), and DensityRegion::WorldToVolume.
Member Data Documentation
float ExponentialDensity::a [private]
Definition at line 51 of file exponential.cpp.
Referenced by Density().
float ExponentialDensity::b [private]
Definition at line 51 of file exponential.cpp.
Referenced by Density().
BBox ExponentialDensity::extent [private]
Definition at line 50 of file exponential.cpp.
Referenced by Density(), IntersectP(), and WorldBound().
Vector ExponentialDensity::upDir [private]
Definition at line 52 of file exponential.cpp.
Referenced by Density(), and ExponentialDensity().
The documentation for this class was generated from the following file:
exponential.cpp