pbrt: FresnelDielectric Class Reference
FresnelDielectric Class Reference
#include <reflection.h>
Public Member Functions
Spectrum Evaluate (float cosi) const
FresnelDielectric (float ei, float et)
Private Attributes
float eta_i
float eta_t
Detailed Description
Definition at line 185 of file reflection.h.
Constructor & Destructor Documentation
FresnelDielectric::FresnelDielectric (float ei, float et) [inline]
Definition at line 189 of file reflection.h.
Member Function Documentation
Spectrum FresnelDielectric::Evaluate (float cosi) const [virtual]
Implements Fresnel.
Definition at line 77 of file reflection.cpp.
References Clamp(), eta_i, eta_t, and FrDiel().
Referenced by SpecularTransmission::Sample_f().
Member Data Documentation
float FresnelDielectric::eta_i [private]
Definition at line 195 of file reflection.h.
Referenced by Evaluate().
float FresnelDielectric::eta_t [private]
Definition at line 195 of file reflection.h.
Referenced by Evaluate().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp