pbrt: ImageTexture< T > Class Template Reference
ImageTexture< T > Class Template Reference
Public Member Functions
ImageTexture (TextureMapping2D *m, const string &filename, bool doTri, float maxAniso, ImageWrap wm)
T Evaluate (const DifferentialGeometry &) const
~ImageTexture ()
Static Private Member Functions
static MIPMap< T > * GetTexture (const string &filename, bool doTrilinear, float maxAniso, ImageWrap wm)
static void convert (const Spectrum &from, Spectrum *to)
static void convert (const Spectrum &from, float *to)
Private Attributes
MIPMap< T > * mipmap
TextureMapping2D * mapping
Detailed Description
template<class T>
class ImageTexture< T >
Definition at line 33 of file imagemap.cpp.
Constructor & Destructor Documentation
template<class T > ImageTexture< T >::ImageTexture (TextureMapping2D * m, const string & filename, bool doTri, float maxAniso, ImageWrap wm) [inline]
Definition at line 59 of file imagemap.cpp.
References ImageTexture< T >::GetTexture(), ImageTexture< T >::mapping, and ImageTexture< T >::mipmap.
template<class T > ImageTexture< T >::~ImageTexture () [inline]
Definition at line 68 of file imagemap.cpp.
References ImageTexture< T >::mapping.
Member Function Documentation
template<class T> static void ImageTexture< T >::convert (const Spectrum & from, float * to) [inline, static, private]
Definition at line 50 of file imagemap.cpp.
References Spectrum::y().
template<class T> static void ImageTexture< T >::convert (const Spectrum & from, Spectrum * to) [inline, static, private]
Definition at line 47 of file imagemap.cpp.
Referenced by ImageTexture< T >::GetTexture().
template<class T > T ImageTexture< T >::Evaluate (const DifferentialGeometry & dg) const [inline, virtual]
Implements Texture< T >.
Definition at line 123 of file imagemap.cpp.
References TextureMapping2D::Map(), ImageTexture< T >::mapping, and ImageTexture< T >::mipmap.
template<class T > MIPMap< T > * ImageTexture< T >::GetTexture (const string & filename, bool doTrilinear, float maxAniso, ImageWrap wm) [inline, static, private]
Definition at line 86 of file imagemap.cpp.
References ImageTexture< T >::convert(), and ReadImage().
Referenced by ImageTexture< T >::ImageTexture().
Member Data Documentation
template<class T> TextureMapping2D* ImageTexture< T >::mapping [private]
Definition at line 55 of file imagemap.cpp.
Referenced by ImageTexture< T >::Evaluate(), ImageTexture< T >::ImageTexture(), and ImageTexture< T >::~ImageTexture().
template<class T> MIPMap<T>* ImageTexture< T >::mipmap [private]
Definition at line 54 of file imagemap.cpp.
Referenced by ImageTexture< T >::Evaluate(), and ImageTexture< T >::ImageTexture().
The documentation for this class was generated from the following file:
imagemap.cpp