pbrt: PhotonIntegrator Class Reference
PhotonIntegrator Class Reference
Public Member Functions
PhotonIntegrator (int ncaus, int ndir, int nindir, int nLookup, int mdepth, float maxdist, bool finalGather, int gatherSamples, bool directWithPhotons)
~PhotonIntegrator ()
Spectrum Li (const Scene *scene, const RayDifferential &ray, const Sample *sample, float *alpha) const
void RequestSamples (Sample *sample, const Scene *scene)
void Preprocess (const Scene *)
Static Private Member Functions
static bool unsuccessful (int needed, int found, int shot)
static Spectrum LPhoton (KdTree< Photon, PhotonProcess > *map, int nPaths, int nLookup, BSDF *bsdf, const Intersection &isect, const Vector &w, float maxDistSquared)
Private Attributes
u_int nCausticPhotons
u_int nIndirectPhotons
u_int nDirectPhotons
u_int nLookup
int specularDepth
int maxSpecularDepth
float maxDistSquared
bool directWithPhotons
bool finalGather
int gatherSamples
int * lightSampleOffset
int lightNumOffset
int * bsdfSampleOffset
int * bsdfComponentOffset
int gatherSampleOffset
int gatherComponentOffset
int nCausticPaths
int nDirectPaths
int nIndirectPaths
KdTree< Photon, PhotonProcess > * causticMap
KdTree< Photon, PhotonProcess > * directMap
KdTree< Photon, PhotonProcess > * indirectMap
Detailed Description
Definition at line 35 of file photonmap.cpp.
Constructor & Destructor Documentation
PhotonIntegrator::PhotonIntegrator (int ncaus, int ndir, int nindir, int nLookup, int mdepth, float maxdist, bool finalGather, int gatherSamples, bool directWithPhotons)
Definition at line 105 of file photonmap.cpp.
References causticMap, directMap, directWithPhotons, finalGather, gatherSamples, indirectMap, maxDistSquared, maxSpecularDepth, nCausticPhotons, nDirectPhotons, nIndirectPhotons, nLookup, and specularDepth.
PhotonIntegrator::~PhotonIntegrator ()
Definition at line 120 of file photonmap.cpp.
References causticMap, directMap, and indirectMap.
Member Function Documentation
Spectrum PhotonIntegrator::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [virtual]
Implements Integrator.
Definition at line 299 of file photonmap.cpp.
References AbsDot(), Spectrum::Black(), BSDF_ALL, BSDF_REFLECTION, BSDF_SPECULAR, BSDF_TRANSMISSION, bsdfComponentOffset, bsdfSampleOffset, causticMap, Ray::d, Intersection::dg, BSDF::dgShading, directMap, directWithPhotons, DifferentialGeometry::dndu, DifferentialGeometry::dndv, Dot(), DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, BSDF::eta, finalGather, gatherComponentOffset, gatherSampleOffset, gatherSamples, Intersection::GetBSDF(), RayDifferential::hasDifferentials, indirectMap, Scene::Intersect(), Intersection::Le(), Scene::Li(), Scene::lights, lightSampleOffset, LPhoton(), maxDistSquared, maxSpecularDepth, nCausticPaths, nDirectPaths, nIndirectPaths, nLookup, DifferentialGeometry::nn, Ray::o, Sample::oneD, DifferentialGeometry::p, RayDifferential::rx, RayDifferential::ry, BSDF::Sample_f(), specularDepth, Scene::Transmittance(), Sample::twoD, and UniformSampleAllLights().
Spectrum PhotonIntegrator::LPhoton (KdTree< Photon, PhotonProcess > * map, int nPaths, int nLookup, BSDF * bsdf, const Intersection & isect, const Vector & w, float maxDistSquared) [static, private]
Definition at line 433 of file photonmap.cpp.
References StatsRatio::Add(), Photon::alpha, BSDF_ALL_REFLECTION, BSDF_ALL_TRANSMISSION, BSDF_DIFFUSE, BSDF_GLOSSY, BSDF_REFLECTION, BSDF_TRANSMISSION, Intersection::dg, BSDF::dgShading, Dot(), BSDF::f(), PhotonProcess::foundPhotons, INV_PI, KdTree< NodeData, LookupProc >::Lookup(), M_PI, DifferentialGeometry::nn, BSDF::NumComponents(), DifferentialGeometry::p, ClosePhoton::photon, PhotonProcess::photons, and BSDF::rho().
Referenced by Li().
void PhotonIntegrator::Preprocess (const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 147 of file photonmap.cpp.
References AbsDot(), Spectrum::Black(), BSDF_ALL, BSDF_REFLECTION, BSDF_SPECULAR, BSDF_TRANSMISSION, causticMap, Ray::d, Intersection::dg, BSDF::dgShading, directMap, ProgressReporter::Done(), Error(), Floor2Int(), BSDF::FreeAll(), Intersection::GetBSDF(), indirectMap, Scene::Intersect(), Scene::lights, nCausticPaths, nCausticPhotons, nDirectPaths, nDirectPhotons, nIndirectPaths, nIndirectPhotons, DifferentialGeometry::nn, BSDF::NumComponents(), DifferentialGeometry::p, RadicalInverse(), RandomFloat(), BSDF::Sample_f(), Light::Sample_L(), Scene::Transmittance(), unsuccessful(), and ProgressReporter::Update().
void PhotonIntegrator::RequestSamples (Sample * sample, const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 125 of file photonmap.cpp.
References Sample::Add1D(), Sample::Add2D(), bsdfComponentOffset, bsdfSampleOffset, finalGather, gatherComponentOffset, gatherSampleOffset, gatherSamples, lightNumOffset, Scene::lights, lightSampleOffset, Light::nSamples, Sampler::RoundSize(), and Scene::sampler.
static bool PhotonIntegrator::unsuccessful (int needed, int found, int shot) [inline, static, private]
Definition at line 48 of file photonmap.cpp.
Referenced by Preprocess().
Member Data Documentation
int * PhotonIntegrator::bsdfComponentOffset [private]
Definition at line 65 of file photonmap.cpp.
Referenced by Li(), and RequestSamples().
int* PhotonIntegrator::bsdfSampleOffset [private]
Definition at line 65 of file photonmap.cpp.
Referenced by Li(), and RequestSamples().
KdTree<Photon, PhotonProcess>* PhotonIntegrator::causticMap [mutable, private]
Definition at line 68 of file photonmap.cpp.
Referenced by Li(), PhotonIntegrator(), Preprocess(), and ~PhotonIntegrator().
KdTree<Photon, PhotonProcess>* PhotonIntegrator::directMap [mutable, private]
Definition at line 69 of file photonmap.cpp.
Referenced by Li(), PhotonIntegrator(), Preprocess(), and ~PhotonIntegrator().
bool PhotonIntegrator::directWithPhotons [private]
Definition at line 61 of file photonmap.cpp.
Referenced by Li(), and PhotonIntegrator().
bool PhotonIntegrator::finalGather [private]
Definition at line 61 of file photonmap.cpp.
Referenced by Li(), PhotonIntegrator(), and RequestSamples().
int PhotonIntegrator::gatherComponentOffset [private]
Definition at line 66 of file photonmap.cpp.
Referenced by Li(), and RequestSamples().
int PhotonIntegrator::gatherSampleOffset [private]
Definition at line 66 of file photonmap.cpp.
Referenced by Li(), and RequestSamples().
int PhotonIntegrator::gatherSamples [private]
Definition at line 62 of file photonmap.cpp.
Referenced by Li(), PhotonIntegrator(), and RequestSamples().
KdTree<Photon, PhotonProcess>* PhotonIntegrator::indirectMap [mutable, private]
Definition at line 70 of file photonmap.cpp.
Referenced by Li(), PhotonIntegrator(), Preprocess(), and ~PhotonIntegrator().
int PhotonIntegrator::lightNumOffset [private]
Definition at line 64 of file photonmap.cpp.
Referenced by RequestSamples().
int* PhotonIntegrator::lightSampleOffset [private]
Definition at line 64 of file photonmap.cpp.
Referenced by Li(), and RequestSamples().
float PhotonIntegrator::maxDistSquared [private]
Definition at line 60 of file photonmap.cpp.
Referenced by Li(), and PhotonIntegrator().
int PhotonIntegrator::maxSpecularDepth [private]
Definition at line 59 of file photonmap.cpp.
Referenced by Li(), and PhotonIntegrator().
int PhotonIntegrator::nCausticPaths [private]
Definition at line 67 of file photonmap.cpp.
Referenced by Li(), and Preprocess().
u_int PhotonIntegrator::nCausticPhotons [private]
Definition at line 56 of file photonmap.cpp.
Referenced by PhotonIntegrator(), and Preprocess().
int PhotonIntegrator::nDirectPaths [private]
Definition at line 67 of file photonmap.cpp.
Referenced by Li(), and Preprocess().
u_int PhotonIntegrator::nDirectPhotons [private]
Definition at line 56 of file photonmap.cpp.
Referenced by PhotonIntegrator(), and Preprocess().
int PhotonIntegrator::nIndirectPaths [private]
Definition at line 67 of file photonmap.cpp.
Referenced by Li(), and Preprocess().
u_int PhotonIntegrator::nIndirectPhotons [private]
Definition at line 56 of file photonmap.cpp.
Referenced by PhotonIntegrator(), and Preprocess().
u_int PhotonIntegrator::nLookup [private]
Definition at line 57 of file photonmap.cpp.
Referenced by Li(), and PhotonIntegrator().
int PhotonIntegrator::specularDepth [mutable, private]
Definition at line 58 of file photonmap.cpp.
Referenced by Li(), and PhotonIntegrator().
The documentation for this class was generated from the following file:
photonmap.cpp