pbrt: LoopSubdiv Class Reference
LoopSubdiv Class Reference
Public Member Functions
LoopSubdiv (const Transform &o2w, bool ro, int nt, int nv, const int *vi, const Point *P, int nlevels)
~LoopSubdiv ()
bool CanIntersect () const
void Refine (vector< Reference< Shape > > &refined) const
BBox ObjectBound () const
BBox WorldBound () const
Static Private Member Functions
static float beta (int valence)
static Point weightOneRing (SDVertex *vert, float beta)
static Point weightBoundary (SDVertex *vert, float beta)
static float gamma (int valence)
Private Attributes
int nLevels
vector< SDVertex * > vertices
vector< SDFace * > faces
Detailed Description
Definition at line 112 of file loopsubdiv.cpp.
Constructor & Destructor Documentation
LoopSubdiv::LoopSubdiv (const Transform & o2w, bool ro, int nt, int nv, const int * vi, const Point * P, int nlevels)
Definition at line 161 of file loopsubdiv.cpp.
References SDVertex::boundary, SDFace::f, SDEdge::f, SDEdge::f0edgeNum, faces, if(), NEXT, SDFace::nextFace(), nLevels, SDVertex::regular, SDVertex::startFace, SDFace::v, SDVertex::valence(), and vertices.
LoopSubdiv::~LoopSubdiv ()
Definition at line 227 of file loopsubdiv.cpp.
References faces, and vertices.
Member Function Documentation
static float LoopSubdiv::beta (int valence) [inline, static, private]
Definition at line 125 of file loopsubdiv.cpp.
Referenced by gamma(), and Refine().
bool LoopSubdiv::CanIntersect () const [virtual]
Reimplemented from Shape.
Definition at line 243 of file loopsubdiv.cpp.
static float LoopSubdiv::gamma (int valence) [inline, static, private]
Definition at line 131 of file loopsubdiv.cpp.
References beta().
Referenced by Refine().
BBox LoopSubdiv::ObjectBound () const [virtual]
Implements Shape.
Definition at line 231 of file loopsubdiv.cpp.
References Union(), and vertices.
void LoopSubdiv::Refine (vector< Reference< Shape > > & refined) const [virtual]
Reimplemented from Shape.
Definition at line 247 of file loopsubdiv.cpp.
References ParamSet::AddInt(), ParamSet::AddNormal(), ParamSet::AddPoint(), beta(), SDVertex::boundary, SDVertex::child, SDFace::children, Cross(), SDFace::f, faces, gamma(), M_PI, MakeShape(), NEXT, nLevels, Shape::ObjectToWorld, SDVertex::oneRing(), SDFace::otherVert(), SDVertex::P, PREV, SDVertex::regular, Shape::reverseOrientation, SDVertex::startFace, SDEdge::v, SDFace::v, SDVertex::valence(), vertices, SDFace::vnum(), weightBoundary(), and weightOneRing().
Point LoopSubdiv::weightBoundary (SDVertex * vert, float beta) [static, private]
Definition at line 470 of file loopsubdiv.cpp.
References SDVertex::oneRing(), SDVertex::P, and SDVertex::valence().
Referenced by Refine().
Point LoopSubdiv::weightOneRing (SDVertex * vert, float beta) [static, private]
Definition at line 439 of file loopsubdiv.cpp.
References SDVertex::oneRing(), SDVertex::P, and SDVertex::valence().
Referenced by Refine().
BBox LoopSubdiv::WorldBound () const [virtual]
Reimplemented from Shape.
Definition at line 237 of file loopsubdiv.cpp.
References Shape::ObjectToWorld, Union(), and vertices.
Member Data Documentation
vector<SDFace *> LoopSubdiv::faces [private]
Definition at line 137 of file loopsubdiv.cpp.
Referenced by LoopSubdiv(), Refine(), and ~LoopSubdiv().
int LoopSubdiv::nLevels [private]
Definition at line 135 of file loopsubdiv.cpp.
Referenced by LoopSubdiv(), and Refine().
vector<SDVertex *> LoopSubdiv::vertices [private]
Definition at line 136 of file loopsubdiv.cpp.
Referenced by LoopSubdiv(), ObjectBound(), Refine(), WorldBound(), and ~LoopSubdiv().
The documentation for this class was generated from the following file:
loopsubdiv.cpp