pbrt: CylindricalMapping2D Class Reference
CylindricalMapping2D Class Reference
#include <texture.h>
Public Member Functions
CylindricalMapping2D (const Transform &toCyl)
void Map (const DifferentialGeometry &dg, float *s, float *t, float *dsdx, float *dtdx, float *dsdy, float *dtdy) const
Private Member Functions
void cylinder (const Point &P, float *s, float *t) const
Private Attributes
Transform WorldToTexture
Detailed Description
Definition at line 64 of file texture.h.
Constructor & Destructor Documentation
CylindricalMapping2D::CylindricalMapping2D (const Transform & toCyl) [inline]
Definition at line 68 of file texture.h.
Member Function Documentation
void CylindricalMapping2D::cylinder (const Point & P, float * s, float * t) const [private]
Definition at line 125 of file texture.cpp.
References M_PI, Normalize(), WorldToTexture, Vector::x, Vector::y, and Vector::z.
Referenced by Map().
void CylindricalMapping2D::Map (const DifferentialGeometry & dg, float * s, float * t, float * dsdx, float * dtdx, float * dsdy, float * dtdy) const [virtual]
Implements TextureMapping2D.
Definition at line 107 of file texture.cpp.
References cylinder(), DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, and DifferentialGeometry::p.
Member Data Documentation
Transform CylindricalMapping2D::WorldToTexture [private]
Definition at line 76 of file texture.h.
Referenced by cylinder().
The documentation for this class was generated from the following files:
texture.h
texture.cpp