pbrt: Octree< NodeData, LookupProc > Class Template Reference
Octree< NodeData, LookupProc > Class Template Reference
#include <octree.h>
Public Member Functions
Octree (const BBox &b, int md=16)
void Add (const NodeData &dataItem, const BBox &dataBound)
void Lookup (const Point &p, const LookupProc &process)
Private Member Functions
void addPrivate (OctNode< NodeData > *node, const BBox &nodeBound, const NodeData &dataItem, const BBox &dataBound, float diag2, int depth=0)
void lookupPrivate (OctNode< NodeData > *node, const BBox &nodeBound, const Point &P, const LookupProc &process)
Private Attributes
int maxDepth
BBox bound
OctNode< NodeData > root
Detailed Description
template<class NodeData, class LookupProc>
class Octree< NodeData, LookupProc >
Definition at line 42 of file octree.h.
Constructor & Destructor Documentation
template<class NodeData, class LookupProc> Octree< NodeData, LookupProc >::Octree (const BBox & b, int md = 16) [inline]
Definition at line 45 of file octree.h.
Member Function Documentation
template<class NodeData, class LookupProc> void Octree< NodeData, LookupProc >::Add (const NodeData & dataItem, const BBox & dataBound) [inline]
Definition at line 49 of file octree.h.
Referenced by IrradianceCache::IndirectLo().
template<class NodeData, class LookupProc > void Octree< NodeData, LookupProc >::addPrivate (OctNode< NodeData > * node, const BBox & nodeBound, const NodeData & dataItem, const BBox & dataBound, float diag2, int depth = 0) [inline, private]
Definition at line 71 of file octree.h.
References OctNode< NodeData >::children, OctNode< NodeData >::data, DistanceSquared(), Octree< NodeData, LookupProc >::maxDepth, BBox::pMax, BBox::pMin, Point::x, Point::y, and Point::z.
Referenced by Octree< IrradianceSample, IrradProcess >::Add().
template<class NodeData, class LookupProc> void Octree< NodeData, LookupProc >::Lookup (const Point & p, const LookupProc & process) [inline]
Definition at line 53 of file octree.h.
Referenced by IrradianceCache::InterpolateIrradiance().
template<class NodeData, class LookupProc> void Octree< NodeData, LookupProc >::lookupPrivate (OctNode< NodeData > * node, const BBox & nodeBound, const Point & P, const LookupProc & process) [inline, private]
Definition at line 125 of file octree.h.
References OctNode< NodeData >::children, OctNode< NodeData >::data, BBox::pMax, BBox::pMin, Point::x, Point::y, and Point::z.
Referenced by Octree< IrradianceSample, IrradProcess >::Lookup().
Member Data Documentation
template<class NodeData, class LookupProc> BBox Octree< NodeData, LookupProc >::bound [private]
Definition at line 66 of file octree.h.
Referenced by Octree< IrradianceSample, IrradProcess >::Add(), and Octree< IrradianceSample, IrradProcess >::Lookup().
template<class NodeData, class LookupProc> int Octree< NodeData, LookupProc >::maxDepth [private]
Definition at line 65 of file octree.h.
Referenced by Octree< NodeData, LookupProc >::addPrivate(), and Octree< IrradianceSample, IrradProcess >::Octree().
template<class NodeData, class LookupProc> OctNode<NodeData> Octree< NodeData, LookupProc >::root [private]
Definition at line 67 of file octree.h.
Referenced by Octree< IrradianceSample, IrradProcess >::Add(), and Octree< IrradianceSample, IrradProcess >::Lookup().
The documentation for this class was generated from the following file:
octree.h