pbrt: MitchellFilter Class Reference
MitchellFilter Class Reference
Public Member Functions
MitchellFilter (float b, float c, float xw, float yw)
float Evaluate (float x, float y) const
float Mitchell1D (float x) const
Private Attributes
float B
float C
Detailed Description
Definition at line 28 of file mitchell.cpp.
Constructor & Destructor Documentation
MitchellFilter::MitchellFilter (float b, float c, float xw, float yw) [inline]
Definition at line 31 of file mitchell.cpp.
References B, and C.
Referenced by CreateFilter().
Member Function Documentation
float MitchellFilter::Evaluate (float x, float y) const [virtual]
Implements Filter.
Definition at line 48 of file mitchell.cpp.
References Filter::invXWidth, Filter::invYWidth, and Mitchell1D().
float MitchellFilter::Mitchell1D (float x) const [inline]
Definition at line 34 of file mitchell.cpp.
References B, and C.
Referenced by Evaluate().
Member Data Documentation
float MitchellFilter::B [private]
Definition at line 45 of file mitchell.cpp.
Referenced by CreateFilter(), Mitchell1D(), and MitchellFilter().
float MitchellFilter::C [private]
Definition at line 45 of file mitchell.cpp.
Referenced by CreateFilter(), Mitchell1D(), and MitchellFilter().
The documentation for this class was generated from the following file:
mitchell.cpp