pbrt: StatsCounter Class Reference
StatsCounter Class Reference
#include <pbrt.h>
Public Member Functions
StatsCounter (const string &category, const string &name)
void operator++ ()
void operator++ (int)
void Max (StatsCounterType val)
void Min (StatsCounterType val)
operator double () const
StatsCounter (const string &category, const string &name)
void operator++ ()
void operator++ (int)
void Max (StatsCounterType val)
void Min (StatsCounterType val)
operator double () const
Private Attributes
StatsCounterType num
Detailed Description
Definition at line 288 of file pbrt.h.
Constructor & Destructor Documentation
StatsCounter::StatsCounter (const string & category, const string & name)
Definition at line 216 of file util.cpp.
References addTracker(), and num.
StatsCounter::StatsCounter (const string & category, const string & name)
Member Function Documentation
void StatsCounter::operator++ () [inline]
Definition at line 292 of file pbrt.h.
void StatsCounter::operator++ (int) [inline]
Definition at line 293 of file pbrt.h.
void StatsCounter::Max (StatsCounterType val) [inline]
Definition at line 294 of file pbrt.h.
Referenced by GridAccel::GridAccel(), and KdAccelNode::initLeaf().
void StatsCounter::Min (StatsCounterType val) [inline]
Definition at line 295 of file pbrt.h.
StatsCounter::operator double () const [inline]
Definition at line 296 of file pbrt.h.
void StatsCounter::operator++ () [inline]
Definition at line 293 of file pbrtlex.l.
void StatsCounter::operator++ (int) [inline]
Definition at line 294 of file pbrtlex.l.
void StatsCounter::Max (StatsCounterType val) [inline]
Definition at line 295 of file pbrtlex.l.
void StatsCounter::Min (StatsCounterType val) [inline]
Definition at line 296 of file pbrtlex.l.
StatsCounter::operator double () const [inline]
Definition at line 297 of file pbrtlex.l.
Member Data Documentation
StatsCounterType StatsCounter::num [private]
Definition at line 299 of file pbrt.h.
Referenced by StatsCounter().
The documentation for this class was generated from the following files:
pbrt.h
util.cpp