pbrt: Spectrum Class Reference
Spectrum Class Reference
#include <color.h>
Public Member Functions
Spectrum (float v=0.f)
Spectrum (float cs[COLOR_SAMPLES])
Spectrum (const Spectrum &s2)
Spectrum & operator= (const Spectrum &s2)
Spectrum & operator+= (const Spectrum &s2)
Spectrum operator+ (const Spectrum &s2) const
Spectrum operator- (const Spectrum &s2) const
Spectrum operator/ (const Spectrum &s2) const
Spectrum operator* (const Spectrum &sp) const
Spectrum & operator*= (const Spectrum &sp)
Spectrum operator* (float a) const
Spectrum & operator*= (float a)
Spectrum operator/ (float a) const
Spectrum & operator/= (float a)
void AddWeighted (float w, const Spectrum &s)
bool operator== (const Spectrum &sp) const
bool operator!= (const Spectrum &sp) const
bool Black () const
Spectrum Sqrt () const
Spectrum Pow (const Spectrum &e) const
Spectrum operator- () const
Spectrum Clamp (float low=0.f, float high=INFINITY) const
bool IsNaN () const
void Print (FILE *f) const
void XYZ (float xyz[3]) const
float y () const
bool operator< (const Spectrum &s2) const
Static Public Attributes
static const int CIEstart = 360
static const int CIEend = 830
static const int nCIE = CIEend-CIEstart+1
static const float CIE_X [nCIE]
static const float CIE_Y [nCIE]
static const float CIE_Z [nCIE]
Private Attributes
float c [COLOR_SAMPLES]
Static Private Attributes
static float XWeight [COLOR_SAMPLES]
static float YWeight [COLOR_SAMPLES]
static float ZWeight [COLOR_SAMPLES]
Friends
class ParamSet
ostream & operator<< (ostream &, const Spectrum &)
Spectrum operator* (float a, const Spectrum &s)
Spectrum Exp (const Spectrum &s)
Spectrum FromXYZ (float x, float y, float z)
Detailed Description
Definition at line 29 of file color.h.
Constructor & Destructor Documentation
Spectrum::Spectrum (float v = 0.f) [inline]
Definition at line 32 of file color.h.
References Assert, and COLOR_SAMPLES.
Spectrum::Spectrum (float cs[COLOR_SAMPLES]) [inline]
Definition at line 37 of file color.h.
References Assert.
Spectrum::Spectrum (const Spectrum & s2) [inline]
Definition at line 42 of file color.h.
References Assert, c, COLOR_SAMPLES, and IsNaN().
Member Function Documentation
void Spectrum::AddWeighted (float w, const Spectrum & s) [inline]
Definition at line 116 of file color.h.
References Assert, c, and COLOR_SAMPLES.
Referenced by ImageFilm::AddSample().
bool Spectrum::Black () const [inline]
Definition at line 129 of file color.h.
References COLOR_SAMPLES.
Referenced by EstimateDirect(), BidirIntegrator::evalPath(), BidirIntegrator::generatePath(), UberMaterial::GetBSDF(), Translucent::GetBSDF(), Mirror::GetBSDF(), Glass::GetBSDF(), IrradianceCache::IndirectLo(), WhittedIntegrator::Li(), SingleScattering::Li(), PhotonIntegrator::Li(), PathIntegrator::Li(), IrradianceCache::Li(), IGIIntegrator::Li(), ExPhotonIntegrator::Li(), DirectLighting::Li(), PhotonIntegrator::Preprocess(), IGIIntegrator::Preprocess(), ExPhotonIntegrator::Preprocess(), and BSDF::Sample_f().
Spectrum Spectrum::Clamp (float low = 0.f, float high = INFINITY) const [inline]
Definition at line 161 of file color.h.
References c, Clamp(), and COLOR_SAMPLES.
Referenced by MIPMap< Spectrum >::clamp(), FresnelApproxEta(), and FresnelApproxK().
bool Spectrum::IsNaN () const [inline]
Definition at line 168 of file color.h.
References COLOR_SAMPLES.
Referenced by operator=(), Pow(), Scene::Render(), Spectrum(), and Sqrt().
bool Spectrum::operator!= (const Spectrum & sp) const [inline]
Definition at line 126 of file color.h.
Spectrum Spectrum::operator* (float a) const [inline]
Definition at line 89 of file color.h.
References Assert, c, and COLOR_SAMPLES.
Spectrum Spectrum::operator* (const Spectrum & sp) const [inline]
Definition at line 78 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum& Spectrum::operator*= (float a) [inline]
Definition at line 96 of file color.h.
References Assert, and COLOR_SAMPLES.
Spectrum& Spectrum::operator*= (const Spectrum & sp) [inline]
Definition at line 84 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum Spectrum::operator+ (const Spectrum & s2) const [inline]
Definition at line 60 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum& Spectrum::operator+= (const Spectrum & s2) [inline]
Definition at line 55 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum Spectrum::operator- () const [inline]
Definition at line 148 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum Spectrum::operator- (const Spectrum & s2) const [inline]
Definition at line 66 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum Spectrum::operator/ (float a) const [inline]
Definition at line 106 of file color.h.
References Assert.
Spectrum Spectrum::operator/ (const Spectrum & s2) const [inline]
Definition at line 72 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum& Spectrum::operator/= (float a) [inline]
Definition at line 110 of file color.h.
References COLOR_SAMPLES.
bool Spectrum::operator< (const Spectrum & s2) const [inline]
Definition at line 191 of file color.h.
References y().
Spectrum& Spectrum::operator= (const Spectrum & s2) [inline]
Definition at line 47 of file color.h.
References Assert, c, COLOR_SAMPLES, and IsNaN().
bool Spectrum::operator== (const Spectrum & sp) const [inline]
Definition at line 121 of file color.h.
References c, and COLOR_SAMPLES.
Spectrum Spectrum::Pow (const Spectrum & e) const [inline]
Definition at line 141 of file color.h.
References Assert, c, COLOR_SAMPLES, and IsNaN().
Referenced by Lafortune::f().
void Spectrum::Print (FILE * f) const [inline]
Definition at line 173 of file color.h.
References COLOR_SAMPLES.
Spectrum Spectrum::Sqrt () const [inline]
Definition at line 134 of file color.h.
References Assert, c, COLOR_SAMPLES, and IsNaN().
Referenced by FresnelApproxEta(), and FresnelApproxK().
void Spectrum::XYZ (float xyz[3]) const [inline]
Definition at line 177 of file color.h.
References COLOR_SAMPLES.
float Spectrum::y () const [inline]
Definition at line 185 of file color.h.
References COLOR_SAMPLES.
Referenced by ImageTexture< T >::convert(), InfiniteAreaLightIS::InfiniteAreaLightIS(), SingleScattering::Li(), IGIIntegrator::Li(), EmissionIntegrator::Li(), operator<(), IGIIntegrator::Preprocess(), ExPhotonIntegrator::Preprocess(), ReadImage(), Scene::Render(), and WeightedSampleOneLight().
Friends And Related Function Documentation
Spectrum Exp (const Spectrum & s) [friend]
Definition at line 154 of file color.h.
Spectrum FromXYZ (float x, float y, float z) [friend]
Definition at line 44 of file color.cpp.
Spectrum operator* (float a, const Spectrum & s) [friend]
Definition at line 103 of file color.h.
ostream& operator<< (ostream & os, const Spectrum & s) [friend]
Definition at line 27 of file color.cpp.
friend class ParamSet [friend]
Definition at line 194 of file color.h.
Member Data Documentation
float Spectrum::c[COLOR_SAMPLES] [private]
Definition at line 205 of file color.h.
Referenced by AddWeighted(), Clamp(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator/(), operator<<(), operator=(), operator==(), Pow(), Spectrum(), Sqrt(), and ParamSet::ToString().
const float Spectrum::CIE_X [static]
Definition at line 200 of file color.h.
const float Spectrum::CIE_Y [static]
Definition at line 201 of file color.h.
const float Spectrum::CIE_Z [static]
Definition at line 202 of file color.h.
const int Spectrum::CIEend = 830 [static]
Definition at line 198 of file color.h.
const int Spectrum::CIEstart = 360 [static]
Definition at line 197 of file color.h.
const int Spectrum::nCIE = CIEend-CIEstart+1 [static]
Definition at line 199 of file color.h.
float Spectrum::XWeight [static, private]
Initial value:
 {
        0.412453f, 0.357580f, 0.180423f
}
Definition at line 206 of file color.h.
float Spectrum::YWeight [static, private]
Initial value:
 {
        0.212671f, 0.715160f, 0.072169f
}
Definition at line 207 of file color.h.
float Spectrum::ZWeight [static, private]
Initial value:
 {
        0.019334f, 0.119193f, 0.950227f
}
Definition at line 208 of file color.h.
The documentation for this class was generated from the following files:
color.h
color.cpp