pbrt: SingleScattering Class Reference
SingleScattering Class Reference
Public Member Functions
SingleScattering (float ss)
Spectrum Transmittance (const Scene *, const Ray &ray, const Sample *sample, float *alpha) const
void RequestSamples (Sample *sample, const Scene *scene)
Spectrum Li (const Scene *, const RayDifferential &ray, const Sample *sample, float *alpha) const
Private Attributes
float stepSize
int tauSampleOffset
int scatterSampleOffset
Detailed Description
Definition at line 29 of file single.cpp.
Constructor & Destructor Documentation
SingleScattering::SingleScattering (float ss) [inline]
Definition at line 32 of file single.cpp.
References stepSize.
Referenced by CreateVolumeIntegrator().
Member Function Documentation
Spectrum SingleScattering::Transmittance (const Scene * scene, const Ray & ray, const Sample * sample, float * alpha) const [virtual]
Implements VolumeIntegrator.
Definition at line 48 of file single.cpp.
References Sample::oneD, RandomFloat(), stepSize, VolumeRegion::Tau(), tauSampleOffset, and Scene::volumeRegion.
void SingleScattering::RequestSamples (Sample * sample, const Scene * scene) [virtual]
Reimplemented from Integrator.
Definition at line 43 of file single.cpp.
References Sample::Add1D(), scatterSampleOffset, and tauSampleOffset.
Spectrum SingleScattering::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [virtual]
Implements Integrator.
Definition at line 57 of file single.cpp.
References Spectrum::Black(), Ceil2Int(), Ray::d, Floor2Int(), VolumeRegion::IntersectP(), LatinHypercube(), Scene::lights, VolumeRegion::Lve(), N, Sample::oneD, VolumeRegion::p(), RandomFloat(), Light::Sample_L(), scatterSampleOffset, VolumeRegion::sigma_s(), stepSize, VolumeRegion::Tau(), VisibilityTester::Transmittance(), VisibilityTester::Unoccluded(), Scene::volumeRegion, and Spectrum::y().
Member Data Documentation
float SingleScattering::stepSize [private]
Definition at line 39 of file single.cpp.
Referenced by CreateVolumeIntegrator(), Li(), SingleScattering(), and Transmittance().
int SingleScattering::tauSampleOffset [private]
Definition at line 40 of file single.cpp.
Referenced by RequestSamples(), and Transmittance().
int SingleScattering::scatterSampleOffset [private]
Definition at line 40 of file single.cpp.
Referenced by Li(), and RequestSamples().
The documentation for this class was generated from the following file:
single.cpp