pbrt: KdTreeAccel Class Reference
KdTreeAccel Class Reference
Public Member Functions
KdTreeAccel (const vector< Reference< Primitive > > &p, int icost, int scost, float ebonus, int maxp, int maxDepth)
BBox WorldBound () const
bool CanIntersect () const
~KdTreeAccel ()
void buildTree (int nodeNum, const BBox &bounds, const vector< BBox > &primBounds, int *primNums, int nprims, int depth, BoundEdge *edges[3], int *prims0, int *prims1, int badRefines=0)
bool Intersect (const Ray &ray, Intersection *isect) const
bool IntersectP (const Ray &ray) const
Private Attributes
int isectCost
int traversalCost
int maxPrims
float emptyBonus
u_int nMailboxes
MailboxPrim * mailboxPrims
int curMailboxId
KdAccelNode * nodes
int nAllocedNodes
int nextFreeNode
BBox bounds
MemoryArena arena
Detailed Description
Definition at line 108 of file kdtree.cpp.
Constructor & Destructor Documentation
KdTreeAccel::KdTreeAccel (const vector< Reference< Primitive > > & p, int icost, int scost, float ebonus, int maxp, int maxDepth)
Definition at line 142 of file kdtree.cpp.
References AllocAligned(), bounds, buildTree(), curMailboxId, Primitive::FullyRefine(), Log2Int(), mailboxPrims, nAllocedNodes, nextFreeNode, nMailboxes, Round2Int(), and Union().
KdTreeAccel::~KdTreeAccel ()
Definition at line 191 of file kdtree.cpp.
References FreeAligned(), mailboxPrims, nMailboxes, and nodes.
Member Function Documentation
void KdTreeAccel::buildTree (int nodeNum, const BBox & bounds, const vector< BBox > & primBounds, int * primNums, int nprims, int depth, BoundEdge * edges[3], int * prims0, int * prims1, int badRefines = 0)
Definition at line 197 of file kdtree.cpp.
References KdAccelNode::aboveChild, AllocAligned(), arena, Assert, emptyBonus, BoundEdge::END, FreeAligned(), KdAccelNode::initInterior(), KdAccelNode::initLeaf(), isectCost, mailboxPrims, maxPrims, memcpy(), nAllocedNodes, nextFreeNode, nodes, BBox::pMax, BBox::pMin, BoundEdge::primNum, BoundEdge::START, BoundEdge::t, traversalCost, Vector::x, Vector::y, and Vector::z.
Referenced by KdTreeAccel().
bool KdTreeAccel::CanIntersect () const [inline, virtual]
Reimplemented from Primitive.
Definition at line 115 of file kdtree.cpp.
bool KdTreeAccel::Intersect (const Ray & ray, Intersection * isect) const [virtual]
Implements Primitive.
Definition at line 313 of file kdtree.cpp.
References KdAccelNode::aboveChild, bounds, curMailboxId, Ray::d, BBox::IntersectP(), KdAccelNode::IsLeaf(), MailboxPrim::lastMailboxId, MAX_TODO, Ray::maxt, KdToDo::node, nodes, KdAccelNode::nPrimitives(), Ray::o, KdAccelNode::onePrimitive, MailboxPrim::primitive, KdAccelNode::primitives, KdAccelNode::SplitAxis(), KdAccelNode::SplitPos(), KdToDo::tmax, KdToDo::tmin, Vector::x, Vector::y, and Vector::z.
bool KdTreeAccel::IntersectP (const Ray & ray) const [virtual]
Implements Primitive.
Definition at line 404 of file kdtree.cpp.
References KdAccelNode::aboveChild, bounds, curMailboxId, Ray::d, BBox::IntersectP(), KdAccelNode::IsLeaf(), MailboxPrim::lastMailboxId, MAX_TODO, KdToDo::node, nodes, KdAccelNode::nPrimitives(), Ray::o, KdAccelNode::onePrimitive, MailboxPrim::primitive, KdAccelNode::primitives, KdAccelNode::SplitAxis(), KdAccelNode::SplitPos(), KdToDo::tmax, KdToDo::tmin, Vector::x, Vector::y, and Vector::z.
BBox KdTreeAccel::WorldBound () const [inline, virtual]
Implements Primitive.
Definition at line 114 of file kdtree.cpp.
References bounds.
Member Data Documentation
MemoryArena KdTreeAccel::arena [private]
Definition at line 134 of file kdtree.cpp.
Referenced by buildTree().
BBox KdTreeAccel::bounds [private]
Definition at line 133 of file kdtree.cpp.
Referenced by Intersect(), IntersectP(), KdTreeAccel(), and WorldBound().
int KdTreeAccel::curMailboxId [mutable, private]
Definition at line 130 of file kdtree.cpp.
Referenced by Intersect(), IntersectP(), and KdTreeAccel().
float KdTreeAccel::emptyBonus [private]
Definition at line 127 of file kdtree.cpp.
Referenced by buildTree().
int KdTreeAccel::isectCost [private]
Definition at line 126 of file kdtree.cpp.
Referenced by buildTree().
MailboxPrim* KdTreeAccel::mailboxPrims [private]
Definition at line 129 of file kdtree.cpp.
Referenced by buildTree(), KdTreeAccel(), and ~KdTreeAccel().
int KdTreeAccel::maxPrims [private]
Definition at line 126 of file kdtree.cpp.
Referenced by buildTree().
int KdTreeAccel::nAllocedNodes [private]
Definition at line 132 of file kdtree.cpp.
Referenced by buildTree(), and KdTreeAccel().
int KdTreeAccel::nextFreeNode [private]
Definition at line 132 of file kdtree.cpp.
Referenced by buildTree(), and KdTreeAccel().
u_int KdTreeAccel::nMailboxes [private]
Definition at line 128 of file kdtree.cpp.
Referenced by KdTreeAccel(), and ~KdTreeAccel().
KdAccelNode* KdTreeAccel::nodes [private]
Definition at line 131 of file kdtree.cpp.
Referenced by buildTree(), Intersect(), IntersectP(), and ~KdTreeAccel().
int KdTreeAccel::traversalCost [private]
Definition at line 126 of file kdtree.cpp.
Referenced by buildTree().
The documentation for this class was generated from the following file:
kdtree.cpp