pbrt: TextureMapping3D Class Reference
TextureMapping3D Class Reference
#include <texture.h>
Public Member Functions
virtual ~TextureMapping3D ()
virtual Point Map (const DifferentialGeometry &dg, Vector *dpdx, Vector *dpdy) const =0
Detailed Description
Definition at line 90 of file texture.h.
Constructor & Destructor Documentation
virtual TextureMapping3D::~TextureMapping3D () [inline, virtual]
Definition at line 93 of file texture.h.
Member Function Documentation
virtual Point TextureMapping3D::Map (const DifferentialGeometry & dg, Vector * dpdx, Vector * dpdy) const [pure virtual]
Implemented in IdentityMapping3D.
Referenced by WrinkledTexture< T >::Evaluate(), WindyTexture< T >::Evaluate(), MarbleTexture::Evaluate(), FBmTexture< T >::Evaluate(), and Checkerboard3D< T >::Evaluate().
The documentation for this class was generated from the following file:
texture.h