pbrt: Blinn Class Reference
Blinn Class Reference
#include <reflection.h>
Public Member Functions
Blinn (float e)
float D (const Vector &wh) const
virtual void Sample_f (const Vector &wi, Vector *sampled_f, float u1, float u2, float *pdf) const
virtual float Pdf (const Vector &wi, const Vector &wo) const
Private Attributes
float exponent
Detailed Description
Definition at line 307 of file reflection.h.
Constructor & Destructor Documentation
Blinn::Blinn (float e) [inline]
Definition at line 309 of file reflection.h.
Member Function Documentation
float Blinn::D (const Vector & wh) const [inline, virtual]
Implements MicrofacetDistribution.
Definition at line 311 of file reflection.h.
References CosTheta(), and INV_TWOPI.
void Blinn::Sample_f (const Vector & wi, Vector * sampled_f, float u1, float u2, float * pdf) const [virtual]
Implements MicrofacetDistribution.
Definition at line 243 of file reflection.cpp.
References Dot(), exponent, M_PI, SameHemisphere(), SphericalDirection(), and Vector::z.
float Blinn::Pdf (const Vector & wi, const Vector & wo) const [virtual]
Implements MicrofacetDistribution.
Definition at line 259 of file reflection.cpp.
References Dot(), exponent, M_PI, Normalize(), and Vector::z.
Member Data Documentation
float Blinn::exponent [private]
Definition at line 320 of file reflection.h.
Referenced by Pdf(), and Sample_f().
The documentation for this class was generated from the following files:
reflection.h
reflection.cpp