pbrt: TextureParams Class Reference
TextureParams Class Reference
#include <paramset.h>
Public Member Functions
TextureParams (const ParamSet &geomp, const ParamSet &matp, map< string, Reference< Texture< float > > > &ft, map< string, Reference< Texture< Spectrum > > > &st)
Reference< Texture< Spectrum > > GetSpectrumTexture (const string &name, const Spectrum &def) const
Reference< Texture< float > > GetFloatTexture (const string &name, float def) const
float FindFloat (const string &n, float d) const
string FindString (const string &n) const
int FindInt (const string &n, int d) const
bool FindBool (const string &n, bool d) const
Point FindPoint (const string &n, const Point &d) const
Vector FindVector (const string &n, const Vector &d) const
Normal FindNormal (const string &n, const Normal &d) const
Spectrum FindSpectrum (const string &n, const Spectrum &d) const
void ReportUnused () const
const ParamSet & GetGeomParams () const
const ParamSet & GetMaterialParams () const
Private Attributes
const ParamSet & geomParams
const ParamSet & materialParams
map< string, Reference
< Texture< float > > > & floatTextures
map< string, Reference
< Texture< Spectrum > > > & spectrumTextures
Detailed Description
Definition at line 162 of file paramset.h.
Constructor & Destructor Documentation
TextureParams::TextureParams (const ParamSet & geomp, const ParamSet & matp, map< string, Reference< Texture< float > > > & ft, map< string, Reference< Texture< Spectrum > > > & st) [inline]
Definition at line 165 of file paramset.h.
Member Function Documentation
bool TextureParams::FindBool (const string & n, bool d) const [inline]
Definition at line 187 of file paramset.h.
Referenced by CreateFloatTexture(), and CreateSpectrumTexture().
float TextureParams::FindFloat (const string & n, float d) const [inline]
Definition at line 177 of file paramset.h.
Referenced by CreateFloatTexture(), and CreateSpectrumTexture().
int TextureParams::FindInt (const string & n, int d) const [inline]
Definition at line 184 of file paramset.h.
Referenced by CreateFloatTexture(), and CreateSpectrumTexture().
Normal TextureParams::FindNormal (const string & n, const Normal & d) const [inline]
Definition at line 196 of file paramset.h.
Point TextureParams::FindPoint (const string & n, const Point & d) const [inline]
Definition at line 190 of file paramset.h.
Spectrum TextureParams::FindSpectrum (const string & n, const Spectrum & d) const [inline]
Definition at line 199 of file paramset.h.
Referenced by CreateSpectrumTexture().
string TextureParams::FindString (const string & n) const [inline]
Definition at line 181 of file paramset.h.
Referenced by CreateFloatTexture(), and CreateSpectrumTexture().
Vector TextureParams::FindVector (const string & n, const Vector & d) const [inline]
Definition at line 193 of file paramset.h.
Referenced by CreateFloatTexture(), and CreateSpectrumTexture().
Reference< Texture< float > > TextureParams::GetFloatTexture (const string & name, float def) const
Definition at line 452 of file paramset.cpp.
References Error(), ParamSet::FindOneFloat(), ParamSet::FindTexture(), floatTextures, geomParams, and materialParams.
Referenced by CreateFloatTexture(), CreateMaterial(), and CreateSpectrumTexture().
const ParamSet& TextureParams::GetGeomParams () const [inline]
Definition at line 206 of file paramset.h.
const ParamSet& TextureParams::GetMaterialParams () const [inline]
Definition at line 207 of file paramset.h.
Reference< Texture< Spectrum > > TextureParams::GetSpectrumTexture (const string & name, const Spectrum & def) const
Definition at line 436 of file paramset.cpp.
References Error(), ParamSet::FindOneSpectrum(), ParamSet::FindTexture(), geomParams, materialParams, and spectrumTextures.
Referenced by CreateMaterial(), and CreateSpectrumTexture().
void TextureParams::ReportUnused () const [inline]
Definition at line 202 of file paramset.h.
Referenced by MakeFloatTexture(), MakeMaterial(), and MakeSpectrumTexture().
Member Data Documentation
map<string, Reference<Texture<float> > >& TextureParams::floatTextures [private]
Definition at line 212 of file paramset.h.
Referenced by GetFloatTexture().
const ParamSet& TextureParams::geomParams [private]
Definition at line 210 of file paramset.h.
Referenced by GetFloatTexture(), and GetSpectrumTexture().
const ParamSet & TextureParams::materialParams [private]
Definition at line 210 of file paramset.h.
Referenced by GetFloatTexture(), and GetSpectrumTexture().
map<string, Reference<Texture<Spectrum> > >& TextureParams::spectrumTextures [private]
Definition at line 214 of file paramset.h.
Referenced by GetSpectrumTexture().
The documentation for this class was generated from the following files:
paramset.h
paramset.cpp