pbrt: WhittedIntegrator Class Reference
WhittedIntegrator Class Reference
Public Member Functions
Spectrum Li (const Scene *scene, const RayDifferential &ray, const Sample *sample, float *alpha) const
WhittedIntegrator (int md)
Private Attributes
int maxDepth
int rayDepth
Detailed Description
Definition at line 29 of file whitted.cpp.
Constructor & Destructor Documentation
WhittedIntegrator::WhittedIntegrator (int md) [inline]
Definition at line 34 of file whitted.cpp.
References maxDepth, and rayDepth.
Member Function Documentation
Spectrum WhittedIntegrator::Li (const Scene * scene, const RayDifferential & ray, const Sample * sample, float * alpha) const [virtual]
Implements Integrator.
Definition at line 44 of file whitted.cpp.
References AbsDot(), Spectrum::Black(), BSDF_REFLECTION, BSDF_SPECULAR, BSDF_TRANSMISSION, Ray::d, Intersection::dg, BSDF::dgShading, DifferentialGeometry::dndu, DifferentialGeometry::dndv, Dot(), DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, BSDF::eta, BSDF::f(), Intersection::GetBSDF(), RayDifferential::hasDifferentials, Scene::Intersect(), Intersection::Le(), Scene::Li(), Scene::lights, maxDepth, DifferentialGeometry::nn, Ray::o, DifferentialGeometry::p, rayDepth, RayDifferential::rx, RayDifferential::ry, BSDF::Sample_f(), VisibilityTester::Transmittance(), and VisibilityTester::Unoccluded().
Member Data Documentation
int WhittedIntegrator::maxDepth [private]
Definition at line 40 of file whitted.cpp.
Referenced by Li(), and WhittedIntegrator().
int WhittedIntegrator::rayDepth [mutable, private]
Definition at line 41 of file whitted.cpp.
Referenced by Li(), and WhittedIntegrator().
The documentation for this class was generated from the following file:
whitted.cpp