pbrt: BlockedArray< T, logBlockSize > Class Template Reference
BlockedArray< T, logBlockSize > Class Template Reference
#include <pbrt.h>
Public Member Functions
BlockedArray (int nu, int nv, const T *d=NULL)
int BlockSize () const
int RoundUp (int x) const
int uSize () const
int vSize () const
~BlockedArray ()
int Block (int a) const
int Offset (int a) const
T & operator() (int u, int v)
const T & operator() (int u, int v) const
void GetLinearArray (T *a) const
BlockedArray (int nu, int nv, const T *d=NULL)
int BlockSize () const
int RoundUp (int x) const
int uSize () const
int vSize () const
~BlockedArray ()
int Block (int a) const
int Offset (int a) const
T & operator() (int u, int v)
const T & operator() (int u, int v) const
void GetLinearArray (T *a) const
Private Attributes
T * data
int uRes
int vRes
int uBlocks
Detailed Description
template<class T, int logBlockSize>
class BlockedArray< T, logBlockSize >
Definition at line 442 of file pbrt.h.
Constructor & Destructor Documentation
template<class T, int logBlockSize> BlockedArray< T, logBlockSize >::BlockedArray (int nu, int nv, const T * d = NULL) [inline]
Definition at line 445 of file pbrt.h.
template<class T, int logBlockSize> BlockedArray< T, logBlockSize >::~BlockedArray () [inline]
Definition at line 464 of file pbrt.h.
template<class T, int logBlockSize> BlockedArray< T, logBlockSize >::BlockedArray (int nu, int nv, const T * d = NULL) [inline]
Definition at line 446 of file pbrtlex.l.
template<class T, int logBlockSize> BlockedArray< T, logBlockSize >::~BlockedArray () [inline]
Definition at line 465 of file pbrtlex.l.
Member Function Documentation
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::BlockSize () const [inline]
Definition at line 458 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::Offset(), BlockedArray< Spectrum >::operator()(), and BlockedArray< Spectrum >::RoundUp().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::RoundUp (int x) const [inline]
Definition at line 459 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::BlockedArray().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::uSize () const [inline]
Definition at line 462 of file pbrt.h.
Referenced by MIPMap< T >::EWA(), MIPMap< T >::texel(), and MIPMap< T >::triangle().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::vSize () const [inline]
Definition at line 463 of file pbrt.h.
Referenced by MIPMap< T >::EWA(), MIPMap< T >::texel(), and MIPMap< T >::triangle().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::Block (int a) const [inline]
Definition at line 469 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::operator()().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::Offset (int a) const [inline]
Definition at line 470 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::operator()().
template<class T, int logBlockSize> T& BlockedArray< T, logBlockSize >::operator() (int u, int v) [inline]
Definition at line 471 of file pbrt.h.
template<class T, int logBlockSize> const T& BlockedArray< T, logBlockSize >::operator() (int u, int v) const [inline]
Definition at line 479 of file pbrt.h.
template<class T, int logBlockSize> void BlockedArray< T, logBlockSize >::GetLinearArray (T * a) const [inline]
Definition at line 486 of file pbrt.h.
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::BlockSize () const [inline]
Definition at line 459 of file pbrtlex.l.
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::RoundUp (int x) const [inline]
Definition at line 460 of file pbrtlex.l.
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::uSize () const [inline]
Definition at line 463 of file pbrtlex.l.
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::vSize () const [inline]
Definition at line 464 of file pbrtlex.l.
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::Block (int a) const [inline]
Definition at line 470 of file pbrtlex.l.
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::Offset (int a) const [inline]
Definition at line 471 of file pbrtlex.l.
template<class T, int logBlockSize> T& BlockedArray< T, logBlockSize >::operator() (int u, int v) [inline]
Definition at line 472 of file pbrtlex.l.
template<class T, int logBlockSize> const T& BlockedArray< T, logBlockSize >::operator() (int u, int v) const [inline]
Definition at line 480 of file pbrtlex.l.
template<class T, int logBlockSize> void BlockedArray< T, logBlockSize >::GetLinearArray (T * a) const [inline]
Definition at line 487 of file pbrtlex.l.
Member Data Documentation
template<class T, int logBlockSize> T * BlockedArray< T, logBlockSize >::data [private]
Definition at line 493 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::BlockedArray(), BlockedArray< Spectrum >::operator()(), and BlockedArray< Spectrum >::~BlockedArray().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::uRes [private]
Definition at line 494 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::BlockedArray(), BlockedArray< Spectrum >::GetLinearArray(), BlockedArray< Spectrum >::uSize(), and BlockedArray< Spectrum >::~BlockedArray().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::vRes [private]
Definition at line 494 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::BlockedArray(), BlockedArray< Spectrum >::GetLinearArray(), BlockedArray< Spectrum >::vSize(), and BlockedArray< Spectrum >::~BlockedArray().
template<class T, int logBlockSize> int BlockedArray< T, logBlockSize >::uBlocks [private]
Definition at line 494 of file pbrt.h.
Referenced by BlockedArray< Spectrum >::BlockedArray(), and BlockedArray< Spectrum >::operator()().
The documentation for this class was generated from the following file:
pbrt.h