pbrt: VolumeRegion Class Reference
VolumeRegion Class Reference
#include <volume.h>
Public Member Functions
virtual ~VolumeRegion ()
virtual BBox WorldBound () const =0
virtual bool IntersectP (const Ray &ray, float *t0, float *t1) const =0
virtual Spectrum sigma_a (const Point &, const Vector &) const =0
virtual Spectrum sigma_s (const Point &, const Vector &) const =0
virtual Spectrum Lve (const Point &, const Vector &) const =0
virtual float p (const Point &, const Vector &, const Vector &) const =0
virtual Spectrum sigma_t (const Point &, const Vector &) const
virtual Spectrum Tau (const Ray &ray, float step=1.f, float offset=0.5) const =0
Detailed Description
Definition at line 43 of file volume.h.
Constructor & Destructor Documentation
virtual VolumeRegion::~VolumeRegion () [inline, virtual]
Definition at line 46 of file volume.h.
Member Function Documentation
virtual bool VolumeRegion::IntersectP (const Ray & ray, float * t0, float * t1) const [pure virtual]
Implemented in AggregateVolume, ExponentialDensity, HomogeneousVolume, and VolumeGrid.
Referenced by SingleScattering::Li(), EmissionIntegrator::Li(), and DensityRegion::Tau().
virtual Spectrum VolumeRegion::Lve (const Point & , const Vector &) const [pure virtual]
Implemented in DensityRegion, AggregateVolume, and HomogeneousVolume.
Referenced by SingleScattering::Li(), and EmissionIntegrator::Li().
virtual float VolumeRegion::p (const Point & , const Vector & , const Vector &) const [pure virtual]
Implemented in DensityRegion, AggregateVolume, and HomogeneousVolume.
Referenced by SingleScattering::Li().
virtual Spectrum VolumeRegion::sigma_a (const Point & , const Vector &) const [pure virtual]
Implemented in DensityRegion, AggregateVolume, and HomogeneousVolume.
Referenced by sigma_t().
virtual Spectrum VolumeRegion::sigma_s (const Point & , const Vector &) const [pure virtual]
Implemented in DensityRegion, AggregateVolume, and HomogeneousVolume.
Referenced by SingleScattering::Li(), and sigma_t().
Spectrum VolumeRegion::sigma_t (const Point & p, const Vector & w) const [virtual]
Reimplemented in DensityRegion, AggregateVolume, and HomogeneousVolume.
Definition at line 57 of file volume.cpp.
References sigma_a(), and sigma_s().
virtual Spectrum VolumeRegion::Tau (const Ray & ray, float step = 1.f, float offset = 0.5) const [pure virtual]
Implemented in DensityRegion, AggregateVolume, and HomogeneousVolume.
Referenced by SingleScattering::Li(), EmissionIntegrator::Li(), SingleScattering::Transmittance(), and EmissionIntegrator::Transmittance().
virtual BBox VolumeRegion::WorldBound () const [pure virtual]
Implemented in AggregateVolume, ExponentialDensity, HomogeneousVolume, and VolumeGrid.
Referenced by Scene::Scene().
The documentation for this class was generated from the following files:
volume.h
volume.cpp