pbrt: TextureMapping2D Class Reference
TextureMapping2D Class Reference
#include <texture.h>
Public Member Functions
virtual ~TextureMapping2D ()
virtual void Map (const DifferentialGeometry &dg, float *s, float *t, float *dsdx, float *dtdx, float *dsdy, float *dtdy) const =0
Detailed Description
Definition at line 32 of file texture.h.
Constructor & Destructor Documentation
virtual TextureMapping2D::~TextureMapping2D () [inline, virtual]
Definition at line 35 of file texture.h.
Member Function Documentation
virtual void TextureMapping2D::Map (const DifferentialGeometry & dg, float * s, float * t, float * dsdx, float * dtdx, float * dsdy, float * dtdy) const [pure virtual]
Implemented in UVMapping2D, SphericalMapping2D, CylindricalMapping2D, and PlanarMapping2D.
Referenced by UVTexture::Evaluate(), ImageTexture< T >::Evaluate(), DotsTexture< T >::Evaluate(), Checkerboard2D< T >::Evaluate(), and BilerpTexture< T >::Evaluate().
The documentation for this class was generated from the following file:
texture.h