pbrt: Sphere Class Reference
Sphere Class Reference
Public Member Functions
Sphere (const Transform &o2w, bool ro, float rad, float zmin, float zmax, float phiMax)
BBox ObjectBound () const
bool Intersect (const Ray &ray, float *tHit, DifferentialGeometry *dg) const
bool IntersectP (const Ray &ray) const
float Area () const
Point Sample (float u1, float u2, Normal *ns) const
Point Sample (const Point &p, float u1, float u2, Normal *ns) const
float Pdf (const Point &p, const Vector &wi) const
Private Attributes
float radius
float phiMax
float zmin
float zmax
float thetaMin
float thetaMax
Detailed Description
Definition at line 28 of file sphere.cpp.
Constructor & Destructor Documentation
Sphere::Sphere (const Transform & o2w, bool ro, float rad, float zmin, float zmax, float phiMax)
Definition at line 90 of file sphere.cpp.
References Clamp(), phiMax, Radians(), radius, thetaMax, thetaMin, zmax, and zmin.
Referenced by CreateShape().
Member Function Documentation
BBox Sphere::ObjectBound () const [virtual]
Implements Shape.
Definition at line 100 of file sphere.cpp.
References radius, zmax, and zmin.
bool Sphere::Intersect (const Ray & ray, float * tHit, DifferentialGeometry * dg) const [virtual]
Reimplemented from Shape.
Definition at line 104 of file sphere.cpp.
References Cross(), Ray::d, Dot(), M_PI, Ray::maxt, Ray::mint, N, Normalize(), Ray::o, Shape::ObjectToWorld, phiMax, Quadratic(), radius, thetaMax, thetaMin, Shape::WorldToObject, Point::x, Vector::x, Point::y, Vector::y, Point::z, Vector::z, zmax, and zmin.
Referenced by Sample().
bool Sphere::IntersectP (const Ray & ray) const [virtual]
Reimplemented from Shape.
Definition at line 208 of file sphere.cpp.
References Ray::d, M_PI, Ray::maxt, Ray::mint, Ray::o, phiMax, Quadratic(), radius, Shape::WorldToObject, Point::x, Vector::x, Point::y, Vector::y, Point::z, Vector::z, zmax, and zmin.
float Sphere::Area () const [virtual]
Reimplemented from Shape.
Definition at line 251 of file sphere.cpp.
References phiMax, radius, zmax, and zmin.
Point Sphere::Sample (float u1, float u2, Normal * ns) const [inline, virtual]
Reimplemented from Shape.
Definition at line 38 of file sphere.cpp.
References Normalize(), Shape::ObjectToWorld, radius, Shape::reverseOrientation, UniformSampleSphere(), Point::x, Point::y, and Point::z.
Referenced by Sample().
Point Sphere::Sample (const Point & p, float u1, float u2, Normal * ns) const [inline, virtual]
Reimplemented from Shape.
Definition at line 45 of file sphere.cpp.
References CoordinateSystem(), DistanceSquared(), Intersect(), Normalize(), Shape::ObjectToWorld, radius, Shape::reverseOrientation, Sample(), and UniformSampleCone().
float Sphere::Pdf (const Point & p, const Vector & wi) const [inline, virtual]
Reimplemented from Shape.
Definition at line 72 of file sphere.cpp.
References DistanceSquared(), Shape::ObjectToWorld, Shape::Pdf(), radius, and UniformConePdf().
Member Data Documentation
float Sphere::radius [private]
Definition at line 84 of file sphere.cpp.
Referenced by Area(), CreateShape(), Intersect(), IntersectP(), ObjectBound(), Pdf(), Sample(), and Sphere().
float Sphere::phiMax [private]
Definition at line 85 of file sphere.cpp.
Referenced by Area(), Intersect(), IntersectP(), and Sphere().
float Sphere::zmin [private]
Definition at line 86 of file sphere.cpp.
Referenced by Area(), CreateShape(), Intersect(), IntersectP(), ObjectBound(), and Sphere().
float Sphere::zmax [private]
Definition at line 86 of file sphere.cpp.
Referenced by Area(), CreateShape(), Intersect(), IntersectP(), ObjectBound(), and Sphere().
float Sphere::thetaMin [private]
Definition at line 87 of file sphere.cpp.
Referenced by Intersect(), and Sphere().
float Sphere::thetaMax [private]
Definition at line 87 of file sphere.cpp.
Referenced by Intersect(), and Sphere().
The documentation for this class was generated from the following file:
sphere.cpp