pbrt: Checkerboard2D< T > Class Template Reference
Checkerboard2D< T > Class Template Reference
Public Member Functions
Checkerboard2D (TextureMapping2D *m, Reference< Texture< T > > c1, Reference< Texture< T > > c2, const string &aa)
~Checkerboard2D ()
T Evaluate (const DifferentialGeometry &dg) const
Private Attributes
Reference< Texture< T > > tex1
Reference< Texture< T > > tex2
TextureMapping2D * mapping
Detailed Description
template<class T>
class Checkerboard2D< T >
Definition at line 33 of file checkerboard.cpp.
Constructor & Destructor Documentation
template<class T> Checkerboard2D< T >::Checkerboard2D (TextureMapping2D * m, Reference< Texture< T > > c1, Reference< Texture< T > > c2, const string & aa) [inline]
Definition at line 36 of file checkerboard.cpp.
References aaMethod, CLOSEDFORM, Checkerboard2D< T >::mapping, NONE, SUPERSAMPLE, Checkerboard2D< T >::tex1, Checkerboard2D< T >::tex2, and Warning().
template<class T> Checkerboard2D< T >::~Checkerboard2D () [inline]
Definition at line 54 of file checkerboard.cpp.
References Checkerboard2D< T >::mapping.
Member Function Documentation
template<class T> T Checkerboard2D< T >::Evaluate (const DifferentialGeometry & dg) const [inline, virtual]
Implements Texture< T >.
Definition at line 57 of file checkerboard.cpp.
References aaMethod, BUMPINT, CLOSEDFORM, DifferentialGeometry::dpdx, DifferentialGeometry::dpdy, DifferentialGeometry::dudx, DifferentialGeometry::dudy, DifferentialGeometry::dvdx, DifferentialGeometry::dvdy, Floor2Int(), TextureMapping2D::Map(), Checkerboard2D< T >::mapping, N_SAMPLES, DifferentialGeometry::p, SQRT_SAMPLES, StratifiedSample2D(), SUPERSAMPLE, Checkerboard2D< T >::tex1, Checkerboard2D< T >::tex2, DifferentialGeometry::u, and DifferentialGeometry::v.
Member Data Documentation
template<class T> Reference<Texture<T> > Checkerboard2D< T >::tex1 [private]
Definition at line 126 of file checkerboard.cpp.
Referenced by Checkerboard2D< T >::Checkerboard2D(), and Checkerboard2D< T >::Evaluate().
template<class T> Reference<Texture<T> > Checkerboard2D< T >::tex2 [private]
Definition at line 126 of file checkerboard.cpp.
Referenced by Checkerboard2D< T >::Checkerboard2D(), and Checkerboard2D< T >::Evaluate().
template<class T> TextureMapping2D* Checkerboard2D< T >::mapping [private]
Definition at line 127 of file checkerboard.cpp.
Referenced by Checkerboard2D< T >::Checkerboard2D(), Checkerboard2D< T >::Evaluate(), and Checkerboard2D< T >::~Checkerboard2D().
The documentation for this class was generated from the following file:
checkerboard.cpp