pbrt: samplepat.cpp File Reference
samplepat.cpp File Reference
#include "pbrt.h"
#include "sampling.h"
Defines
#define SQRT_SAMPLE_TABLE_SIZE 64
#define SAMPLE_TABLE_SIZE
Functions
static void addSampleToGrid (float sample[][2], int sampleNum, SampleGrid *grid)
float Wrapped1DDist (float a, float b)
void BestCandidate2D (float table[][2], int count, SampleGrid *grid=NULL)
static void Redistribute2D (float samples[][2], SampleGrid &pixelGrid)
int main ()
Variables
int line_num = 0
string current_file
static float imageSamples [SAMPLE_TABLE_SIZE][2]
static float timeSamples [SAMPLE_TABLE_SIZE]
static float lensSamples [SAMPLE_TABLE_SIZE][2]
Define Documentation
#define SAMPLE_TABLE_SIZE
Value:
(SQRT_SAMPLE_TABLE_SIZE * \
                           SQRT_SAMPLE_TABLE_SIZE)
Definition at line 29 of file core/samplepat.cpp.
Referenced by BestCandidateSampler::BestCandidateSampler(), BestCandidateSampler::GetNextSample(), main(), and Redistribute2D().
#define SQRT_SAMPLE_TABLE_SIZE 64
Definition at line 28 of file core/samplepat.cpp.
Referenced by BestCandidateSampler::BestCandidateSampler(), and main().
Function Documentation
static void addSampleToGrid (float sample[][2], int sampleNum, SampleGrid * grid) [static]
Definition at line 39 of file core/samplepat.cpp.
References GRID.
Referenced by BestCandidate2D().
void BestCandidate2D (float table[][2], int count, SampleGrid * grid = NULL)
Definition at line 134 of file core/samplepat.cpp.
References addSampleToGrid(), BC_GRID_SIZE, ProgressReporter::Done(), GRID, INFINITY, RandomFloat(), ProgressReporter::Update(), and Wrapped1DDist().
Referenced by main().
int main ()
Definition at line 55 of file core/samplepat.cpp.
References Assert, BC_GRID_SIZE, BestCandidate2D(), ProgressReporter::Done(), GRID, imageSamples, INFINITY, lensSamples, RandomFloat(), Redistribute2D(), SAMPLE_TABLE_SIZE, Severe(), SQRT_SAMPLE_TABLE_SIZE, timeSamples, ProgressReporter::Update(), and Wrapped1DDist().
static void Redistribute2D (float samples[][2], SampleGrid & pixelGrid) [static]
Definition at line 190 of file core/samplepat.cpp.
References Assert, BC_GRID_SIZE, ProgressReporter::Done(), GRID, imageSamples, INFINITY, SAMPLE_TABLE_SIZE, ProgressReporter::Update(), and Wrapped1DDist().
Referenced by main().
float Wrapped1DDist (float a, float b) [inline]
Definition at line 45 of file core/samplepat.cpp.
Referenced by BestCandidate2D(), main(), and Redistribute2D().
Variable Documentation
string current_file
Definition at line 33 of file core/samplepat.cpp.
Referenced by include_pop(), include_push(), ParseFile(), and processError().
float imageSamples[SAMPLE_TABLE_SIZE][2] [static]
Definition at line 35 of file core/samplepat.cpp.
Referenced by main(), and Redistribute2D().
float lensSamples[SAMPLE_TABLE_SIZE][2] [static]
Definition at line 37 of file core/samplepat.cpp.
Referenced by main().
int line_num = 0
Definition at line 32 of file core/samplepat.cpp.
Referenced by ParseFile(), and processError().
float timeSamples[SAMPLE_TABLE_SIZE] [static]
Definition at line 36 of file core/samplepat.cpp.
Referenced by main().