pbrt: debug.cpp File Reference
debug.cpp File Reference
#include "pbrt.h"
#include "transport.h"
#include "scene.h"
Classes
class DebugIntegrator
Enumerations
enum DebugVariable {
DEBUG_U, DEBUG_V, DEBUG_GEOM_NORMAL_X, DEBUG_GEOM_NORMAL_Y,
DEBUG_GEOM_NORMAL_Z, DEBUG_SHAD_NORMAL_X, DEBUG_SHAD_NORMAL_Y, DEBUG_SHAD_NORMAL_Z,
DEBUG_ONE, DEBUG_ZERO, DEBUG_HIT_SOMETHING
}
Functions
DLLEXPORT SurfaceIntegrator * CreateSurfaceIntegrator (const ParamSet &params)
Enumeration Type Documentation
enum DebugVariable
Enumerator:
DEBUG_U
DEBUG_V
DEBUG_GEOM_NORMAL_X
DEBUG_GEOM_NORMAL_Y
DEBUG_GEOM_NORMAL_Z
DEBUG_SHAD_NORMAL_X
DEBUG_SHAD_NORMAL_Y
DEBUG_SHAD_NORMAL_Z
DEBUG_ONE
DEBUG_ZERO
DEBUG_HIT_SOMETHING
Definition at line 33 of file debug.cpp.
Function Documentation
DLLEXPORT SurfaceIntegrator* CreateSurfaceIntegrator (const ParamSet & params)
Definition at line 135 of file debug.cpp.
References DEBUG_GEOM_NORMAL_X, DEBUG_GEOM_NORMAL_Y, DEBUG_GEOM_NORMAL_Z, DEBUG_HIT_SOMETHING, DEBUG_ONE, DEBUG_SHAD_NORMAL_X, DEBUG_SHAD_NORMAL_Y, DEBUG_SHAD_NORMAL_Z, DEBUG_U, DEBUG_V, DEBUG_ZERO, DebugIntegrator::DebugIntegrator(), Error(), and ParamSet::FindOneString().