pbrt: directlighting.cpp File Reference
directlighting.cpp File Reference
#include "pbrt.h"
#include "transport.h"
#include "scene.h"
Classes
class DirectLighting
Enumerations
enum LightStrategy { SAMPLE_ALL_UNIFORM, SAMPLE_ONE_UNIFORM, SAMPLE_ONE_WEIGHTED }
Functions
DLLEXPORT SurfaceIntegrator * CreateSurfaceIntegrator (const ParamSet &params)
Enumeration Type Documentation
enum LightStrategy
Enumerator:
SAMPLE_ALL_UNIFORM
SAMPLE_ONE_UNIFORM
SAMPLE_ONE_WEIGHTED
Definition at line 29 of file directlighting.cpp.
Function Documentation
DLLEXPORT SurfaceIntegrator* CreateSurfaceIntegrator (const ParamSet & params)
Definition at line 195 of file directlighting.cpp.
References DirectLighting::DirectLighting(), ParamSet::FindOneInt(), ParamSet::FindOneString(), DirectLighting::maxDepth, SAMPLE_ALL_UNIFORM, SAMPLE_ONE_UNIFORM, SAMPLE_ONE_WEIGHTED, DirectLighting::strategy, and Warning().