pbrt: distant.cpp File Reference
distant.cpp File Reference
#include "pbrt.h"
#include "light.h"
#include "shape.h"
#include "scene.h"
Classes
class DistantLight
Functions
DLLEXPORT Light * CreateLight (const Transform &light2world, const ParamSet &paramSet)
Function Documentation
DLLEXPORT Light* CreateLight (const Transform & light2world, const ParamSet & paramSet)
Definition at line 94 of file distant.cpp.
References DistantLight::DistantLight(), ParamSet::FindOnePoint(), ParamSet::FindOneSpectrum(), and DistantLight::L.