pbrt: dynload.h File Reference
dynload.h File Reference
#include "pbrt.h"
Functions
COREDLL void UpdatePluginPath (const string &newpath)
COREDLL Reference< Shape > MakeShape (const string &name, const Transform &object2world, bool reverseOrientation, const ParamSet &paramSet)
COREDLL Reference< Material > MakeMaterial (const string &name, const Transform &mtl2world, const TextureParams &mp)
COREDLL Reference< Texture
< float > > MakeFloatTexture (const string &name, const Transform &tex2world, const TextureParams &tp)
COREDLL Reference< Texture
< Spectrum > > MakeSpectrumTexture (const string &name, const Transform &tex2world, const TextureParams &tp)
COREDLL Light * MakeLight (const string &name, const Transform &light2world, const ParamSet &paramSet)
COREDLL AreaLight * MakeAreaLight (const string &name, const Transform &light2world, const ParamSet &paramSet, const Reference< Shape > &shape)
COREDLL VolumeRegion * MakeVolumeRegion (const string &name, const Transform &light2world, const ParamSet &paramSet)
COREDLL SurfaceIntegrator * MakeSurfaceIntegrator (const string &name, const ParamSet &paramSet)
COREDLL VolumeIntegrator * MakeVolumeIntegrator (const string &name, const ParamSet &paramSet)
COREDLL Primitive * MakeAccelerator (const string &name, const vector< Reference< Primitive > > &prims, const ParamSet &paramSet)
COREDLL Camera * MakeCamera (const string &name, const ParamSet &paramSet, const Transform &world2cam, Film *film)
COREDLL Sampler * MakeSampler (const string &name, const ParamSet &paramSet, const Film *film)
COREDLL Filter * MakeFilter (const string &name, const ParamSet &paramSet)
COREDLL ToneMap * MakeToneMap (const string &name, const ParamSet &paramSet)
COREDLL Film * MakeFilm (const string &name, const ParamSet &paramSet, Filter *filt)
Function Documentation
COREDLL Primitive* MakeAccelerator (const string & name, const vector< Reference< Primitive > > & prims, const ParamSet & paramSet)
Definition at line 398 of file dynload.cpp.
References acceleratorPlugins, AcceleratorPlugin::CreateAccelerator, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene(), and pbrtObjectInstance().
COREDLL AreaLight* MakeAreaLight (const string & name, const Transform & light2world, const ParamSet & paramSet, const Reference< Shape > & shape)
Definition at line 353 of file dynload.cpp.
References arealightPlugins, AreaLightPlugin::CreateAreaLight, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by pbrtShape().
COREDLL Camera* MakeCamera (const string & name, const ParamSet & paramSet, const Transform & world2cam, Film * film)
Definition at line 410 of file dynload.cpp.
References cameraPlugins, CameraPlugin::CreateCamera, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene().
COREDLL Film* MakeFilm (const string & name, const ParamSet & paramSet, Filter * filt)
Definition at line 451 of file dynload.cpp.
References FilmPlugin::CreateFilm, filmPlugins, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene().
COREDLL Filter* MakeFilter (const string & name, const ParamSet & paramSet)
Definition at line 431 of file dynload.cpp.
References FilterPlugin::CreateFilter, filterPlugins, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene().
COREDLL Reference<Texture<float> > MakeFloatTexture (const string & name, const Transform & tex2world, const TextureParams & tp)
Definition at line 319 of file dynload.cpp.
References TexturePlugin::CreateFloatTex, PluginSearchPath, TextureParams::ReportUnused(), and texturePlugins.
Referenced by pbrtTexture().
COREDLL Light* MakeLight (const string & name, const Transform & light2world, const ParamSet & paramSet)
Definition at line 343 of file dynload.cpp.
References LightPlugin::CreateLight, lightPlugins, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by pbrtLightSource().
COREDLL Reference<Material> MakeMaterial (const string & name, const Transform & mtl2world, const TextureParams & mp)
Definition at line 306 of file dynload.cpp.
References MaterialPlugin::CreateMaterial, materialPlugins, PluginSearchPath, and TextureParams::ReportUnused().
Referenced by pbrtShape().
COREDLL Sampler* MakeSampler (const string & name, const ParamSet & paramSet, const Film * film)
Definition at line 421 of file dynload.cpp.
References SamplerPlugin::CreateSampler, PluginSearchPath, ParamSet::ReportUnused(), and samplerPlugins.
Referenced by RenderOptions::MakeScene().
COREDLL Reference<Shape> MakeShape (const string & name, const Transform & object2world, bool reverseOrientation, const ParamSet & paramSet)
Definition at line 272 of file dynload.cpp.
References ShapePlugin::CreateShape, PluginSearchPath, and shapePlugins.
Referenced by pbrtShape(), NURBS::Refine(), LoopSubdiv::Refine(), and Heightfield::Refine().
COREDLL Reference<Texture<Spectrum> > MakeSpectrumTexture (const string & name, const Transform & tex2world, const TextureParams & tp)
Definition at line 331 of file dynload.cpp.
References TexturePlugin::CreateSpectrumTex, PluginSearchPath, TextureParams::ReportUnused(), and texturePlugins.
Referenced by pbrtTexture().
COREDLL SurfaceIntegrator* MakeSurfaceIntegrator (const string & name, const ParamSet & paramSet)
Definition at line 376 of file dynload.cpp.
References SurfaceIntegratorPlugin::CreateSurfaceIntegrator, PluginSearchPath, ParamSet::ReportUnused(), and surf_integratorPlugins.
Referenced by RenderOptions::MakeScene().
COREDLL ToneMap* MakeToneMap (const string & name, const ParamSet & paramSet)
Definition at line 441 of file dynload.cpp.
References ToneMapPlugin::CreateToneMap, PluginSearchPath, ParamSet::ReportUnused(), and tonemapPlugins.
Referenced by ApplyImagingPipeline().
COREDLL VolumeIntegrator* MakeVolumeIntegrator (const string & name, const ParamSet & paramSet)
Definition at line 387 of file dynload.cpp.
References VolumeIntegratorPlugin::CreateVolumeIntegrator, PluginSearchPath, ParamSet::ReportUnused(), and vol_integratorPlugins.
Referenced by RenderOptions::MakeScene().
COREDLL VolumeRegion* MakeVolumeRegion (const string & name, const Transform & light2world, const ParamSet & paramSet)
Definition at line 365 of file dynload.cpp.
References VolumeRegionPlugin::CreateVolumeRegion, PluginSearchPath, ParamSet::ReportUnused(), and volumePlugins.
Referenced by pbrtVolume().
COREDLL void UpdatePluginPath (const string & newpath)
Definition at line 262 of file dynload.cpp.
References PluginSearchPath.
Referenced by pbrtSearchPath(), and RenderOptions::RenderOptions().