pbrt: dynload.cpp File Reference
dynload.cpp File Reference
#include "dynload.h"
#include "paramset.h"
#include "shape.h"
#include "material.h"
#include <dlfcn.h>
#include <map>
Classes
class Plugin
class ShapePlugin
class MaterialPlugin
class TexturePlugin
class LightPlugin
class VolumeRegionPlugin
class AreaLightPlugin
class SurfaceIntegratorPlugin
class VolumeIntegratorPlugin
class AcceleratorPlugin
class SamplerPlugin
class CameraPlugin
class FilterPlugin
class ToneMapPlugin
class FilmPlugin
Functions
static string SearchPath (const string &searchpath, const string &filename)
template<class D >
D * GetPlugin (const string &name, map< string, D * > &loadedPlugins, const string &searchPath)
COREDLL void UpdatePluginPath (const string &newpath)
COREDLL Reference< Shape > MakeShape (const string &name, const Transform &object2world, bool reverseOrientation, const ParamSet &paramSet)
COREDLL Reference< Material > MakeMaterial (const string &name, const Transform &mtl2world, const TextureParams &mp)
COREDLL Reference< Texture
< float > > MakeFloatTexture (const string &name, const Transform &tex2world, const TextureParams &tp)
COREDLL Reference< Texture
< Spectrum > > MakeSpectrumTexture (const string &name, const Transform &tex2world, const TextureParams &tp)
COREDLL Light * MakeLight (const string &name, const Transform &light2world, const ParamSet &paramSet)
COREDLL AreaLight * MakeAreaLight (const string &name, const Transform &light2world, const ParamSet &paramSet, const Reference< Shape > &shape)
COREDLL VolumeRegion * MakeVolumeRegion (const string &name, const Transform &volume2world, const ParamSet &paramSet)
COREDLL SurfaceIntegrator * MakeSurfaceIntegrator (const string &name, const ParamSet &paramSet)
COREDLL VolumeIntegrator * MakeVolumeIntegrator (const string &name, const ParamSet &paramSet)
COREDLL Primitive * MakeAccelerator (const string &name, const vector< Reference< Primitive > > &prims, const ParamSet &paramSet)
COREDLL Camera * MakeCamera (const string &name, const ParamSet &paramSet, const Transform &world2cam, Film *film)
COREDLL Sampler * MakeSampler (const string &name, const ParamSet &paramSet, const Film *film)
COREDLL Filter * MakeFilter (const string &name, const ParamSet &paramSet)
COREDLL ToneMap * MakeToneMap (const string &name, const ParamSet &paramSet)
COREDLL Film * MakeFilm (const string &name, const ParamSet &paramSet, Filter *filter)
Variables
static string PluginSearchPath
static map< string, ShapePlugin * > shapePlugins
static map< string,
FilterPlugin * > filterPlugins
static map< string,
MaterialPlugin * > materialPlugins
static map< string,
TexturePlugin * > texturePlugins
static map< string, FilmPlugin * > filmPlugins
static map< string, LightPlugin * > lightPlugins
static map< string,
AreaLightPlugin * > arealightPlugins
static map< string,
VolumeRegionPlugin * > volumePlugins
static map< string,
SurfaceIntegratorPlugin * > surf_integratorPlugins
static map< string,
VolumeIntegratorPlugin * > vol_integratorPlugins
static map< string,
ToneMapPlugin * > tonemapPlugins
static map< string,
AcceleratorPlugin * > acceleratorPlugins
static map< string,
CameraPlugin * > cameraPlugins
static map< string,
SamplerPlugin * > samplerPlugins
Function Documentation
template<class D > D* GetPlugin (const string & name, map< string, D * > & loadedPlugins, const string & searchPath) [inline]
Definition at line 41 of file dynload.cpp.
References Error(), and SearchPath().
COREDLL Primitive* MakeAccelerator (const string & name, const vector< Reference< Primitive > > & prims, const ParamSet & paramSet)
Definition at line 398 of file dynload.cpp.
References acceleratorPlugins, AcceleratorPlugin::CreateAccelerator, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene(), and pbrtObjectInstance().
COREDLL AreaLight* MakeAreaLight (const string & name, const Transform & light2world, const ParamSet & paramSet, const Reference< Shape > & shape)
Definition at line 353 of file dynload.cpp.
References arealightPlugins, AreaLightPlugin::CreateAreaLight, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by pbrtShape().
COREDLL Camera* MakeCamera (const string & name, const ParamSet & paramSet, const Transform & world2cam, Film * film)
Definition at line 410 of file dynload.cpp.
References cameraPlugins, CameraPlugin::CreateCamera, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene().
COREDLL Film* MakeFilm (const string & name, const ParamSet & paramSet, Filter * filter)
Definition at line 451 of file dynload.cpp.
References FilmPlugin::CreateFilm, filmPlugins, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene().
COREDLL Filter* MakeFilter (const string & name, const ParamSet & paramSet)
Definition at line 431 of file dynload.cpp.
References FilterPlugin::CreateFilter, filterPlugins, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by RenderOptions::MakeScene().
COREDLL Reference<Texture<float> > MakeFloatTexture (const string & name, const Transform & tex2world, const TextureParams & tp)
Definition at line 319 of file dynload.cpp.
References TexturePlugin::CreateFloatTex, PluginSearchPath, TextureParams::ReportUnused(), and texturePlugins.
Referenced by pbrtTexture().
COREDLL Light* MakeLight (const string & name, const Transform & light2world, const ParamSet & paramSet)
Definition at line 343 of file dynload.cpp.
References LightPlugin::CreateLight, lightPlugins, PluginSearchPath, and ParamSet::ReportUnused().
Referenced by pbrtLightSource().
COREDLL Reference<Material> MakeMaterial (const string & name, const Transform & mtl2world, const TextureParams & mp)
Definition at line 306 of file dynload.cpp.
References MaterialPlugin::CreateMaterial, materialPlugins, PluginSearchPath, and TextureParams::ReportUnused().
Referenced by pbrtShape().
COREDLL Sampler* MakeSampler (const string & name, const ParamSet & paramSet, const Film * film)
Definition at line 421 of file dynload.cpp.
References SamplerPlugin::CreateSampler, PluginSearchPath, ParamSet::ReportUnused(), and samplerPlugins.
Referenced by RenderOptions::MakeScene().
COREDLL Reference<Shape> MakeShape (const string & name, const Transform & object2world, bool reverseOrientation, const ParamSet & paramSet)
Definition at line 272 of file dynload.cpp.
References ShapePlugin::CreateShape, PluginSearchPath, and shapePlugins.
Referenced by pbrtShape(), NURBS::Refine(), LoopSubdiv::Refine(), and Heightfield::Refine().
COREDLL Reference<Texture<Spectrum> > MakeSpectrumTexture (const string & name, const Transform & tex2world, const TextureParams & tp)
Definition at line 331 of file dynload.cpp.
References TexturePlugin::CreateSpectrumTex, PluginSearchPath, TextureParams::ReportUnused(), and texturePlugins.
Referenced by pbrtTexture().
COREDLL SurfaceIntegrator* MakeSurfaceIntegrator (const string & name, const ParamSet & paramSet)
Definition at line 376 of file dynload.cpp.
References SurfaceIntegratorPlugin::CreateSurfaceIntegrator, PluginSearchPath, ParamSet::ReportUnused(), and surf_integratorPlugins.
Referenced by RenderOptions::MakeScene().
COREDLL ToneMap* MakeToneMap (const string & name, const ParamSet & paramSet)
Definition at line 441 of file dynload.cpp.
References ToneMapPlugin::CreateToneMap, PluginSearchPath, ParamSet::ReportUnused(), and tonemapPlugins.
Referenced by ApplyImagingPipeline().
COREDLL VolumeIntegrator* MakeVolumeIntegrator (const string & name, const ParamSet & paramSet)
Definition at line 387 of file dynload.cpp.
References VolumeIntegratorPlugin::CreateVolumeIntegrator, PluginSearchPath, ParamSet::ReportUnused(), and vol_integratorPlugins.
Referenced by RenderOptions::MakeScene().
COREDLL VolumeRegion* MakeVolumeRegion (const string & name, const Transform & volume2world, const ParamSet & paramSet)
Definition at line 365 of file dynload.cpp.
References VolumeRegionPlugin::CreateVolumeRegion, PluginSearchPath, ParamSet::ReportUnused(), and volumePlugins.
Referenced by pbrtVolume().
static string SearchPath (const string & searchpath, const string & filename) [static]
Definition at line 286 of file dynload.cpp.
References PBRT_PATH_SEP.
Referenced by GetPlugin().
COREDLL void UpdatePluginPath (const string & newpath)
Definition at line 262 of file dynload.cpp.
References PluginSearchPath.
Referenced by pbrtSearchPath(), and RenderOptions::RenderOptions().
Variable Documentation
map<string, AcceleratorPlugin *> acceleratorPlugins [static]
Definition at line 91 of file dynload.cpp.
Referenced by MakeAccelerator().
map<string, AreaLightPlugin *> arealightPlugins [static]
Definition at line 86 of file dynload.cpp.
Referenced by MakeAreaLight().
map<string, CameraPlugin *> cameraPlugins [static]
Definition at line 92 of file dynload.cpp.
Referenced by MakeCamera().
map<string, FilmPlugin *> filmPlugins [static]
Definition at line 84 of file dynload.cpp.
Referenced by MakeFilm().
map<string, FilterPlugin *> filterPlugins [static]
Definition at line 81 of file dynload.cpp.
Referenced by MakeFilter().
map<string, LightPlugin *> lightPlugins [static]
Definition at line 85 of file dynload.cpp.
Referenced by MakeLight().
map<string, MaterialPlugin *> materialPlugins [static]
Definition at line 82 of file dynload.cpp.
Referenced by MakeMaterial().
string PluginSearchPath [static]
Definition at line 79 of file dynload.cpp.
Referenced by MakeAccelerator(), MakeAreaLight(), MakeCamera(), MakeFilm(), MakeFilter(), MakeFloatTexture(), MakeLight(), MakeMaterial(), MakeSampler(), MakeShape(), MakeSpectrumTexture(), MakeSurfaceIntegrator(), MakeToneMap(), MakeVolumeIntegrator(), MakeVolumeRegion(), and UpdatePluginPath().
map<string, SamplerPlugin *> samplerPlugins [static]
Definition at line 93 of file dynload.cpp.
Referenced by MakeSampler().
map<string, ShapePlugin *> shapePlugins [static]
Definition at line 80 of file dynload.cpp.
Referenced by MakeShape().
map<string, SurfaceIntegratorPlugin *> surf_integratorPlugins [static]
Definition at line 88 of file dynload.cpp.
Referenced by MakeSurfaceIntegrator().
map<string, TexturePlugin *> texturePlugins [static]
Definition at line 83 of file dynload.cpp.
Referenced by MakeFloatTexture(), and MakeSpectrumTexture().
map<string, ToneMapPlugin *> tonemapPlugins [static]
Definition at line 90 of file dynload.cpp.
Referenced by MakeToneMap().
map<string, VolumeIntegratorPlugin *> vol_integratorPlugins [static]
Definition at line 89 of file dynload.cpp.
Referenced by MakeVolumeIntegrator().
map<string, VolumeRegionPlugin *> volumePlugins [static]
Definition at line 87 of file dynload.cpp.
Referenced by MakeVolumeRegion().