pbrt: exphotonmap.cpp File Reference
exphotonmap.cpp File Reference
#include "pbrt.h"
#include "transport.h"
#include "scene.h"
#include "mc.h"
#include "kdtree.h"
#include "sampling.h"
Classes
struct Photon
struct RadiancePhoton
struct RadiancePhotonProcess
struct PhotonProcess
struct ClosePhoton
class ExPhotonIntegrator
Functions
float kernel (const Photon *photon, const Point &p, float md2)
DLLEXPORT SurfaceIntegrator * CreateSurfaceIntegrator (const ParamSet &params)
Function Documentation
DLLEXPORT SurfaceIntegrator* CreateSurfaceIntegrator (const ParamSet & params)
Definition at line 714 of file exphotonmap.cpp.
References ExPhotonIntegrator::ExPhotonIntegrator(), ExPhotonIntegrator::finalGather, ParamSet::FindOneBool(), ParamSet::FindOneFloat(), ParamSet::FindOneInt(), ExPhotonIntegrator::gatherSamples, and ExPhotonIntegrator::rrTreshold.
float kernel (const Photon * photon, const Point & p, float md2) [inline]
Definition at line 70 of file exphotonmap.cpp.
References DistanceSquared(), M_PI, and Photon::p.
Referenced by ExPhotonIntegrator::LPhoton().