pbrt: exrassemble.cpp File Reference
exrassemble.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <sys/types.h>
#include <dirent.h>
#include <string.h>
#include <ImfAttribute.h>
#include <ImfInputFile.h>
#include <ImfOutputFile.h>
#include <ImfChannelList.h>
#include <ImfFrameBuffer.h>
#include <half.h>
Functions
void WriteEXR (const char *name, half *rgba, int xRes, int yRes)
half * ReadEXR (const char *name, int *x0, int *y0, int *xSize, int *ySize, int *xres, int *yres)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file exrassemble.cpp.
References memcpy(), ReadEXR(), and WriteEXR().
half * ReadEXR (const char * name, int * x0, int * y0, int * xSize, int * ySize, int * xres, int * yres)
Definition at line 101 of file exrassemble.cpp.
Referenced by main().
void WriteEXR (const char * name, half * rgba, int xRes, int yRes)
Definition at line 76 of file exrassemble.cpp.
Referenced by main().