pbrt: exrio.cpp File Reference
exrio.cpp File Reference
#include <ImfInputFile.h>
#include <ImfOutputFile.h>
#include <ImfChannelList.h>
#include <ImfFrameBuffer.h>
#include <ImfRgbaFile.h>
#include <half.h>
#include "pbrt.h"
#include "color.h"
Functions
COREDLL Spectrum * ReadImage (const string &name, int *width, int *height)
COREDLL void WriteRGBAImage (const string &name, float *pixels, float *alpha, int xRes, int yRes, int totalXRes, int totalYRes, int xOffset, int yOffset)
Function Documentation
COREDLL Spectrum* ReadImage (const string & name, int * width, int * height)
Definition at line 40 of file exrio.cpp.
References Error(), and Spectrum::y().
Referenced by ImageTexture< T >::GetTexture(), GonioPhotometricLight::GonioPhotometricLight(), InfiniteAreaLight::InfiniteAreaLight(), InfiniteAreaLightIS::InfiniteAreaLightIS(), and ProjectionLight::ProjectionLight().
COREDLL void WriteRGBAImage (const string & name, float * pixels, float * alpha, int xRes, int yRes, int totalXRes, int totalYRes, int xOffset, int yOffset)
Definition at line 75 of file exrio.cpp.
References Error().
Referenced by ImageFilm::WriteImage().