pbrt: exrtotiff.cpp File Reference
exrtotiff.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <tiffio.h>
#include <ImfInputFile.h>
#include <ImfChannelList.h>
#include <ImfFrameBuffer.h>
#include <half.h>
#include "pbrt.h"
#include "film.h"
#include "paramset.h"
Defines
#define ARG(name, var)
Functions
static bool ReadEXR (const char *name, float *&rgba, int &xRes, int &yRes, bool &hasAlpha)
static void WriteTIFF (const char *name, float *rgba, int xRes, int yRes, bool hasAlpha)
static void usage ()
int main (int argc, char *argv[])
Define Documentation
#define ARG (name, var)
Value:
else if (!strcmp(argv[argNum], "-" name)) { \
        if (argNum+1 == argc) \
          usage(); \
        var = atof(argv[argNum+1]); \
        ++argNum; \
      }
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 38 of file exrtotiff.cpp.
References ParamSet::AddFloat(), ApplyImagingPipeline(), ARG, pbrtCleanup(), pbrtInit(), ReadEXR(), usage(), and WriteTIFF().
static bool ReadEXR (const char * name, float *& rgba, int & xRes, int & yRes, bool & hasAlpha) [static]
Definition at line 164 of file exrtotiff.cpp.
static void usage () [static]
Definition at line 25 of file exrtotiff.cpp.
Referenced by main().
void WriteTIFF (const char * name, float * rgba, int xRes, int yRes, bool hasAlpha) [static]
Definition at line 120 of file exrtotiff.cpp.
Referenced by main().