pbrt: fbm.cpp File Reference
fbm.cpp File Reference
#include "pbrt.h"
#include "texture.h"
#include "paramset.h"
Classes
class FBmTexture< T >
Functions
DLLEXPORT Texture< float > * CreateFloatTexture (const Transform &tex2world, const TextureParams &tp)
DLLEXPORT Texture< Spectrum > * CreateSpectrumTexture (const Transform &tex2world, const TextureParams &tp)
Function Documentation
DLLEXPORT Texture<float>* CreateFloatTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 52 of file fbm.cpp.
References TextureParams::FindFloat(), and TextureParams::FindInt().
DLLEXPORT Texture<Spectrum>* CreateSpectrumTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 60 of file fbm.cpp.
References TextureParams::FindFloat(), and TextureParams::FindInt().