pbrt: film.h File Reference
film.h File Reference
#include "pbrt.h"
Classes
class Film
Functions
COREDLL void ApplyImagingPipeline (float *rgb, int xResolution, int yResolution, float *yWeight=NULL, float bloomRadius=.2f, float bloomWeight=0.f, const char *tonemap=NULL, const ParamSet *toneMapParams=NULL, float gamma=2.2, float dither=0.5f, int maxDisplayValue=255)
Function Documentation
COREDLL void ApplyImagingPipeline (float * rgb, int xResolution, int yResolution, float * yWeight = NULL, float bloomRadius = .2f, float bloomWeight = 0.f, const char * tonemap = NULL, const ParamSet * toneMapParams = NULL, float gamma = 2.2, float dither = 0.5f, int maxDisplayValue = 255)
Definition at line 30 of file film.cpp.
References ProgressReporter::Done(), Float2Int(), Lerp(), MakeToneMap(), ToneMap::Map(), RandomFloat(), and ProgressReporter::Update().
Referenced by main().