pbrt: film.cpp File Reference
film.cpp File Reference
#include "film.h"
#include "dynload.h"
#include "paramset.h"
#include "tonemap.h"
Functions
void ApplyImagingPipeline (float *rgb, int xResolution, int yResolution, float *yWeight, float bloomRadius, float bloomWeight, const char *toneMapName, const ParamSet *toneMapParams, float gamma, float dither, int maxDisplayValue)
Function Documentation
void ApplyImagingPipeline (float * rgb, int xResolution, int yResolution, float * yWeight, float bloomRadius, float bloomWeight, const char * toneMapName, const ParamSet * toneMapParams, float gamma, float dither, int maxDisplayValue)
Definition at line 30 of file film.cpp.
References ProgressReporter::Done(), Float2Int(), Lerp(), MakeToneMap(), ToneMap::Map(), RandomFloat(), and ProgressReporter::Update().
Referenced by main().