pbrt: geometry.cpp File Reference
geometry.cpp File Reference
#include "geometry.h"
Functions
COREDLL BBox Union (const BBox &b, const Point &p)
COREDLL BBox Union (const BBox &b, const BBox &b2)
Function Documentation
COREDLL BBox Union (const BBox & b, const BBox & b2)
Definition at line 37 of file geometry.cpp.
References BBox::pMax, BBox::pMin, Point::x, Point::y, and Point::z.
COREDLL BBox Union (const BBox & b, const Point & p)
Definition at line 27 of file geometry.cpp.
References BBox::pMax, BBox::pMin, Point::x, Point::y, and Point::z.
Referenced by AggregateVolume::AggregateVolume(), GridAccel::GridAccel(), KdTreeAccel::KdTreeAccel(), Triangle::ObjectBound(), TriangleMesh::ObjectBound(), ShapeSet::ObjectBound(), NURBS::ObjectBound(), LoopSubdiv::ObjectBound(), Transform::operator()(), KdTree< NodeData, LookupProc >::recursiveBuild(), Scene::Scene(), Triangle::WorldBound(), TriangleMesh::WorldBound(), NURBS::WorldBound(), and LoopSubdiv::WorldBound().