pbrt: grid.cpp File Reference
grid.cpp File Reference
#include "pbrt.h"
#include "primitive.h"
Classes
struct MailboxPrim
struct Voxel
class GridAccel
Functions
DLLEXPORT Primitive * CreateAccelerator (const vector< Reference< Primitive > > &prims, const ParamSet &ps)
Variables
static StatsRatio rayTests ("Grid Accelerator","Intersection tests per ray")
static StatsRatio rayHits ("Grid Accelerator","Intersections found per ray")
Function Documentation
DLLEXPORT Primitive* CreateAccelerator (const vector< Reference< Primitive > > & prims, const ParamSet & ps)
Definition at line 430 of file grid.cpp.
References ParamSet::FindOneBool().
Variable Documentation
StatsRatio rayHits("Grid Accelerator","Intersections found per ray") [static]
Referenced by Voxel::Intersect(), GridAccel::Intersect(), Voxel::IntersectP(), and GridAccel::IntersectP().
StatsRatio rayTests("Grid Accelerator","Intersection tests per ray") [static]
Referenced by Voxel::Intersect(), GridAccel::Intersect(), Voxel::IntersectP(), and GridAccel::IntersectP().