pbrt: homogeneous.cpp File Reference
homogeneous.cpp File Reference
#include "volume.h"
Classes
class HomogeneousVolume
Functions
DLLEXPORT VolumeRegion * CreateVolumeRegion (const Transform &volume2world, const ParamSet &params)
Function Documentation
DLLEXPORT VolumeRegion* CreateVolumeRegion (const Transform & volume2world, const ParamSet & params)
Definition at line 76 of file homogeneous.cpp.
References ParamSet::FindOneFloat(), ParamSet::FindOnePoint(), and ParamSet::FindOneSpectrum().