pbrt: igi.cpp File Reference
igi.cpp File Reference
#include "pbrt.h"
#include "transport.h"
#include "scene.h"
#include "mc.h"
#include "sampling.h"
Classes
struct VirtualLight
class IGIIntegrator
Functions
DLLEXPORT SurfaceIntegrator * CreateSurfaceIntegrator (const ParamSet &params)
Function Documentation
DLLEXPORT SurfaceIntegrator* CreateSurfaceIntegrator (const ParamSet & params)
Definition at line 288 of file igi.cpp.
References ParamSet::FindOneFloat(), ParamSet::FindOneInt(), IGIIntegrator::IGIIntegrator(), IGIIntegrator::nLightPaths, and IGIIntegrator::nLightSets.