pbrt: image.cpp File Reference
image.cpp File Reference
#include "pbrt.h"
#include "film.h"
#include "color.h"
#include "paramset.h"
#include "tonemap.h"
#include "sampling.h"
Classes
class ImageFilm
struct ImageFilm::Pixel
Defines
#define FILTER_TABLE_SIZE 16
Functions
DLLEXPORT Film * CreateFilm (const ParamSet &params, Filter *filter)
Define Documentation
#define FILTER_TABLE_SIZE 16
Referenced by ImageFilm::AddSample(), and ImageFilm::ImageFilm().
Function Documentation
DLLEXPORT Film* CreateFilm (const ParamSet & params, Filter * filter)
Definition at line 213 of file image.cpp.
References Clamp(), ImageFilm::filename, ParamSet::FindFloat(), ParamSet::FindOneBool(), ParamSet::FindOneInt(), ParamSet::FindOneString(), ImageFilm::ImageFilm(), ImageFilm::premultiplyAlpha, and ImageFilm::writeFrequency.