pbrt: infinitesample.cpp File Reference
infinitesample.cpp File Reference
#include "pbrt.h"
#include "light.h"
#include "texture.h"
#include "shape.h"
#include "scene.h"
#include "mipmap.h"
Classes
struct Distribution1D
class InfiniteAreaLightIS
Functions
DLLEXPORT Light * CreateLight (const Transform &light2world, const ParamSet &paramSet)
Function Documentation
DLLEXPORT Light* CreateLight (const Transform & light2world, const ParamSet & paramSet)
Definition at line 217 of file infinitesample.cpp.
References ParamSet::FindOneInt(), ParamSet::FindOneSpectrum(), ParamSet::FindOneString(), InfiniteAreaLightIS::InfiniteAreaLightIS(), and Light::nSamples.