pbrt: infinite.cpp File Reference
infinite.cpp File Reference
#include "pbrt.h"
#include "light.h"
#include "texture.h"
#include "shape.h"
#include "scene.h"
#include "mipmap.h"
Classes
class InfiniteAreaLight
Functions
DLLEXPORT Light * CreateLight (const Transform &light2world, const ParamSet &paramSet)
Function Documentation
DLLEXPORT Light* CreateLight (const Transform & light2world, const ParamSet & paramSet)
Definition at line 163 of file infinite.cpp.
References ParamSet::FindOneInt(), ParamSet::FindOneSpectrum(), and ParamSet::FindOneString().