pbrt: kdtree.cpp File Reference
kdtree.cpp File Reference
#include "pbrt.h"
#include "primitive.h"
Classes
struct MailboxPrim
struct KdAccelNode
struct BoundEdge
class KdTreeAccel
struct KdToDo
Defines
#define MAX_TODO 64
#define MAX_TODO 64
Functions
DLLEXPORT Primitive * CreateAccelerator (const vector< Reference< Primitive > > &prims, const ParamSet &ps)
Define Documentation
#define MAX_TODO 64
#define MAX_TODO 64
Referenced by KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
Function Documentation
DLLEXPORT Primitive* CreateAccelerator (const vector< Reference< Primitive > > & prims, const ParamSet & ps)
Definition at line 489 of file kdtree.cpp.
References KdTreeAccel::emptyBonus, ParamSet::FindOneFloat(), ParamSet::FindOneInt(), KdTreeAccel::isectCost, KdTreeAccel::KdTreeAccel(), and KdTreeAccel::maxPrims.