pbrt: loopsubdiv.cpp File Reference
loopsubdiv.cpp File Reference
#include "shape.h"
#include "paramset.h"
#include "dynload.h"
#include "texture.h"
#include <set>
#include <map>
Classes
struct SDVertex
struct SDFace
struct SDEdge
class LoopSubdiv
Defines
#define NEXT(i) (((i)+1)%3)
#define PREV(i) (((i)+2)%3)
Functions
DLLEXPORT Shape * CreateShape (const Transform &o2w, bool reverseOrientation, const ParamSet &params)
Define Documentation
#define NEXT (i) (((i)+1)%3)
Definition at line 34 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::LoopSubdiv(), SDFace::nextVert(), and LoopSubdiv::Refine().
#define PREV (i) (((i)+2)%3)
Definition at line 35 of file loopsubdiv.cpp.
Referenced by SDFace::prevFace(), SDFace::prevVert(), and LoopSubdiv::Refine().
Function Documentation
DLLEXPORT Shape* CreateShape (const Transform & o2w, bool reverseOrientation, const ParamSet & params)
Definition at line 481 of file loopsubdiv.cpp.
References ParamSet::FindInt(), ParamSet::FindOneInt(), ParamSet::FindOneString(), ParamSet::FindPoint(), and LoopSubdiv::LoopSubdiv().