pbrt: mc.cpp File Reference
mc.cpp File Reference
#include "pbrt.h"
#include "geometry.h"
#include "shape.h"
#include "mc.h"
#include "volume.h"
Functions
void ComputeStep1dCDF (float *f, int nSteps, float *c, float *cdf)
float SampleStep1d (float *f, float *cdf, float c, int nSteps, float u, float *pdf)
void RejectionSampleDisk (float *x, float *y)
COREDLL Vector UniformSampleHemisphere (float u1, float u2)
COREDLL float UniformHemispherePdf (float theta, float phi)
COREDLL Vector UniformSampleSphere (float u1, float u2)
COREDLL float UniformSpherePdf ()
COREDLL void UniformSampleDisk (float u1, float u2, float *x, float *y)
COREDLL void ConcentricSampleDisk (float u1, float u2, float *dx, float *dy)
COREDLL void UniformSampleTriangle (float u1, float u2, float *u, float *v)
COREDLL float UniformConePdf (float cosThetaMax)
Vector UniformSampleCone (float u1, float u2, float costhetamax)
COREDLL Vector UniformSampleCone (float u1, float u2, float costhetamax, const Vector &x, const Vector &y, const Vector &z)
COREDLL Vector SampleHG (const Vector &w, float g, float u1, float u2)
COREDLL float HGPdf (const Vector &w, const Vector &wp, float g)
Function Documentation
void ComputeStep1dCDF (float * f, int nSteps, float * c, float * cdf)
Definition at line 31 of file mc.cpp.
Referenced by Distribution1D::Distribution1D(), IGIIntegrator::Preprocess(), ExPhotonIntegrator::Preprocess(), and WeightedSampleOneLight().
COREDLL void ConcentricSampleDisk (float u1, float u2, float * dx, float * dy)
Definition at line 92 of file mc.cpp.
References M_PI.
Referenced by CosineSampleHemisphere(), PerspectiveCamera::GenerateRay(), OrthoCamera::GenerateRay(), Disk::Sample(), InfiniteAreaLight::Sample_L(), and DistantLight::Sample_L().
COREDLL float HGPdf (const Vector & w, const Vector & wp, float g)
Definition at line 179 of file mc.cpp.
References PhaseHG().
void RejectionSampleDisk (float * x, float * y)
Definition at line 54 of file mc.cpp.
References RandomFloat().
COREDLL Vector SampleHG (const Vector & w, float g, float u1, float u2)
Definition at line 162 of file mc.cpp.
References CoordinateSystem(), M_PI, and SphericalDirection().
float SampleStep1d (float * f, float * cdf, float c, int nSteps, float u, float * pdf)
Definition at line 43 of file mc.cpp.
References Assert.
Referenced by IGIIntegrator::Preprocess(), ExPhotonIntegrator::Preprocess(), and WeightedSampleOneLight().
COREDLL float UniformConePdf (float cosThetaMax)
Definition at line 142 of file mc.cpp.
References M_PI.
Referenced by ExPhotonIntegrator::Li(), Sphere::Pdf(), SpotLight::Sample_L(), and ProjectionLight::Sample_L().
COREDLL float UniformHemispherePdf (float theta, float phi)
Definition at line 71 of file mc.cpp.
References INV_TWOPI.
COREDLL Vector UniformSampleCone (float u1, float u2, float costhetamax, const Vector & x, const Vector & y, const Vector & z)
Definition at line 154 of file mc.cpp.
References Lerp(), and M_PI.
Vector UniformSampleCone (float u1, float u2, float costhetamax)
Definition at line 145 of file mc.cpp.
References Lerp(), and M_PI.
Referenced by ExPhotonIntegrator::Li(), Sphere::Sample(), SpotLight::Sample_L(), and ProjectionLight::Sample_L().
COREDLL void UniformSampleDisk (float u1, float u2, float * x, float * y)
Definition at line 85 of file mc.cpp.
References M_PI.
COREDLL Vector UniformSampleHemisphere (float u1, float u2)
Definition at line 63 of file mc.cpp.
References M_PI.
Referenced by BxDF::rho().
COREDLL Vector UniformSampleSphere (float u1, float u2)
Definition at line 74 of file mc.cpp.
References M_PI.
Referenced by Sphere::Sample(), PointLight::Sample_L(), InfiniteAreaLightIS::Sample_L(), InfiniteAreaLight::Sample_L(), GonioPhotometricLight::Sample_L(), and AreaLight::Sample_L().
COREDLL void UniformSampleTriangle (float u1, float u2, float * u, float * v)
Definition at line 136 of file mc.cpp.
Referenced by Triangle::Sample().
COREDLL float UniformSpherePdf ()
Definition at line 82 of file mc.cpp.
References M_PI.
Referenced by PointLight::Sample_L(), InfiniteAreaLight::Sample_L(), and GonioPhotometricLight::Sample_L().