pbrt: mc.h File Reference
mc.h File Reference
Functions
COREDLL void RejectionSampleDisk (float u1, float u2, float *x, float *y)
COREDLL Vector UniformSampleHemisphere (float u1, float u2)
COREDLL float UniformHemispherePdf (float theta, float phi)
COREDLL Vector UniformSampleSphere (float u1, float u2)
COREDLL float UniformSpherePdf ()
COREDLL Vector UniformSampleCone (float u1, float u2, float costhetamax)
COREDLL Vector UniformSampleCone (float u1, float u2, float costhetamax, const Vector &x, const Vector &y, const Vector &z)
COREDLL float UniformConePdf (float costhetamax)
COREDLL void UniformSampleDisk (float u1, float u2, float *x, float *y)
Vector CosineSampleHemisphere (float u1, float u2)
float CosineHemispherePdf (float costheta, float phi)
COREDLL Vector SampleHG (const Vector &w, float g, float u1, float u2)
COREDLL float HGPdf (const Vector &w, const Vector &wp, float g)
float BalanceHeuristic (int nf, float fPdf, int ng, float gPdf)
float PowerHeuristic (int nf, float fPdf, int ng, float gPdf)
Function Documentation
float BalanceHeuristic (int nf, float fPdf, int ng, float gPdf) [inline]
Definition at line 51 of file mc.h.
float CosineHemispherePdf (float costheta, float phi) [inline]
Definition at line 45 of file mc.h.
References INV_PI.
Vector CosineSampleHemisphere (float u1, float u2) [inline]
Definition at line 38 of file mc.h.
References ConcentricSampleDisk(), Vector::x, Vector::y, and Vector::z.
Referenced by IrradianceCache::IndirectLo(), FresnelBlend::Sample_f(), and BxDF::Sample_f().
COREDLL float HGPdf (const Vector & w, const Vector & wp, float g)
Definition at line 179 of file mc.cpp.
References PhaseHG().
float PowerHeuristic (int nf, float fPdf, int ng, float gPdf) [inline]
Definition at line 55 of file mc.h.
Referenced by EstimateDirect(), and ExPhotonIntegrator::Li().
COREDLL void RejectionSampleDisk (float u1, float u2, float * x, float * y)
COREDLL Vector SampleHG (const Vector & w, float g, float u1, float u2)
Definition at line 162 of file mc.cpp.
References CoordinateSystem(), M_PI, and SphericalDirection().
COREDLL float UniformConePdf (float costhetamax)
Definition at line 142 of file mc.cpp.
References M_PI.
Referenced by ExPhotonIntegrator::Li(), Sphere::Pdf(), SpotLight::Sample_L(), and ProjectionLight::Sample_L().
COREDLL float UniformHemispherePdf (float theta, float phi)
Definition at line 71 of file mc.cpp.
References INV_TWOPI.
COREDLL Vector UniformSampleCone (float u1, float u2, float costhetamax, const Vector & x, const Vector & y, const Vector & z)
Definition at line 154 of file mc.cpp.
References Lerp(), and M_PI.
COREDLL Vector UniformSampleCone (float u1, float u2, float costhetamax)
Definition at line 145 of file mc.cpp.
References Lerp(), and M_PI.
Referenced by ExPhotonIntegrator::Li(), Sphere::Sample(), SpotLight::Sample_L(), and ProjectionLight::Sample_L().
COREDLL void UniformSampleDisk (float u1, float u2, float * x, float * y)
Definition at line 85 of file mc.cpp.
References M_PI.
COREDLL Vector UniformSampleHemisphere (float u1, float u2)
Definition at line 63 of file mc.cpp.
References M_PI.
Referenced by BxDF::rho().
COREDLL Vector UniformSampleSphere (float u1, float u2)
Definition at line 74 of file mc.cpp.
References M_PI.
Referenced by Sphere::Sample(), PointLight::Sample_L(), InfiniteAreaLightIS::Sample_L(), InfiniteAreaLight::Sample_L(), GonioPhotometricLight::Sample_L(), and AreaLight::Sample_L().
COREDLL float UniformSpherePdf ()
Definition at line 82 of file mc.cpp.
References M_PI.
Referenced by PointLight::Sample_L(), InfiniteAreaLight::Sample_L(), and GonioPhotometricLight::Sample_L().