pbrt: mix.cpp File Reference
mix.cpp File Reference
#include "pbrt.h"
#include "texture.h"
#include "paramset.h"
Classes
class MixTexture< T >
Functions
DLLEXPORT Texture< float > * CreateFloatTexture (const Transform &tex2world, const TextureParams &tp)
DLLEXPORT Texture< Spectrum > * CreateSpectrumTexture (const Transform &tex2world, const TextureParams &tp)
Function Documentation
DLLEXPORT Texture<float>* CreateFloatTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 50 of file mix.cpp.
References TextureParams::GetFloatTexture().
DLLEXPORT Texture<Spectrum>* CreateSpectrumTexture (const Transform & tex2world, const TextureParams & tp)
Definition at line 58 of file mix.cpp.
References TextureParams::GetFloatTexture(), and TextureParams::GetSpectrumTexture().