pbrt: orthographic.cpp File Reference
orthographic.cpp File Reference
#include "camera.h"
#include "film.h"
#include "paramset.h"
Classes
class OrthoCamera
Functions
DLLEXPORT Camera * CreateCamera (const ParamSet &params, const Transform &world2cam, Film *film)
Function Documentation
DLLEXPORT Camera* CreateCamera (const ParamSet & params, const Transform & world2cam, Film * film)
Definition at line 80 of file orthographic.cpp.
References ParamSet::FindFloat(), ParamSet::FindOneFloat(), memcpy(), OrthoCamera::OrthoCamera(), Film::xResolution, and Film::yResolution.