pbrt: pbrt.cpp File Reference
pbrt.cpp File Reference
#include "pbrt.h"
#include "api.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file pbrt.cpp.
References Error(), ParseFile(), PBRT_VERSION, pbrtCleanup(), and pbrtInit().