pbrt: pbrtparse.y File Reference
pbrtparse.y File Reference
#include "api.h"
#include "pbrt.h"
#include "paramset.h"
#include <stdarg.h>
Defines
#define YYMAXDEPTH 100000000
#define CPS cur_paramlist_size
#define CPT cur_paramlist_tokens
#define CPA cur_paramlist_args
#define CPTH cur_paramlist_texture_helper
#define CPSZ cur_paramlist_sizes
#define NA(r) ((float *) r->array)
#define SA(r) ((const char **) r->array)
#define YYPRINT(file, type, value)
#define TRY_DECODING_TYPE(name, mask)
Functions
memcpy (arg, $2->array, $2->nelems *$2->element_size)
if (cur_paramlist_size >=cur_paramlist_allocated)
ArrayFree ($2)
InitParamSet (params, CPS, CPT, CPA, CPSZ, CPTH)
pbrtAccelerator ($2, params)
FreeArgs ()
static void InitParamSet (ParamSet &ps, int count, const char **tokens, void **args, int *sizes, bool *texture_helper)
static bool lookupType (const char *token, int *type, string &name)
Variables
array_init __pad0__
cur_array = new ParamArray
cur_array allocated = 0
cur_array nelems = 0
cur_array array = NULL
array_is_single_string = false
string_array_init __pad1__
num_array_init __pad2__
array __pad3__
string_array __pad4__
real_string_array __pad5__
single_element_string_array __pad6__
string_list __pad7__
string_list_entry __pad8__
AddArrayElement & to_add
num_array __pad9__
real_num_array __pad10__
single_element_num_array __pad11__
num_list __pad12__
num_list_entry __pad13__
paramlist __pad14__
paramlist_init __pad15__
paramlist_contents __pad16__
paramlist_entry __pad17__
cur_paramlist_tokens [cur_paramlist_size] = $1
cur_paramlist_sizes [cur_paramlist_size] = $2->nelems
cur_paramlist_texture_helper [cur_paramlist_size] = array_is_single_string
cur_paramlist_args [cur_paramlist_size++] = arg
ri_stmt_list __pad18__
ri_stmt __pad19__
Define Documentation
#define CPA cur_paramlist_args
#define CPS cur_paramlist_size
#define CPSZ cur_paramlist_sizes
#define CPT cur_paramlist_tokens
#define CPTH cur_paramlist_texture_helper
#define NA (r) ((float *) r->array)
#define SA (r) ((const char **) r->array)
#define TRY_DECODING_TYPE (name, mask)
Value:
if (strncmp(name, strp, strlen(name)) == 0) { \
                        *type = mask; strp += strlen(name); \
                }
#define YYMAXDEPTH 100000000
#define YYPRINT (file, type, value)
Value:
{ \
        if ((type) == ID || (type) == STRING) \
                fprintf ((file), " %s", (value).string); \
        else if ((type) == NUM) \
                fprintf ((file), " %f", (value).num); \
}
Function Documentation
ArrayFree ($ 2)
FreeArgs ()
Definition at line 238 of file pbrtparse.cpp.
References cur_paramlist_args, and cur_paramlist_size.
Referenced by yyparse().
if (cur_paramlist_size >= cur_paramlist_allocated)
Definition at line 9205 of file pbrtparse.y.
static void InitParamSet (ParamSet & ps, int count, const char ** tokens, void ** args, int * sizes, bool * texture_helper) [static]
Definition at line 9402 of file pbrtparse.y.
InitParamSet (params , CPS , CPT , CPA , CPSZ , CPTH)
static bool lookupType (const char * token, int * type, string & name) [static]
Definition at line 9475 of file pbrtparse.y.
memcpy (arg , $2-> array, $2->nelems *$2-> element_size)
Referenced by AddArrayElement(), ArrayDup(), KdTreeAccel::buildTree(), CreateCamera(), Distribution1D::Distribution1D(), Heightfield::Heightfield(), ImageFilm::ImageFilm(), Matrix4x4::Inverse(), main(), Matrix4x4::Matrix4x4(), NURBS::NURBS(), TriangleMesh::TriangleMesh(), VolumeGrid::VolumeGrid(), and yyparse().
pbrtAccelerator ($ 2, params)
Variable Documentation
array_init __pad0__
Definition at line 9091 of file pbrtparse.y.
real_num_array __pad10__
Definition at line 9161 of file pbrtparse.y.
single_element_num_array __pad11__
Definition at line 9166 of file pbrtparse.y.
num_list __pad12__
Definition at line 9177 of file pbrtparse.y.
num_list_entry __pad13__
Definition at line 9181 of file pbrtparse.y.
paramlist __pad14__
Definition at line 9183 of file pbrtparse.y.
paramlist_init __pad15__
Definition at line 9191 of file pbrtparse.y.
paramlist_contents __pad16__
Definition at line 9192 of file pbrtparse.y.
paramlist_entry __pad17__
Definition at line 9203 of file pbrtparse.y.
ri_stmt_list __pad18__
Definition at line 9217 of file pbrtparse.y.
ri_stmt __pad19__
Definition at line 9228 of file pbrtparse.y.
string_array_init __pad1__
Definition at line 9101 of file pbrtparse.y.
num_array_init __pad2__
Definition at line 9106 of file pbrtparse.y.
array __pad3__
Definition at line 9111 of file pbrtparse.y.
string_array __pad4__
Definition at line 9120 of file pbrtparse.y.
real_string_array __pad5__
Definition at line 9130 of file pbrtparse.y.
single_element_string_array __pad6__
Definition at line 9135 of file pbrtparse.y.
string_list __pad7__
Definition at line 9146 of file pbrtparse.y.
string_list_entry __pad8__
Definition at line 9150 of file pbrtparse.y.
num_array __pad9__
Definition at line 9152 of file pbrtparse.y.
cur_array allocated = 0
Definition at line 9097 of file pbrtparse.y.
cur_array array = NULL
Definition at line 9099 of file pbrtparse.y.
Referenced by yyparse().
array_is_single_string = false
Definition at line 9100 of file pbrtparse.y.
cur_array = new ParamArray
Definition at line 9096 of file pbrtparse.y.
cur_paramlist_args[cur_paramlist_size++] = arg
Definition at line 9215 of file pbrtparse.y.
cur_paramlist_sizes[cur_paramlist_size] = $2->nelems
Definition at line 9213 of file pbrtparse.y.
cur_paramlist_texture_helper[cur_paramlist_size] = array_is_single_string
Definition at line 9214 of file pbrtparse.y.
cur_paramlist_tokens[cur_paramlist_size] = $1
Definition at line 9212 of file pbrtparse.y.
cur_array nelems = 0
Definition at line 9098 of file pbrtparse.y.
Referenced by yyparse().
AddArrayElement & to_add
Definition at line 9151 of file pbrtparse.y.
Referenced by yyparse().