pbrt: reflection.cpp File Reference
reflection.cpp File Reference
#include "reflection.h"
#include "color.h"
#include "mc.h"
#include "sampling.h"
#include <stdarg.h>
Functions
COREDLL Spectrum FrDiel (float cosi, float cost, const Spectrum &etai, const Spectrum &etat)
COREDLL Spectrum FrCond (float cosi, const Spectrum &eta, const Spectrum &k)
COREDLL Spectrum FresnelApproxEta (const Spectrum &Fr)
COREDLL Spectrum FresnelApproxK (const Spectrum &Fr)
Function Documentation
COREDLL Spectrum FrCond (float cosi, const Spectrum & eta, const Spectrum & k)
Definition at line 40 of file reflection.cpp.
Referenced by FresnelConductor::Evaluate().
COREDLL Spectrum FrDiel (float cosi, float cost, const Spectrum & etai, const Spectrum & etat)
Definition at line 31 of file reflection.cpp.
Referenced by FresnelDielectric::Evaluate().
COREDLL Spectrum FresnelApproxEta (const Spectrum & Fr)
Definition at line 52 of file reflection.cpp.
References Spectrum::Clamp(), and Spectrum::Sqrt().
Referenced by ShinyMetal::GetBSDF().
COREDLL Spectrum FresnelApproxK (const Spectrum & Fr)
Definition at line 57 of file reflection.cpp.
References Spectrum::Clamp(), and Spectrum::Sqrt().