pbrt: sampling.cpp File Reference
sampling.cpp File Reference
#include "pbrt.h"
#include "sampling.h"
#include "transport.h"
#include "volume.h"
Functions
COREDLL void StratifiedSample1D (float *samp, int nSamples, bool jitter)
COREDLL void StratifiedSample2D (float *samp, int nx, int ny, bool jitter)
COREDLL void Shuffle (float *samp, int count, int dims)
COREDLL void LatinHypercube (float *samples, int nSamples, int nDim)
Function Documentation
COREDLL void LatinHypercube (float * samples, int nSamples, int nDim)
Definition at line 98 of file sampling.cpp.
References RandomFloat(), and RandomUInt().
Referenced by StratifiedSampler::GetNextSample(), SingleScattering::Li(), and BxDF::rho().
COREDLL void Shuffle (float * samp, int count, int dims)
Definition at line 91 of file sampling.cpp.
References RandomUInt().
Referenced by StratifiedSampler::GetNextSample(), LDShuffleScrambled1D(), LDShuffleScrambled2D(), and StratifiedSampler::StratifiedSampler().
COREDLL void StratifiedSample1D (float * samp, int nSamples, bool jitter)
Definition at line 72 of file sampling.cpp.
References RandomFloat().
Referenced by StratifiedSampler::GetNextSample(), BestCandidateSampler::GetNextSample(), and StratifiedSampler::StratifiedSampler().
COREDLL void StratifiedSample2D (float * samp, int nx, int ny, bool jitter)
Definition at line 80 of file sampling.cpp.
References RandomFloat().
Referenced by Checkerboard3D< T >::Evaluate(), Checkerboard2D< T >::Evaluate(), StratifiedSampler::GetNextSample(), BestCandidateSampler::GetNextSample(), and StratifiedSampler::StratifiedSampler().