pbrt: spot.cpp File Reference
spot.cpp File Reference
#include "pbrt.h"
#include "light.h"
#include "shape.h"
Classes
class SpotLight
Functions
DLLEXPORT Light * CreateLight (const Transform &l2w, const ParamSet &paramSet)
Function Documentation
DLLEXPORT Light* CreateLight (const Transform & l2w, const ParamSet & paramSet)
Definition at line 96 of file spot.cpp.
References CoordinateSystem(), ParamSet::FindOneFloat(), ParamSet::FindOnePoint(), ParamSet::FindOneSpectrum(), Transform::GetInverse(), Normalize(), Translate(), Point::x, Vector::x, Point::y, Vector::y, Point::z, and Vector::z.