pbrt: SDFace Struct Reference
SDFace Struct Reference
Public Member Functions
SDFace ()
int vnum (SDVertex *vert) const
SDFace * nextFace (SDVertex *vert)
SDFace * prevFace (SDVertex *vert)
SDVertex * nextVert (SDVertex *vert)
SDVertex * prevVert (SDVertex *vert)
SDVertex * otherVert (SDVertex *v0, SDVertex *v1)
Public Attributes
SDVertex * v [3]
SDFace * f [3]
SDFace * children [4]
Detailed Description
Definition at line 53 of file loopsubdiv.cpp.
Constructor & Destructor Documentation
SDFace::SDFace () [inline]
Definition at line 55 of file loopsubdiv.cpp.
References children, f, and v.
Member Function Documentation
SDFace* SDFace::nextFace (SDVertex * vert) [inline]
Definition at line 71 of file loopsubdiv.cpp.
References f, and vnum().
Referenced by LoopSubdiv::LoopSubdiv(), SDVertex::oneRing(), and SDVertex::valence().
SDVertex* SDFace::nextVert (SDVertex * vert) [inline]
Definition at line 77 of file loopsubdiv.cpp.
References NEXT, v, and vnum().
Referenced by SDVertex::oneRing().
SDVertex* SDFace::otherVert (SDVertex * v0, SDVertex * v1) [inline]
Definition at line 83 of file loopsubdiv.cpp.
References Severe(), and v.
Referenced by LoopSubdiv::Refine().
SDFace* SDFace::prevFace (SDVertex * vert) [inline]
Definition at line 74 of file loopsubdiv.cpp.
References f, PREV, and vnum().
Referenced by SDVertex::oneRing(), and SDVertex::valence().
SDVertex* SDFace::prevVert (SDVertex * vert) [inline]
Definition at line 80 of file loopsubdiv.cpp.
References PREV, v, and vnum().
Referenced by SDVertex::oneRing().
int SDFace::vnum (SDVertex * vert) const [inline]
Definition at line 65 of file loopsubdiv.cpp.
References Severe(), and v.
Referenced by nextFace(), nextVert(), prevFace(), prevVert(), and LoopSubdiv::Refine().
Member Data Documentation
SDFace* SDFace::children[4]
Definition at line 92 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::Refine(), and SDFace().
SDFace* SDFace::f[3]
Definition at line 91 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::LoopSubdiv(), nextFace(), prevFace(), LoopSubdiv::Refine(), and SDFace().
SDVertex* SDFace::v[3]
Definition at line 90 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::LoopSubdiv(), nextVert(), otherVert(), prevVert(), LoopSubdiv::Refine(), SDFace(), and vnum().
The documentation for this struct was generated from the following file:
loopsubdiv.cpp