pbrt: SDVertex Struct Reference
SDVertex Struct Reference
Public Member Functions
SDVertex (Point pt=Point(0, 0, 0))
int valence ()
void oneRing (Point *P)
Public Attributes
Point P
SDFace * startFace
SDVertex * child
bool regular
bool boundary
Detailed Description
Definition at line 39 of file loopsubdiv.cpp.
Constructor & Destructor Documentation
SDVertex::SDVertex (Point pt = Point(0,0,0)) [inline]
Definition at line 41 of file loopsubdiv.cpp.
Member Function Documentation
void SDVertex::oneRing (Point * P)
Definition at line 449 of file loopsubdiv.cpp.
References boundary, SDFace::nextFace(), SDFace::nextVert(), P, SDFace::prevFace(), SDFace::prevVert(), and startFace.
Referenced by LoopSubdiv::Refine(), LoopSubdiv::weightBoundary(), and LoopSubdiv::weightOneRing().
int SDVertex::valence () [inline]
Definition at line 140 of file loopsubdiv.cpp.
References boundary, SDFace::nextFace(), SDFace::prevFace(), and startFace.
Referenced by LoopSubdiv::LoopSubdiv(), LoopSubdiv::Refine(), LoopSubdiv::weightBoundary(), and LoopSubdiv::weightOneRing().
Member Data Documentation
bool SDVertex::boundary
Definition at line 51 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::LoopSubdiv(), oneRing(), LoopSubdiv::Refine(), and valence().
SDVertex* SDVertex::child
Definition at line 50 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::Refine().
Point SDVertex::P
Definition at line 48 of file loopsubdiv.cpp.
Referenced by oneRing(), LoopSubdiv::Refine(), LoopSubdiv::weightBoundary(), and LoopSubdiv::weightOneRing().
bool SDVertex::regular
Definition at line 51 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::LoopSubdiv(), and LoopSubdiv::Refine().
SDFace* SDVertex::startFace
Definition at line 49 of file loopsubdiv.cpp.
Referenced by LoopSubdiv::LoopSubdiv(), oneRing(), LoopSubdiv::Refine(), and valence().
The documentation for this struct was generated from the following file:
loopsubdiv.cpp