pbrt: VisibilityTester Struct Reference
VisibilityTester Struct Reference
#include <light.h>
Public Member Functions
void SetSegment (const Point &p1, const Point &p2)
void SetRay (const Point &p, const Vector &w)
bool Unoccluded (const Scene *scene) const
Spectrum Transmittance (const Scene *scene) const
Public Attributes
Ray r
Detailed Description
Definition at line 76 of file light.h.
Member Function Documentation
void VisibilityTester::SetRay (const Point & p, const Vector & w) [inline]
Definition at line 81 of file light.h.
References RAY_EPSILON.
Referenced by InfiniteAreaLightIS::Sample_L(), InfiniteAreaLight::Sample_L(), and DistantLight::Sample_L().
void VisibilityTester::SetSegment (const Point & p1, const Point & p2) [inline]
Definition at line 78 of file light.h.
References RAY_EPSILON.
Referenced by SpotLight::Sample_L(), ProjectionLight::Sample_L(), PointLight::Sample_L(), GonioPhotometricLight::Sample_L(), and AreaLight::Sample_L().
Spectrum VisibilityTester::Transmittance (const Scene * scene) const
Definition at line 38 of file light.cpp.
References r, and Scene::Transmittance().
Referenced by EstimateDirect(), WhittedIntegrator::Li(), and SingleScattering::Li().
bool VisibilityTester::Unoccluded (const Scene * scene) const
Definition at line 30 of file light.cpp.
References Scene::IntersectP(), and r.
Referenced by EstimateDirect(), WhittedIntegrator::Li(), and SingleScattering::Li().
Member Data Documentation
Ray VisibilityTester::r
Definition at line 86 of file light.h.
Referenced by Transmittance(), and Unoccluded().
The documentation for this struct was generated from the following files:
light.h
light.cpp