pbrt: ProgressReporter Struct Reference
ProgressReporter Struct Reference
#include <pbrt.h>
Public Member Functions
ProgressReporter (int totalWork, const string &title, int barLength=58)
~ProgressReporter ()
void Update (int num=1) const
void Done () const
ProgressReporter (int totalWork, const string &title, int barLength=58)
~ProgressReporter ()
void Update (int num=1) const
void Done () const
Public Attributes
const int totalPlusses
float frequency
float count
int plussesPrinted
Timer * timer
FILE * outFile
char * buf
char * curSpace
Detailed Description
Definition at line 271 of file pbrt.h.
Constructor & Destructor Documentation
ProgressReporter::ProgressReporter (int totalWork, const string & title, int barLength = 58)
Definition at line 403 of file util.cpp.
References buf, count, curSpace, frequency, outFile, plussesPrinted, Timer::Start(), timer, and totalPlusses.
ProgressReporter::~ProgressReporter ()
Definition at line 425 of file util.cpp.
References buf, and timer.
ProgressReporter::ProgressReporter (int totalWork, const string & title, int barLength = 58)
ProgressReporter::~ProgressReporter ()
Member Function Documentation
void ProgressReporter::Update (int num = 1) const
Definition at line 426 of file util.cpp.
References buf, count, curSpace, frequency, outFile, plussesPrinted, Timer::Time(), timer, and totalPlusses.
Referenced by ApplyImagingPipeline(), BestCandidate2D(), main(), HighContrastOp::Map(), PhotonIntegrator::Preprocess(), ExPhotonIntegrator::Preprocess(), and Redistribute2D().
void ProgressReporter::Done () const
Definition at line 448 of file util.cpp.
References buf, curSpace, outFile, plussesPrinted, Timer::Time(), timer, and totalPlusses.
Referenced by ApplyImagingPipeline(), BestCandidate2D(), main(), HighContrastOp::Map(), PhotonIntegrator::Preprocess(), ExPhotonIntegrator::Preprocess(), and Redistribute2D().
void ProgressReporter::Update (int num = 1) const
void ProgressReporter::Done () const
Member Data Documentation
const int ProgressReporter::totalPlusses
Definition at line 279 of file pbrt.h.
Referenced by Done(), ProgressReporter(), and Update().
float ProgressReporter::frequency
Definition at line 280 of file pbrt.h.
Referenced by ProgressReporter(), and Update().
float ProgressReporter::count [mutable]
Definition at line 281 of file pbrt.h.
Referenced by ProgressReporter(), and Update().
int ProgressReporter::plussesPrinted [mutable]
Definition at line 282 of file pbrt.h.
Referenced by Done(), ProgressReporter(), and Update().
Timer * ProgressReporter::timer [mutable]
Definition at line 283 of file pbrt.h.
Referenced by Done(), ProgressReporter(), Update(), and ~ProgressReporter().
FILE * ProgressReporter::outFile
Definition at line 284 of file pbrt.h.
Referenced by Done(), ProgressReporter(), and Update().
char * ProgressReporter::buf
Definition at line 285 of file pbrt.h.
Referenced by Done(), ProgressReporter(), Update(), and ~ProgressReporter().
char * ProgressReporter::curSpace [mutable]
Definition at line 286 of file pbrt.h.
Referenced by Done(), ProgressReporter(), and Update().
The documentation for this struct was generated from the following files:
pbrt.h
util.cpp