pbrt: Intersection Struct Reference
Intersection Struct Reference
#include <primitive.h>
Public Member Functions
Intersection ()
BSDF * GetBSDF (const RayDifferential &ray) const
Spectrum Le (const Vector &wo) const
Public Attributes
DifferentialGeometry dg
const Primitive * primitive
Transform WorldToObject
Detailed Description
Definition at line 48 of file primitive.h.
Constructor & Destructor Documentation
Intersection::Intersection () [inline]
Definition at line 50 of file primitive.h.
Member Function Documentation
BSDF * Intersection::GetBSDF (const RayDifferential & ray) const
Definition at line 135 of file primitive.cpp.
References DifferentialGeometry::ComputeDifferentials(), dg, Primitive::GetBSDF(), primitive, and WorldToObject.
Referenced by BidirIntegrator::generatePath(), IrradianceCache::IndirectLo(), WhittedIntegrator::Li(), PhotonIntegrator::Li(), PathIntegrator::Li(), IrradianceCache::Li(), IGIIntegrator::Li(), ExPhotonIntegrator::Li(), DirectLighting::Li(), DebugIntegrator::Li(), PhotonIntegrator::Preprocess(), IGIIntegrator::Preprocess(), and ExPhotonIntegrator::Preprocess().
Spectrum Intersection::Le (const Vector & wo) const
Definition at line 142 of file primitive.cpp.
References dg, Primitive::GetAreaLight(), AreaLight::L(), DifferentialGeometry::nn, DifferentialGeometry::p, and primitive.
Referenced by EstimateDirect(), IrradianceCache::IndirectLo(), WhittedIntegrator::Li(), PhotonIntegrator::Li(), PathIntegrator::Li(), IrradianceCache::Li(), IGIIntegrator::Li(), ExPhotonIntegrator::Li(), and DirectLighting::Li().
Member Data Documentation
DifferentialGeometry Intersection::dg
Definition at line 53 of file primitive.h.
Referenced by BidirIntegrator::generatePath(), GetBSDF(), GeometricPrimitive::Intersect(), InstancePrimitive::Intersect(), Le(), WhittedIntegrator::Li(), PhotonIntegrator::Li(), IrradianceCache::Li(), IGIIntegrator::Li(), ExPhotonIntegrator::Li(), DirectLighting::Li(), DebugIntegrator::Li(), PhotonIntegrator::LPhoton(), ExPhotonIntegrator::LPhoton(), PhotonIntegrator::Preprocess(), IGIIntegrator::Preprocess(), and ExPhotonIntegrator::Preprocess().
const Primitive* Intersection::primitive
Definition at line 54 of file primitive.h.
Referenced by EstimateDirect(), GetBSDF(), GeometricPrimitive::Intersect(), and Le().
Transform Intersection::WorldToObject
Definition at line 55 of file primitive.h.
Referenced by GetBSDF(), GeometricPrimitive::Intersect(), and InstancePrimitive::Intersect().
The documentation for this struct was generated from the following files:
primitive.h
primitive.cpp