pbrt: Matrix4x4 Struct Reference
Matrix4x4 Struct Reference
#include <pbrt.h>
Public Member Functions
Matrix4x4 ()
Matrix4x4 (float mat[4][4])
Matrix4x4 (float t00, float t01, float t02, float t03, float t10, float t11, float t12, float t13, float t20, float t21, float t22, float t23, float t30, float t31, float t32, float t33)
Reference< Matrix4x4 > Transpose () const
void Print (ostream &os) const
Reference< Matrix4x4 > Inverse () const
Matrix4x4 ()
Matrix4x4 (float mat[4][4])
Matrix4x4 (float t00, float t01, float t02, float t03, float t10, float t11, float t12, float t13, float t20, float t21, float t22, float t23, float t30, float t31, float t32, float t33)
Reference< Matrix4x4 > Transpose () const
void Print (ostream &os) const
Reference< Matrix4x4 > Inverse () const
Static Public Member Functions
static Reference< Matrix4x4 > Mul (const Reference< Matrix4x4 > &m1, const Reference< Matrix4x4 > &m2)
static Reference< Matrix4x4 > Mul (const Reference< Matrix4x4 > &m1, const Reference< Matrix4x4 > &m2)
Public Attributes
float m [4][4]
Detailed Description
Definition at line 496 of file pbrt.h.
Constructor & Destructor Documentation
Matrix4x4::Matrix4x4 () [inline]
Definition at line 498 of file pbrt.h.
Referenced by Inverse(), and Transpose().
Matrix4x4::Matrix4x4 (float mat[4][4])
Definition at line 109 of file util.cpp.
References m, and memcpy().
Matrix4x4::Matrix4x4 (float t00, float t01, float t02, float t03, float t10, float t11, float t12, float t13, float t20, float t21, float t22, float t23, float t30, float t31, float t32, float t33)
Definition at line 112 of file util.cpp.
References m.
Matrix4x4::Matrix4x4 () [inline]
Definition at line 499 of file pbrtlex.l.
Matrix4x4::Matrix4x4 (float mat[4][4])
Matrix4x4::Matrix4x4 (float t00, float t01, float t02, float t03, float t10, float t11, float t12, float t13, float t20, float t21, float t22, float t23, float t30, float t31, float t32, float t33)
Member Function Documentation
Reference< Matrix4x4 > Matrix4x4::Transpose () const
Definition at line 121 of file util.cpp.
References m, and Matrix4x4().
Referenced by Rotate(), RotateX(), RotateY(), and RotateZ().
void Matrix4x4::Print (ostream & os) const [inline]
Definition at line 510 of file pbrt.h.
static Reference<Matrix4x4> Matrix4x4::Mul (const Reference< Matrix4x4 > & m1, const Reference< Matrix4x4 > & m2) [inline, static]
Definition at line 523 of file pbrt.h.
Referenced by Transform::operator*().
Reference< Matrix4x4 > Matrix4x4::Inverse () const
Definition at line 127 of file util.cpp.
References Error(), m, Matrix4x4(), and memcpy().
Referenced by LookAt().
Reference<Matrix4x4> Matrix4x4::Transpose () const
void Matrix4x4::Print (ostream & os) const [inline]
Definition at line 511 of file pbrtlex.l.
static Reference<Matrix4x4> Matrix4x4::Mul (const Reference< Matrix4x4 > & m1, const Reference< Matrix4x4 > & m2) [inline, static]
Definition at line 524 of file pbrtlex.l.
Reference<Matrix4x4> Matrix4x4::Inverse () const
Member Data Documentation
float Matrix4x4::m
Definition at line 535 of file pbrt.h.
Referenced by Inverse(), Matrix4x4(), and Transpose().
The documentation for this struct was generated from the following files:
pbrt.h
util.cpp