pbrt: KdAccelNode Struct Reference
KdAccelNode Struct Reference
Public Member Functions
void initLeaf (int *primNums, int np, MailboxPrim *mailboxPrims, MemoryArena &arena)
void initInterior (int axis, float s)
float SplitPos () const
int nPrimitives () const
int SplitAxis () const
bool IsLeaf () const
Public Attributes
union {
u_int flags
float split
u_int nPrims
};
union {
u_int aboveChild
MailboxPrim * onePrimitive
MailboxPrim ** primitives
};
Detailed Description
Definition at line 36 of file kdtree.cpp.
Member Function Documentation
void KdAccelNode::initInterior (int axis, float s) [inline]
Definition at line 67 of file kdtree.cpp.
References flags, and split.
Referenced by KdTreeAccel::buildTree().
void KdAccelNode::initLeaf (int * primNums, int np, MailboxPrim * mailboxPrims, MemoryArena & arena) [inline]
Definition at line 38 of file kdtree.cpp.
References StatsRatio::Add(), MemoryArena::Alloc(), flags, StatsCounter::Max(), nPrims, onePrimitive, and primitives.
Referenced by KdTreeAccel::buildTree().
bool KdAccelNode::IsLeaf () const [inline]
Definition at line 77 of file kdtree.cpp.
References flags.
Referenced by KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
int KdAccelNode::nPrimitives () const [inline]
Definition at line 75 of file kdtree.cpp.
References nPrims.
Referenced by KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
int KdAccelNode::SplitAxis () const [inline]
Definition at line 76 of file kdtree.cpp.
References flags.
Referenced by KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
float KdAccelNode::SplitPos () const [inline]
Definition at line 74 of file kdtree.cpp.
References split.
Referenced by KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
Member Data Documentation
union { ... }
union { ... }
u_int KdAccelNode::aboveChild
Definition at line 84 of file kdtree.cpp.
Referenced by KdTreeAccel::buildTree(), KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
u_int KdAccelNode::flags
Definition at line 79 of file kdtree.cpp.
Referenced by initInterior(), initLeaf(), IsLeaf(), and SplitAxis().
u_int KdAccelNode::nPrims
Definition at line 81 of file kdtree.cpp.
Referenced by initLeaf(), and nPrimitives().
MailboxPrim* KdAccelNode::onePrimitive
Definition at line 85 of file kdtree.cpp.
Referenced by initLeaf(), KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
MailboxPrim** KdAccelNode::primitives
Definition at line 86 of file kdtree.cpp.
Referenced by initLeaf(), KdTreeAccel::Intersect(), and KdTreeAccel::IntersectP().
float KdAccelNode::split
Definition at line 80 of file kdtree.cpp.
Referenced by initInterior(), and SplitPos().
The documentation for this struct was generated from the following file:
kdtree.cpp