pbrt: texture.cpp File Reference
texture.cpp File Reference
#include "texture.h"
#include "shape.h"
Defines
#define NOISE_PERM_SIZE 256
Functions
float Grad (int x, int y, int z, float dx, float dy, float dz)
float NoiseWeight (float t)
COREDLL float Noise (float x, float y, float z)
COREDLL float Noise (const Point &P)
COREDLL float FBm (const Point &P, const Vector &dpdx, const Vector &dpdy, float omega, int maxOctaves)
COREDLL float Turbulence (const Point &P, const Vector &dpdx, const Vector &dpdy, float omega, int maxOctaves)
COREDLL float Lanczos (float x, float tau)
Variables
static int NoisePerm [2 *NOISE_PERM_SIZE]
Define Documentation
#define NOISE_PERM_SIZE 256
Definition at line 31 of file texture.cpp.
Referenced by Noise().
Function Documentation
COREDLL float FBm (const Point & P, const Vector & dpdx, const Vector & dpdy, float omega, int maxOctaves)
Definition at line 202 of file texture.cpp.
References Floor2Int(), Vector::LengthSquared(), Log2(), Noise(), and SmoothStep().
Referenced by WindyTexture< T >::Evaluate(), MarbleTexture::Evaluate(), and FBmTexture< T >::Evaluate().
float Grad (int x, int y, int z, float dx, float dy, float dz) [inline]
Definition at line 189 of file texture.cpp.
References NoisePerm.
Referenced by Noise().
COREDLL float Lanczos (float x, float tau)
Definition at line 241 of file texture.cpp.
References M_PI.
Referenced by MIPMap< Spectrum >::resampleWeights().
COREDLL float Noise (const Point & P)
Definition at line 186 of file texture.cpp.
References Noise(), Point::x, Point::y, and Point::z.
COREDLL float Noise (float x, float y, float z)
Definition at line 156 of file texture.cpp.
References Floor2Int(), Grad(), Lerp(), NOISE_PERM_SIZE, and NoiseWeight().
Referenced by DotsTexture< T >::Evaluate(), FBm(), Noise(), and Turbulence().
float NoiseWeight (float t) [inline]
Definition at line 197 of file texture.cpp.
Referenced by Noise().
COREDLL float Turbulence (const Point & P, const Vector & dpdx, const Vector & dpdy, float omega, int maxOctaves)
Definition at line 221 of file texture.cpp.
References Floor2Int(), Vector::LengthSquared(), Log2(), Noise(), and SmoothStep().
Referenced by WrinkledTexture< T >::Evaluate().
Variable Documentation
int NoisePerm[2 *NOISE_PERM_SIZE] [static]
Initial value:
 {
        151, 160, 137, 91, 90, 15, 131, 13, 201, 95, 96,
        53, 194, 233, 7, 225, 140, 36, 103, 30, 69, 142,
        8, 99, 37, 240, 21, 10, 23,
           190,  6, 148, 247, 120, 234, 75, 0, 26, 197, 62, 94, 252, 219, 203, 117, 35, 11, 32, 57, 177, 33,
           88, 237, 149, 56, 87, 174, 20, 125, 136, 171, 168,  68, 175, 74, 165, 71, 134, 139, 48, 27, 166,
           77, 146, 158, 231, 83, 111, 229, 122, 60, 211, 133, 230, 220, 105, 92, 41, 55, 46, 245, 40, 244,
           102, 143, 54,  65, 25, 63, 161,  1, 216, 80, 73, 209, 76, 132, 187, 208,  89, 18, 169, 200, 196,
           135, 130, 116, 188, 159, 86, 164, 100, 109, 198, 173, 186,  3, 64, 52, 217, 226, 250, 124, 123,
           5, 202, 38, 147, 118, 126, 255, 82, 85, 212, 207, 206, 59, 227, 47, 16, 58, 17, 182, 189, 28, 42,
           223, 183, 170, 213, 119, 248, 152,  2, 44, 154, 163,  70, 221, 153, 101, 155, 167,  43, 172, 9,
           129, 22, 39, 253,  19, 98, 108, 110, 79, 113, 224, 232, 178, 185,  112, 104, 218, 246, 97, 228,
           251, 34, 242, 193, 238, 210, 144, 12, 191, 179, 162, 241,  81, 51, 145, 235, 249, 14, 239, 107,
           49, 192, 214,  31, 181, 199, 106, 157, 184,  84, 204, 176, 115, 121, 50, 45, 127,  4, 150, 254,
           138, 236, 205, 93, 222, 114, 67, 29, 24, 72, 243, 141, 128, 195, 78, 66, 215, 61, 156, 180,
           151, 160, 137, 91, 90, 15,
           131, 13, 201, 95, 96, 53, 194, 233, 7, 225, 140, 36, 103, 30, 69, 142, 8, 99, 37, 240, 21, 10, 23,
           190,  6, 148, 247, 120, 234, 75, 0, 26, 197, 62, 94, 252, 219, 203, 117, 35, 11, 32, 57, 177, 33,
           88, 237, 149, 56, 87, 174, 20, 125, 136, 171, 168,  68, 175, 74, 165, 71, 134, 139, 48, 27, 166,
           77, 146, 158, 231, 83, 111, 229, 122, 60, 211, 133, 230, 220, 105, 92, 41, 55, 46, 245, 40, 244,
           102, 143, 54,  65, 25, 63, 161,  1, 216, 80, 73, 209, 76, 132, 187, 208,  89, 18, 169, 200, 196,
           135, 130, 116, 188, 159, 86, 164, 100, 109, 198, 173, 186,  3, 64, 52, 217, 226, 250, 124, 123,
           5, 202, 38, 147, 118, 126, 255, 82, 85, 212, 207, 206, 59, 227, 47, 16, 58, 17, 182, 189, 28, 42,
           223, 183, 170, 213, 119, 248, 152,  2, 44, 154, 163,  70, 221, 153, 101, 155, 167,  43, 172, 9,
           129, 22, 39, 253,  19, 98, 108, 110, 79, 113, 224, 232, 178, 185,  112, 104, 218, 246, 97, 228,
           251, 34, 242, 193, 238, 210, 144, 12, 191, 179, 162, 241,  81, 51, 145, 235, 249, 14, 239, 107,
           49, 192, 214,  31, 181, 199, 106, 157, 184,  84, 204, 176, 115, 121, 50, 45, 127,  4, 150, 254,
           138, 236, 205, 93, 222, 114, 67, 29, 24, 72, 243, 141, 128, 195, 78, 66, 215, 61, 156, 180
}
Definition at line 32 of file texture.cpp.
Referenced by Grad().