pbrt: tifftoexr.cpp File Reference
tifftoexr.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <tiffio.h>
#include <ImfOutputFile.h>
#include <ImfChannelList.h>
#include <ImfFrameBuffer.h>
#include <half.h>
Defines
#define INV_255 .00392156862745098039f
Functions
static void WriteEXR (const char *name, float *rgba, int xRes, int yRes, bool hasAlpha)
static bool ReadTIFF (const char *name, float *&rgba, int &xRes, int &yRes, bool &hasAlpha)
int main (int argc, char *argv[])
Define Documentation
#define INV_255 .00392156862745098039f
Definition at line 17 of file tifftoexr.cpp.
Referenced by ReadTIFF().
Function Documentation
int main (int argc, char * argv[])
Definition at line 22 of file tifftoexr.cpp.
References ReadTIFF(), and WriteEXR().
static bool ReadTIFF (const char * name, float *& rgba, int & xRes, int & yRes, bool & hasAlpha) [static]
Definition at line 67 of file tifftoexr.cpp.
References INV_255.
Referenced by main().
void WriteEXR (const char * name, float * rgba, int xRes, int yRes, bool hasAlpha) [static]
Definition at line 37 of file tifftoexr.cpp.