pbrt: transform.cpp File Reference
transform.cpp File Reference
#include "transform.h"
#include "shape.h"
Functions
ostream & operator<< (ostream &os, const Transform &t)
COREDLL Transform Translate (const Vector &delta)
COREDLL Transform Scale (float x, float y, float z)
Transform RotateX (float angle)
Transform RotateY (float angle)
Transform RotateZ (float angle)
Transform Rotate (float angle, const Vector &axis)
Transform LookAt (const Point &pos, const Point &look, const Vector &up)
Transform COREDLL Orthographic (float znear, float zfar)
COREDLL Transform Perspective (float fov, float n, float f)
Function Documentation
Transform LookAt (const Point & pos, const Point & look, const Vector & up)
Definition at line 113 of file transform.cpp.
References Cross(), Matrix4x4::Inverse(), Normalize(), Vector::x, Point::x, Vector::y, Point::y, Vector::z, and Point::z.
Referenced by pbrtLookAt().
ostream& operator<< (ostream & os, const Transform & t)
Definition at line 28 of file transform.cpp.
References Transform::m.
Transform COREDLL Orthographic (float znear, float zfar)
Definition at line 177 of file transform.cpp.
References Scale(), and Translate().
COREDLL Transform Perspective (float fov, float n, float f)
Definition at line 182 of file transform.cpp.
References Radians(), and Scale().
Referenced by ProjectionLight::ProjectionLight().
Transform Rotate (float angle, const Vector & axis)
Definition at line 84 of file transform.cpp.
References Normalize(), Radians(), Matrix4x4::Transpose(), Vector::x, Vector::y, and Vector::z.
Referenced by pbrtRotate().
Transform RotateX (float angle)
Definition at line 56 of file transform.cpp.
References Radians(), and Matrix4x4::Transpose().
Transform RotateY (float angle)
Definition at line 65 of file transform.cpp.
References Radians(), and Matrix4x4::Transpose().
Transform RotateZ (float angle)
Definition at line 75 of file transform.cpp.
References Radians(), and Matrix4x4::Transpose().
COREDLL Transform Scale (float x, float y, float z)
Definition at line 44 of file transform.cpp.
Referenced by Orthographic(), pbrtScale(), Perspective(), and ProjectiveCamera::ProjectiveCamera().
COREDLL Transform Translate (const Vector & delta)
Definition at line 32 of file transform.cpp.
References Vector::x, Vector::y, and Vector::z.
Referenced by CreateLight(), Orthographic(), pbrtTranslate(), and ProjectiveCamera::ProjectiveCamera().