pbrt: trianglemesh.cpp File Reference
trianglemesh.cpp File Reference
#include "shape.h"
#include "paramset.h"
Classes
class TriangleMesh
class Triangle
Functions
DLLEXPORT Shape * CreateShape (const Transform &o2w, bool reverseOrientation, const ParamSet &params)
Function Documentation
DLLEXPORT Shape* CreateShape (const Transform & o2w, bool reverseOrientation, const ParamSet & params)
Definition at line 350 of file trianglemesh.cpp.
References Cross(), Error(), ParamSet::FindFloat(), ParamSet::FindInt(), ParamSet::FindNormal(), ParamSet::FindPoint(), ParamSet::FindVector(), Vector::Length(), N, and Warning().