pbrt: volumegrid.cpp File Reference
volumegrid.cpp File Reference
#include "volume.h"
Classes
class VolumeGrid
Functions
DLLEXPORT VolumeRegion * CreateVolumeRegion (const Transform &volume2world, const ParamSet &params)
Function Documentation
DLLEXPORT VolumeRegion* CreateVolumeRegion (const Transform & volume2world, const ParamSet & params)
Definition at line 85 of file volumegrid.cpp.
References Error(), ParamSet::FindFloat(), ParamSet::FindOneFloat(), ParamSet::FindOneInt(), ParamSet::FindOnePoint(), ParamSet::FindOneSpectrum(), DensityRegion::g, VolumeGrid::nx, VolumeGrid::ny, VolumeGrid::nz, DensityRegion::sigma_a(), DensityRegion::sigma_s(), and VolumeGrid::VolumeGrid().