pbrt: volume.cpp File Reference
volume.cpp File Reference
#include "volume.h"
Functions
COREDLL float PhaseIsotropic (const Vector &, const Vector &)
COREDLL float PhaseRayleigh (const Vector &w, const Vector &wp)
COREDLL float PhaseMieHazy (const Vector &w, const Vector &wp)
COREDLL float PhaseMieMurky (const Vector &w, const Vector &wp)
COREDLL float PhaseHG (const Vector &w, const Vector &wp, float g)
COREDLL float PhaseSchlick (const Vector &w, const Vector &wp, float g)
Function Documentation
COREDLL float PhaseHG (const Vector & w, const Vector & wp, float g)
Definition at line 44 of file volume.cpp.
References Dot(), and M_PI.
Referenced by HGPdf(), DensityRegion::p(), and HomogeneousVolume::p().
COREDLL float PhaseIsotropic (const Vector & , const Vector &)
Definition at line 28 of file volume.cpp.
References M_PI.
COREDLL float PhaseMieHazy (const Vector & w, const Vector & wp)
Definition at line 35 of file volume.cpp.
References Dot(), and M_PI.
COREDLL float PhaseMieMurky (const Vector & w, const Vector & wp)
Definition at line 39 of file volume.cpp.
References Dot(), and M_PI.
COREDLL float PhaseRayleigh (const Vector & w, const Vector & wp)
Definition at line 31 of file volume.cpp.
References Dot(), and M_PI.
COREDLL float PhaseSchlick (const Vector & w, const Vector & wp, float g)
Definition at line 50 of file volume.cpp.
References Dot(), and M_PI.